export const defaultAdminOfferFields = [
  "id",
  "seller_id",
  "variant_id",
  "shipping_profile_id",
  "sku",
  "ean",
  "upc",
  "created_by",
  "metadata",
  "created_at",
  "updated_at",
  "deleted_at",
  "seller.id",
  "seller.name",
  "seller.handle",
  "product_variant.id",
  "product_variant.title",
  "product_variant.sku",
  "shipping_profile.id",
  "shipping_profile.name",
  "prices.id",
  "prices.amount",
  "prices.currency_code",
  "prices.min_quantity",
  "prices.max_quantity",
  "prices.price_rules.attribute",
  "prices.price_rules.value",
  "inventory_items.inventory_item_id",
  "inventory_items.required_quantity",
  "inventory_items.id",
  "inventory_items.sku",
]

export const adminOfferQueryConfig = {
  list: {
    defaults: defaultAdminOfferFields,
    isList: true,
  },
  retrieve: {
    defaults: defaultAdminOfferFields,
    isList: false,
  },
}
