export const defaultAdminOfferFields = [
  "id",
  "seller_id",
  "variant_id",
  "shipping_profile_id",
  "price_set_id",
  "sku",
  "ean",
  "upc",
  "created_by",
  "metadata",
  "created_at",
  "updated_at",
  "deleted_at",
  "seller.id",
  "seller.name",
  "seller.handle",
  "product_variant.id",
  "product_variant.title",
  "product_variant.sku",
  "shipping_profile.id",
  "shipping_profile.name",
  "price_set.id",
  "price_set.prices.id",
  "price_set.prices.amount",
  "price_set.prices.currency_code",
  "price_set.prices.min_quantity",
  "price_set.prices.max_quantity",
  "inventory_items.inventory_item_id",
  "inventory_items.required_quantity",
  "inventory_items.id",
  "inventory_items.sku",
]

export const adminOfferQueryConfig = {
  list: {
    defaults: defaultAdminOfferFields,
    isList: true,
  },
  retrieve: {
    defaults: defaultAdminOfferFields,
    isList: false,
  },
}
