export const VALID_FILE_EXTENSIONS = [".tsx", ".ts", ".jsx", ".js"]

export const CONFIG_VIRTUAL_MODULE = "virtual:mercur/config"
export const ROUTES_VIRTUAL_MODULE = "virtual:mercur/routes"
export const COMPONENTS_VIRTUAL_MODULE = "virtual:mercur/components"
export const MENU_ITEMS_VIRTUAL_MODULE = "virtual:mercur/menu-items"
export const I18N_VIRTUAL_MODULE = "virtual:mercur/i18n"
export const MEDUSA_ROUTES_VIRTUAL_MODULE = "virtual:medusa/routes"
export const MEDUSA_MENU_ITEMS_VIRTUAL_MODULE = "virtual:medusa/menu-items"
export const MEDUSA_I18N_VIRTUAL_MODULE = "virtual:medusa/i18n"
export const MEDUSA_WIDGETS_VIRTUAL_MODULE = "virtual:medusa/widgets"
export const MEDUSA_FORMS_VIRTUAL_MODULE = "virtual:medusa/forms"
export const MEDUSA_DISPLAYS_VIRTUAL_MODULE = "virtual:medusa/displays"
export const MEDUSA_LINKS_VIRTUAL_MODULE = "virtual:medusa/links"

export const RESOLVED_CONFIG_MODULE = "\0" + CONFIG_VIRTUAL_MODULE
export const RESOLVED_ROUTES_MODULE = "\0" + ROUTES_VIRTUAL_MODULE
export const RESOLVED_COMPONENTS_MODULE = "\0" + COMPONENTS_VIRTUAL_MODULE
export const RESOLVED_MENU_ITEMS_MODULE = "\0" + MENU_ITEMS_VIRTUAL_MODULE
export const RESOLVED_I18N_MODULE = "\0" + I18N_VIRTUAL_MODULE
export const RESOLVED_MEDUSA_ROUTES_MODULE = "\0" + MEDUSA_ROUTES_VIRTUAL_MODULE
export const RESOLVED_MEDUSA_MENU_ITEMS_MODULE =
    "\0" + MEDUSA_MENU_ITEMS_VIRTUAL_MODULE
export const RESOLVED_MEDUSA_I18N_MODULE = "\0" + MEDUSA_I18N_VIRTUAL_MODULE
export const RESOLVED_MEDUSA_WIDGETS_MODULE = "\0" + MEDUSA_WIDGETS_VIRTUAL_MODULE
export const RESOLVED_MEDUSA_FORMS_MODULE = "\0" + MEDUSA_FORMS_VIRTUAL_MODULE
export const RESOLVED_MEDUSA_DISPLAYS_MODULE =
    "\0" + MEDUSA_DISPLAYS_VIRTUAL_MODULE
export const RESOLVED_MEDUSA_LINKS_MODULE = "\0" + MEDUSA_LINKS_VIRTUAL_MODULE

export const VIRTUAL_MODULES = [
    CONFIG_VIRTUAL_MODULE,
    ROUTES_VIRTUAL_MODULE,
    COMPONENTS_VIRTUAL_MODULE,
    MENU_ITEMS_VIRTUAL_MODULE,
    I18N_VIRTUAL_MODULE,
    MEDUSA_ROUTES_VIRTUAL_MODULE,
    MEDUSA_MENU_ITEMS_VIRTUAL_MODULE,
    MEDUSA_I18N_VIRTUAL_MODULE,
    MEDUSA_WIDGETS_VIRTUAL_MODULE,
    MEDUSA_FORMS_VIRTUAL_MODULE,
    MEDUSA_DISPLAYS_VIRTUAL_MODULE,
    MEDUSA_LINKS_VIRTUAL_MODULE,
]
