// This file is generated automatically by Mercur CLI
// Do not edit this file manually

export type Routes = {
    admin: {
        apiKeys: typeof import("@medusajs/medusa/api/admin/api-keys/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/api-keys/[id]/route") & {
                revoke: typeof import("@medusajs/medusa/api/admin/api-keys/[id]/revoke/route");
                salesChannels: typeof import("@medusajs/medusa/api/admin/api-keys/[id]/sales-channels/route");
            };
        };
        campaigns: typeof import("@medusajs/medusa/api/admin/campaigns/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/campaigns/[id]/route") & {
                promotions: typeof import("@medusajs/medusa/api/admin/campaigns/[id]/promotions/route");
            };
        };
        claims: typeof import("@medusajs/medusa/api/admin/claims/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/claims/[id]/route") & {
                cancel: typeof import("@medusajs/medusa/api/admin/claims/[id]/cancel/route");
                claimItems: typeof import("@medusajs/medusa/api/admin/claims/[id]/claim-items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/claim-items/[action_id]/route");
                };
                inbound: {
                    items: typeof import("@medusajs/medusa/api/admin/claims/[id]/inbound/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/inbound/items/[action_id]/route");
                    };
                    shippingMethod: typeof import("@medusajs/medusa/api/admin/claims/[id]/inbound/shipping-method/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/inbound/shipping-method/[action_id]/route");
                    };
                };
                outbound: {
                    items: typeof import("@medusajs/medusa/api/admin/claims/[id]/outbound/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/outbound/items/[action_id]/route");
                    };
                    shippingMethod: typeof import("@medusajs/medusa/api/admin/claims/[id]/outbound/shipping-method/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/outbound/shipping-method/[action_id]/route");
                    };
                };
                request: typeof import("@medusajs/medusa/api/admin/claims/[id]/request/route");
            };
        };
        collections: typeof import("@medusajs/medusa/api/admin/collections/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/collections/[id]/route") & {
                products: typeof import("@medusajs/medusa/api/admin/collections/[id]/products/route");
            };
        };
        currencies: typeof import("@medusajs/medusa/api/admin/currencies/route") & {
            $code: typeof import("@medusajs/medusa/api/admin/currencies/[code]/route");
        };
        customerGroups: typeof import("@medusajs/medusa/api/admin/customer-groups/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/customer-groups/[id]/route") & {
                customers: typeof import("@medusajs/medusa/api/admin/customer-groups/[id]/customers/route");
            };
        };
        customers: typeof import("@medusajs/medusa/api/admin/customers/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/customers/[id]/route") & {
                addresses: typeof import("@medusajs/medusa/api/admin/customers/[id]/addresses/route") & {
                    $addressId: typeof import("@medusajs/medusa/api/admin/customers/[id]/addresses/[address_id]/route");
                };
                customerGroups: typeof import("@medusajs/medusa/api/admin/customers/[id]/customer-groups/route");
            };
        };
        draftOrders: typeof import("@medusajs/medusa/api/admin/draft-orders/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/route") & {
                convertToOrder: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/convert-to-order/route");
                edit: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/route") & {
                    confirm: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/confirm/route");
                    items: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/items/[action_id]/route");
                        item: {
                            $itemId: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/items/item/[item_id]/route");
                        };
                    };
                    promotions: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/promotions/route");
                    request: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/request/route");
                    shippingMethods: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/shipping-methods/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/shipping-methods/[action_id]/route");
                        method: {
                            $methodId: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/shipping-methods/method/[method_id]/route");
                        };
                    };
                };
            };
        };
        exchanges: typeof import("@medusajs/medusa/api/admin/exchanges/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/route") & {
                cancel: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/cancel/route");
                inbound: {
                    items: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/inbound/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/inbound/items/[action_id]/route");
                    };
                    shippingMethod: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/inbound/shipping-method/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/inbound/shipping-method/[action_id]/route");
                    };
                };
                outbound: {
                    items: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/outbound/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/outbound/items/[action_id]/route");
                    };
                    shippingMethod: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/outbound/shipping-method/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/outbound/shipping-method/[action_id]/route");
                    };
                };
                request: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/request/route");
            };
        };
        featureFlags: typeof import("@medusajs/medusa/api/admin/feature-flags/route");
        fulfillmentProviders: typeof import("@medusajs/medusa/api/admin/fulfillment-providers/route") & {
            $id: {
                options: typeof import("@medusajs/medusa/api/admin/fulfillment-providers/[id]/options/route");
            };
        };
        fulfillmentSets: {
            $id: typeof import("@medusajs/medusa/api/admin/fulfillment-sets/[id]/route") & {
                serviceZones: typeof import("@medusajs/medusa/api/admin/fulfillment-sets/[id]/service-zones/route") & {
                    $zoneId: typeof import("@medusajs/medusa/api/admin/fulfillment-sets/[id]/service-zones/[zone_id]/route");
                };
            };
        };
        fulfillments: typeof import("@medusajs/medusa/api/admin/fulfillments/route") & {
            $id: {
                cancel: typeof import("@medusajs/medusa/api/admin/fulfillments/[id]/cancel/route");
                shipment: typeof import("@medusajs/medusa/api/admin/fulfillments/[id]/shipment/route");
            };
        };
        index: {
            details: typeof import("@medusajs/medusa/api/admin/index/details/route");
            sync: typeof import("@medusajs/medusa/api/admin/index/sync/route");
        };
        inventoryItems: typeof import("@medusajs/medusa/api/admin/inventory-items/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/inventory-items/[id]/route") & {
                locationLevels: typeof import("@medusajs/medusa/api/admin/inventory-items/[id]/location-levels/route") & {
                    $locationId: typeof import("@medusajs/medusa/api/admin/inventory-items/[id]/location-levels/[location_id]/route");
                    batch: typeof import("@medusajs/medusa/api/admin/inventory-items/[id]/location-levels/batch/route");
                };
            };
            locationLevels: {
                batch: typeof import("@medusajs/medusa/api/admin/inventory-items/location-levels/batch/route");
            };
        };
        invites: typeof import("@medusajs/medusa/api/admin/invites/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/invites/[id]/route") & {
                resend: typeof import("@medusajs/medusa/api/admin/invites/[id]/resend/route");
            };
            accept: typeof import("@medusajs/medusa/api/admin/invites/accept/route");
        };
        locales: typeof import("@medusajs/medusa/api/admin/locales/route") & {
            $code: typeof import("@medusajs/medusa/api/admin/locales/[code]/route");
        };
        notifications: typeof import("@medusajs/medusa/api/admin/notifications/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/notifications/[id]/route");
        };
        orderChanges: {
            $id: typeof import("@medusajs/medusa/api/admin/order-changes/[id]/route");
        };
        orderEdits: typeof import("@medusajs/medusa/api/admin/order-edits/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/route") & {
                confirm: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/confirm/route");
                items: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/items/[action_id]/route");
                    item: {
                        $itemId: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/items/item/[item_id]/route");
                    };
                };
                request: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/request/route");
                shippingMethod: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/shipping-method/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/shipping-method/[action_id]/route");
                };
            };
        };
        orders: typeof import("@medusajs/medusa/api/admin/orders/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/orders/[id]/route") & {
                archive: typeof import("@medusajs/medusa/api/admin/orders/[id]/archive/route");
                cancel: typeof import("@medusajs/medusa/api/admin/orders/[id]/cancel/route");
                changes: typeof import("@medusajs/medusa/api/admin/orders/[id]/changes/route");
                complete: typeof import("@medusajs/medusa/api/admin/orders/[id]/complete/route");
                creditLines: typeof import("@medusajs/medusa/api/admin/orders/[id]/credit-lines/route");
                fulfillments: typeof import("@medusajs/medusa/api/admin/orders/[id]/fulfillments/route") & {
                    $fulfillmentId: {
                        cancel: typeof import("@medusajs/medusa/api/admin/orders/[id]/fulfillments/[fulfillment_id]/cancel/route");
                        markAsDelivered: typeof import("@medusajs/medusa/api/admin/orders/[id]/fulfillments/[fulfillment_id]/mark-as-delivered/route");
                        shipments: typeof import("@medusajs/medusa/api/admin/orders/[id]/fulfillments/[fulfillment_id]/shipments/route");
                    };
                };
                lineItems: typeof import("@medusajs/medusa/api/admin/orders/[id]/line-items/route");
                preview: typeof import("@medusajs/medusa/api/admin/orders/[id]/preview/route");
                shippingOptions: typeof import("@medusajs/medusa/api/admin/orders/[id]/shipping-options/route");
                transfer: typeof import("@medusajs/medusa/api/admin/orders/[id]/transfer/route") & {
                    cancel: typeof import("@medusajs/medusa/api/admin/orders/[id]/transfer/cancel/route");
                };
            };
            export: typeof import("@medusajs/medusa/api/admin/orders/export/route");
        };
        paymentCollections: typeof import("@medusajs/medusa/api/admin/payment-collections/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/payment-collections/[id]/route") & {
                markAsPaid: typeof import("@medusajs/medusa/api/admin/payment-collections/[id]/mark-as-paid/route");
            };
        };
        payments: typeof import("@medusajs/medusa/api/admin/payments/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/payments/[id]/route") & {
                capture: typeof import("@medusajs/medusa/api/admin/payments/[id]/capture/route");
                refund: typeof import("@medusajs/medusa/api/admin/payments/[id]/refund/route");
            };
            paymentProviders: typeof import("@medusajs/medusa/api/admin/payments/payment-providers/route");
        };
        plugins: typeof import("@medusajs/medusa/api/admin/plugins/route");
        priceLists: typeof import("@medusajs/medusa/api/admin/price-lists/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/price-lists/[id]/route") & {
                prices: typeof import("@medusajs/medusa/api/admin/price-lists/[id]/prices/route") & {
                    batch: typeof import("@medusajs/medusa/api/admin/price-lists/[id]/prices/batch/route");
                };
                products: typeof import("@medusajs/medusa/api/admin/price-lists/[id]/products/route");
            };
        };
        pricePreferences: typeof import("@medusajs/medusa/api/admin/price-preferences/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/price-preferences/[id]/route");
        };
        productCategories: typeof import("@medusajs/medusa/api/admin/product-categories/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/product-categories/[id]/route") & {
                products: typeof import("@medusajs/medusa/api/admin/product-categories/[id]/products/route");
            };
        };
        productTags: typeof import("@medusajs/medusa/api/admin/product-tags/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/product-tags/[id]/route");
        };
        productTypes: typeof import("@medusajs/medusa/api/admin/product-types/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/product-types/[id]/route");
        };
        productVariants: typeof import("@medusajs/medusa/api/admin/product-variants/route");
        products: typeof import("@medusajs/medusa/api/admin/products/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/products/[id]/route") & {
                images: {
                    $imageId: {
                        variants: {
                            batch: typeof import("@medusajs/medusa/api/admin/products/[id]/images/[image_id]/variants/batch/route");
                        };
                    };
                };
                options: typeof import("@medusajs/medusa/api/admin/products/[id]/options/route") & {
                    $optionId: typeof import("@medusajs/medusa/api/admin/products/[id]/options/[option_id]/route");
                };
                variants: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/route") & {
                    $variantId: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/[variant_id]/route") & {
                        images: {
                            batch: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/[variant_id]/images/batch/route");
                        };
                        inventoryItems: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/[variant_id]/inventory-items/route") & {
                            $inventoryItemId: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/[variant_id]/inventory-items/[inventory_item_id]/route");
                        };
                    };
                    batch: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/batch/route");
                    inventoryItems: {
                        batch: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/inventory-items/batch/route");
                    };
                };
            };
            batch: typeof import("@medusajs/medusa/api/admin/products/batch/route");
            export: typeof import("@medusajs/medusa/api/admin/products/export/route");
            import: typeof import("@medusajs/medusa/api/admin/products/import/route") & {
                $transactionId: {
                    confirm: typeof import("@medusajs/medusa/api/admin/products/import/[transaction_id]/confirm/route");
                };
            };
            imports: typeof import("@medusajs/medusa/api/admin/products/imports/route") & {
                $transactionId: {
                    confirm: typeof import("@medusajs/medusa/api/admin/products/imports/[transaction_id]/confirm/route");
                };
            };
        };
        promotions: typeof import("@medusajs/medusa/api/admin/promotions/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/promotions/[id]/route") & {
                $ruleType: typeof import("@medusajs/medusa/api/admin/promotions/[id]/[rule_type]/route");
                buyRules: {
                    batch: typeof import("@medusajs/medusa/api/admin/promotions/[id]/buy-rules/batch/route");
                };
                rules: {
                    batch: typeof import("@medusajs/medusa/api/admin/promotions/[id]/rules/batch/route");
                };
                targetRules: {
                    batch: typeof import("@medusajs/medusa/api/admin/promotions/[id]/target-rules/batch/route");
                };
            };
            ruleAttributeOptions: {
                $ruleType: typeof import("@medusajs/medusa/api/admin/promotions/rule-attribute-options/[rule_type]/route");
            };
            ruleValueOptions: {
                $ruleType: {
                    $ruleAttributeId: typeof import("@medusajs/medusa/api/admin/promotions/rule-value-options/[rule_type]/[rule_attribute_id]/route");
                };
            };
        };
        rbac: {
            policies: typeof import("@medusajs/medusa/api/admin/rbac/policies/route") & {
                $id: typeof import("@medusajs/medusa/api/admin/rbac/policies/[id]/route");
            };
            roles: typeof import("@medusajs/medusa/api/admin/rbac/roles/route") & {
                $id: typeof import("@medusajs/medusa/api/admin/rbac/roles/[id]/route") & {
                    policies: typeof import("@medusajs/medusa/api/admin/rbac/roles/[id]/policies/route") & {
                        $policyId: typeof import("@medusajs/medusa/api/admin/rbac/roles/[id]/policies/[policy_id]/route");
                    };
                };
            };
        };
        refundReasons: typeof import("@medusajs/medusa/api/admin/refund-reasons/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/refund-reasons/[id]/route");
        };
        regions: typeof import("@medusajs/medusa/api/admin/regions/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/regions/[id]/route");
        };
        reservations: typeof import("@medusajs/medusa/api/admin/reservations/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/reservations/[id]/route");
        };
        returnReasons: typeof import("@medusajs/medusa/api/admin/return-reasons/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/return-reasons/[id]/route");
        };
        returns: typeof import("@medusajs/medusa/api/admin/returns/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/returns/[id]/route") & {
                cancel: typeof import("@medusajs/medusa/api/admin/returns/[id]/cancel/route");
                dismissItems: typeof import("@medusajs/medusa/api/admin/returns/[id]/dismiss-items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/returns/[id]/dismiss-items/[action_id]/route");
                };
                receive: typeof import("@medusajs/medusa/api/admin/returns/[id]/receive/route") & {
                    confirm: typeof import("@medusajs/medusa/api/admin/returns/[id]/receive/confirm/route");
                };
                receiveItems: typeof import("@medusajs/medusa/api/admin/returns/[id]/receive-items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/returns/[id]/receive-items/[action_id]/route");
                };
                request: typeof import("@medusajs/medusa/api/admin/returns/[id]/request/route");
                requestItems: typeof import("@medusajs/medusa/api/admin/returns/[id]/request-items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/returns/[id]/request-items/[action_id]/route");
                };
                shippingMethod: typeof import("@medusajs/medusa/api/admin/returns/[id]/shipping-method/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/returns/[id]/shipping-method/[action_id]/route");
                };
            };
        };
        salesChannels: typeof import("@medusajs/medusa/api/admin/sales-channels/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/sales-channels/[id]/route") & {
                products: typeof import("@medusajs/medusa/api/admin/sales-channels/[id]/products/route");
            };
        };
        shippingOptionTypes: typeof import("@medusajs/medusa/api/admin/shipping-option-types/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/shipping-option-types/[id]/route");
        };
        shippingOptions: typeof import("@medusajs/medusa/api/admin/shipping-options/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/shipping-options/[id]/route") & {
                rules: {
                    batch: typeof import("@medusajs/medusa/api/admin/shipping-options/[id]/rules/batch/route");
                };
            };
        };
        shippingProfiles: typeof import("@medusajs/medusa/api/admin/shipping-profiles/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/shipping-profiles/[id]/route");
        };
        stockLocations: typeof import("@medusajs/medusa/api/admin/stock-locations/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/stock-locations/[id]/route") & {
                fulfillmentProviders: typeof import("@medusajs/medusa/api/admin/stock-locations/[id]/fulfillment-providers/route");
                fulfillmentSets: typeof import("@medusajs/medusa/api/admin/stock-locations/[id]/fulfillment-sets/route");
                salesChannels: typeof import("@medusajs/medusa/api/admin/stock-locations/[id]/sales-channels/route");
            };
        };
        stores: typeof import("@medusajs/medusa/api/admin/stores/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/stores/[id]/route");
        };
        taxProviders: typeof import("@medusajs/medusa/api/admin/tax-providers/route");
        taxRates: typeof import("@medusajs/medusa/api/admin/tax-rates/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/tax-rates/[id]/route") & {
                rules: typeof import("@medusajs/medusa/api/admin/tax-rates/[id]/rules/route") & {
                    $ruleId: typeof import("@medusajs/medusa/api/admin/tax-rates/[id]/rules/[rule_id]/route");
                };
            };
        };
        taxRegions: typeof import("@medusajs/medusa/api/admin/tax-regions/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/tax-regions/[id]/route");
        };
        translations: typeof import("@medusajs/medusa/api/admin/translations/route") & {
            batch: typeof import("@medusajs/medusa/api/admin/translations/batch/route");
            entities: typeof import("@medusajs/medusa/api/admin/translations/entities/route");
            settings: typeof import("@medusajs/medusa/api/admin/translations/settings/route") & {
                batch: typeof import("@medusajs/medusa/api/admin/translations/settings/batch/route");
            };
            statistics: typeof import("@medusajs/medusa/api/admin/translations/statistics/route");
        };
        uploads: typeof import("@medusajs/medusa/api/admin/uploads/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/uploads/[id]/route");
            presignedUrls: typeof import("@medusajs/medusa/api/admin/uploads/presigned-urls/route");
        };
        users: typeof import("@medusajs/medusa/api/admin/users/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/users/[id]/route");
            me: typeof import("@medusajs/medusa/api/admin/users/me/route");
        };
        views: {
            $entity: {
                columns: typeof import("@medusajs/medusa/api/admin/views/[entity]/columns/route");
                configurations: typeof import("@medusajs/medusa/api/admin/views/[entity]/configurations/route") & {
                    $id: typeof import("@medusajs/medusa/api/admin/views/[entity]/configurations/[id]/route");
                    active: typeof import("@medusajs/medusa/api/admin/views/[entity]/configurations/active/route");
                };
            };
        };
        workflowsExecutions: typeof import("@medusajs/medusa/api/admin/workflows-executions/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/workflows-executions/[id]/route");
            $workflowId: {
                $transactionId: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/[transaction_id]/route") & {
                    $stepId: {
                        subscribe: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/[transaction_id]/[step_id]/subscribe/route");
                    };
                };
                run: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/run/route");
                steps: {
                    failure: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/steps/failure/route");
                    success: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/steps/success/route");
                };
                subscribe: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/subscribe/route");
            };
        };
        commissionRates: typeof import("@mercurjs/core-plugin/api/admin/commission-rates/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/admin/commission-rates/[id]/route") & {
                rules: typeof import("@mercurjs/core-plugin/api/admin/commission-rates/[id]/rules/route");
            };
        };
        orderGroups: typeof import("@mercurjs/core-plugin/api/admin/order-groups/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/admin/order-groups/[id]/route");
        };
        payouts: typeof import("@mercurjs/core-plugin/api/admin/payouts/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/admin/payouts/[id]/route");
        };
        sellers: typeof import("@mercurjs/core-plugin/api/admin/sellers/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/admin/sellers/[id]/route");
        };
        reviews: typeof import("../../src/reviews/api/admin/reviews/route") & {
            $id: typeof import("../../src/reviews/api/admin/reviews/[id]/route");
        };
    };
    auth: {
        $actorType: {
            $authProvider: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/route") & {
                callback: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/callback/route");
                register: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/register/route");
                resetPassword: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/reset-password/route");
                update: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/update/route");
            };
        };
        session: typeof import("@medusajs/medusa/api/auth/session/route");
        token: {
            refresh: typeof import("@medusajs/medusa/api/auth/token/refresh/route");
        };
    };
    store: {
        carts: typeof import("@medusajs/medusa/api/store/carts/route") & {
            $id: typeof import("@medusajs/medusa/api/store/carts/[id]/route") & {
                complete: typeof import("@mercurjs/core-plugin/api/store/carts/[id]/complete/route");
                customer: typeof import("@medusajs/medusa/api/store/carts/[id]/customer/route");
                lineItems: typeof import("@medusajs/medusa/api/store/carts/[id]/line-items/route") & {
                    $lineId: typeof import("@medusajs/medusa/api/store/carts/[id]/line-items/[line_id]/route");
                };
                promotions: typeof import("@mercurjs/core-plugin/api/store/carts/[id]/promotions/route");
                shippingMethods: typeof import("@mercurjs/core-plugin/api/store/carts/[id]/shipping-methods/route");
                taxes: typeof import("@medusajs/medusa/api/store/carts/[id]/taxes/route");
            };
        };
        collections: typeof import("@medusajs/medusa/api/store/collections/route") & {
            $id: typeof import("@medusajs/medusa/api/store/collections/[id]/route");
        };
        currencies: typeof import("@medusajs/medusa/api/store/currencies/route") & {
            $code: typeof import("@medusajs/medusa/api/store/currencies/[code]/route");
        };
        customers: typeof import("@medusajs/medusa/api/store/customers/route") & {
            me: typeof import("@medusajs/medusa/api/store/customers/me/route") & {
                addresses: typeof import("@medusajs/medusa/api/store/customers/me/addresses/route") & {
                    $addressId: typeof import("@medusajs/medusa/api/store/customers/me/addresses/[address_id]/route");
                };
            };
        };
        locales: typeof import("@medusajs/medusa/api/store/locales/route");
        orders: typeof import("@medusajs/medusa/api/store/orders/route") & {
            $id: typeof import("@medusajs/medusa/api/store/orders/[id]/route") & {
                transfer: {
                    accept: typeof import("@medusajs/medusa/api/store/orders/[id]/transfer/accept/route");
                    cancel: typeof import("@medusajs/medusa/api/store/orders/[id]/transfer/cancel/route");
                    decline: typeof import("@medusajs/medusa/api/store/orders/[id]/transfer/decline/route");
                    request: typeof import("@medusajs/medusa/api/store/orders/[id]/transfer/request/route");
                };
            };
        };
        paymentCollections: typeof import("@medusajs/medusa/api/store/payment-collections/route") & {
            $id: {
                paymentSessions: typeof import("@medusajs/medusa/api/store/payment-collections/[id]/payment-sessions/route");
            };
        };
        paymentProviders: typeof import("@medusajs/medusa/api/store/payment-providers/route");
        productCategories: typeof import("@medusajs/medusa/api/store/product-categories/route") & {
            $id: typeof import("@medusajs/medusa/api/store/product-categories/[id]/route");
        };
        productTags: typeof import("@medusajs/medusa/api/store/product-tags/route") & {
            $id: typeof import("@medusajs/medusa/api/store/product-tags/[id]/route");
        };
        productTypes: typeof import("@medusajs/medusa/api/store/product-types/route") & {
            $id: typeof import("@medusajs/medusa/api/store/product-types/[id]/route");
        };
        productVariants: typeof import("@medusajs/medusa/api/store/product-variants/route") & {
            $id: typeof import("@medusajs/medusa/api/store/product-variants/[id]/route");
        };
        products: typeof import("@medusajs/medusa/api/store/products/route") & {
            $id: typeof import("@medusajs/medusa/api/store/products/[id]/route");
        };
        regions: typeof import("@medusajs/medusa/api/store/regions/route") & {
            $id: typeof import("@medusajs/medusa/api/store/regions/[id]/route");
        };
        returnReasons: typeof import("@medusajs/medusa/api/store/return-reasons/route") & {
            $id: typeof import("@medusajs/medusa/api/store/return-reasons/[id]/route");
        };
        returns: typeof import("@medusajs/medusa/api/store/returns/route");
        shippingOptions: typeof import("@mercurjs/core-plugin/api/store/shipping-options/route") & {
            $id: {
                calculate: typeof import("@medusajs/medusa/api/store/shipping-options/[id]/calculate/route");
            };
        };
        orderGroups: typeof import("@mercurjs/core-plugin/api/store/order-groups/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/store/order-groups/[id]/route");
        };
        sellers: typeof import("@mercurjs/core-plugin/api/store/sellers/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/store/sellers/[id]/route");
        };
        reviews: typeof import("../../src/reviews/api/store/reviews/route") & {
            $id: typeof import("../../src/reviews/api/store/reviews/[id]/route");
        };
        wishlist: typeof import("../../src/wishlist/api/store/wishlist/route") & {
            product: {
                $referenceId: typeof import("../../src/wishlist/api/store/wishlist/product/[reference_id]/route");
            };
        };
    };
    vendor: {
        campaigns: typeof import("@mercurjs/core-plugin/api/vendor/campaigns/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/campaigns/[id]/route") & {
                promotions: typeof import("@mercurjs/core-plugin/api/vendor/campaigns/[id]/promotions/route");
            };
        };
        collections: typeof import("@mercurjs/core-plugin/api/vendor/collections/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/collections/[id]/route") & {
                products: typeof import("@mercurjs/core-plugin/api/vendor/collections/[id]/products/route");
            };
        };
        currencies: typeof import("@mercurjs/core-plugin/api/vendor/currencies/route") & {
            $code: typeof import("@mercurjs/core-plugin/api/vendor/currencies/[code]/route");
        };
        customers: typeof import("@mercurjs/core-plugin/api/vendor/customers/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/customers/[id]/route");
        };
        fulfillmentSets: {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/fulfillment-sets/[id]/route") & {
                serviceZones: typeof import("@mercurjs/core-plugin/api/vendor/fulfillment-sets/[id]/service-zones/route") & {
                    $zoneId: typeof import("@mercurjs/core-plugin/api/vendor/fulfillment-sets/[id]/service-zones/[zone_id]/route");
                };
            };
        };
        inventoryItems: typeof import("@mercurjs/core-plugin/api/vendor/inventory-items/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/inventory-items/[id]/route") & {
                locationLevels: typeof import("@mercurjs/core-plugin/api/vendor/inventory-items/[id]/location-levels/route") & {
                    $locationId: typeof import("@mercurjs/core-plugin/api/vendor/inventory-items/[id]/location-levels/[location_id]/route");
                    batch: typeof import("@mercurjs/core-plugin/api/vendor/inventory-items/[id]/location-levels/batch/route");
                };
            };
        };
        orders: typeof import("@mercurjs/core-plugin/api/vendor/orders/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/orders/[id]/route") & {
                cancel: typeof import("@mercurjs/core-plugin/api/vendor/orders/[id]/cancel/route");
                changes: typeof import("@mercurjs/core-plugin/api/vendor/orders/[id]/changes/route");
                complete: typeof import("@mercurjs/core-plugin/api/vendor/orders/[id]/complete/route");
                fulfillments: typeof import("@mercurjs/core-plugin/api/vendor/orders/[id]/fulfillments/route") & {
                    $fulfillmentId: {
                        cancel: typeof import("@mercurjs/core-plugin/api/vendor/orders/[id]/fulfillments/[fulfillment_id]/cancel/route");
                        markAsDelivered: typeof import("@mercurjs/core-plugin/api/vendor/orders/[id]/fulfillments/[fulfillment_id]/mark-as-delivered/route");
                        shipments: typeof import("@mercurjs/core-plugin/api/vendor/orders/[id]/fulfillments/[fulfillment_id]/shipments/route");
                    };
                };
                preview: typeof import("@mercurjs/core-plugin/api/vendor/orders/[id]/preview/route");
            };
        };
        payments: typeof import("@mercurjs/core-plugin/api/vendor/payments/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/payments/[id]/route") & {
                capture: typeof import("@mercurjs/core-plugin/api/vendor/payments/[id]/capture/route");
                refund: typeof import("@mercurjs/core-plugin/api/vendor/payments/[id]/refund/route");
            };
            paymentProviders: typeof import("@mercurjs/core-plugin/api/vendor/payments/payment-providers/route");
        };
        payoutAccounts: typeof import("@mercurjs/core-plugin/api/vendor/payout-accounts/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/payout-accounts/[id]/route") & {
                onboarding: typeof import("@mercurjs/core-plugin/api/vendor/payout-accounts/[id]/onboarding/route");
            };
        };
        payouts: typeof import("@mercurjs/core-plugin/api/vendor/payouts/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/payouts/[id]/route");
        };
        priceLists: typeof import("@mercurjs/core-plugin/api/vendor/price-lists/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/price-lists/[id]/route") & {
                products: typeof import("@mercurjs/core-plugin/api/vendor/price-lists/[id]/products/route");
            };
        };
        pricePreferences: typeof import("@mercurjs/core-plugin/api/vendor/price-preferences/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/price-preferences/[id]/route");
        };
        productCategories: typeof import("@mercurjs/core-plugin/api/vendor/product-categories/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/product-categories/[id]/route") & {
                products: typeof import("@mercurjs/core-plugin/api/vendor/product-categories/[id]/products/route");
            };
        };
        productTags: typeof import("@mercurjs/core-plugin/api/vendor/product-tags/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/product-tags/[id]/route");
        };
        productTypes: typeof import("@mercurjs/core-plugin/api/vendor/product-types/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/product-types/[id]/route");
        };
        products: typeof import("@mercurjs/core-plugin/api/vendor/products/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/products/[id]/route") & {
                options: typeof import("@mercurjs/core-plugin/api/vendor/products/[id]/options/route") & {
                    $optionId: typeof import("@mercurjs/core-plugin/api/vendor/products/[id]/options/[option_id]/route");
                };
                variants: typeof import("@mercurjs/core-plugin/api/vendor/products/[id]/variants/route") & {
                    $variantId: typeof import("@mercurjs/core-plugin/api/vendor/products/[id]/variants/[variant_id]/route");
                };
            };
            import: typeof import("../../src/product-import-export/api/vendor/products/import/route");
            export: typeof import("../../src/product-import-export/api/vendor/products/export/route");
        };
        promotions: typeof import("@mercurjs/core-plugin/api/vendor/promotions/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/promotions/[id]/route") & {
                $ruleType: typeof import("@mercurjs/core-plugin/api/vendor/promotions/[id]/[rule_type]/route");
                buyRules: {
                    batch: typeof import("@mercurjs/core-plugin/api/vendor/promotions/[id]/buy-rules/batch/route");
                };
                rules: {
                    batch: typeof import("@mercurjs/core-plugin/api/vendor/promotions/[id]/rules/batch/route");
                };
                targetRules: {
                    batch: typeof import("@mercurjs/core-plugin/api/vendor/promotions/[id]/target-rules/batch/route");
                };
            };
            ruleAttributeOptions: {
                $ruleType: typeof import("@mercurjs/core-plugin/api/vendor/promotions/rule-attribute-options/[rule_type]/route");
            };
            ruleValueOptions: {
                $ruleType: {
                    $ruleAttributeId: typeof import("@mercurjs/core-plugin/api/vendor/promotions/rule-value-options/[rule_type]/[rule_attribute_id]/route");
                };
            };
        };
        refundReasons: typeof import("@mercurjs/core-plugin/api/vendor/refund-reasons/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/refund-reasons/[id]/route");
        };
        regions: typeof import("@mercurjs/core-plugin/api/vendor/regions/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/regions/[id]/route");
        };
        returnReasons: typeof import("@mercurjs/core-plugin/api/vendor/return-reasons/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/return-reasons/[id]/route");
        };
        returns: typeof import("@mercurjs/core-plugin/api/vendor/returns/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/route") & {
                cancel: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/cancel/route");
                dismissItems: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/dismiss-items/route") & {
                    $actionId: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/dismiss-items/[action_id]/route");
                };
                receive: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/receive/route") & {
                    confirm: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/receive/confirm/route");
                };
                receiveItems: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/receive-items/route") & {
                    $actionId: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/receive-items/[action_id]/route");
                };
                request: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/request/route");
                requestItems: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/request-items/route") & {
                    $actionId: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/request-items/[action_id]/route");
                };
                shippingMethod: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/shipping-method/route") & {
                    $actionId: typeof import("@mercurjs/core-plugin/api/vendor/returns/[id]/shipping-method/[action_id]/route");
                };
            };
        };
        salesChannels: typeof import("@mercurjs/core-plugin/api/vendor/sales-channels/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/sales-channels/[id]/route") & {
                products: typeof import("@mercurjs/core-plugin/api/vendor/sales-channels/[id]/products/route");
            };
        };
        sellers: typeof import("@mercurjs/core-plugin/api/vendor/sellers/route") & {
            me: typeof import("@mercurjs/core-plugin/api/vendor/sellers/me/route");
        };
        shippingOptionTypes: typeof import("@mercurjs/core-plugin/api/vendor/shipping-option-types/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/shipping-option-types/[id]/route");
        };
        shippingOptions: typeof import("@mercurjs/core-plugin/api/vendor/shipping-options/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/shipping-options/[id]/route") & {
                rules: {
                    batch: typeof import("@mercurjs/core-plugin/api/vendor/shipping-options/[id]/rules/batch/route");
                };
            };
        };
        shippingProfiles: typeof import("@mercurjs/core-plugin/api/vendor/shipping-profiles/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/shipping-profiles/[id]/route");
        };
        stockLocations: typeof import("@mercurjs/core-plugin/api/vendor/stock-locations/route") & {
            $id: typeof import("@mercurjs/core-plugin/api/vendor/stock-locations/[id]/route") & {
                fulfillmentProviders: typeof import("@mercurjs/core-plugin/api/vendor/stock-locations/[id]/fulfillment-providers/route");
                fulfillmentSets: typeof import("@mercurjs/core-plugin/api/vendor/stock-locations/[id]/fulfillment-sets/route");
                salesChannels: typeof import("@mercurjs/core-plugin/api/vendor/stock-locations/[id]/sales-channels/route");
            };
        };
        uploads: typeof import("@mercurjs/core-plugin/api/vendor/uploads/route");
        reviews: typeof import("../../src/reviews/api/vendor/reviews/route") & {
            $id: typeof import("../../src/reviews/api/vendor/reviews/[id]/route");
        };
    };
};
