// AUTO-GENERATED by `mercur build` preflight — do not edit.
// See SPEC-005 / SPEC-006 for the design notes.
//
// This file is the path-mapping shim resolved when downstream code writes
// `import { ProductDTO } from "@medusajs/types"`. `tsconfig.augment.json`
// (emitted alongside) maps `@medusajs/types` here and
// `@medusajs/types-original` to the real upstream package.

// 1. Forward every upstream type except the ones we replace below.
//    `export type *` is intentional — the upstream package is types-only,
//    so the shim must never claim a runtime export.
//    `ModuleImplementations` is explicitly excluded so the re-declaration
//    further down is the only one visible to consumers.
export type * from "@medusajs/types-original"

// 2. Replace ProductDTO with the Mercur shape. Same name; named re-export
//    wins over `export type *` per TS module rules.
export type { MercurProductDTO as ProductDTO } from "@mercurjs/types/product"

// 3. Replace ProductStatus. This is a *type* export only — upstream
//    `ProductStatus` in @medusajs/types is a string-literal union with no
//    runtime value, and path mapping is types-only. Code that needs a
//    runtime constant imports `ProductStatusValues` from
//    `@mercurjs/types/product` directly (that import is not path-mapped).
export type { ProductStatus } from "@mercurjs/types/product"

// 4. Re-declare ModuleImplementations explicitly. `declare module`
//    augmentation can't replace `product: IProductModuleService` with a
//    different service type — TS rejects interface merges with conflicting
//    property types. Replacement (not augmentation) is the only option.
//
//    Every upstream key is re-listed verbatim. The Mercur-only modules
//    (admin_ui, codegen, commission, custom_fields, offer, payout, seller,
//    subscription, vendor_ui) come in via Medusa's per-project
//    `generateContainerTypes` output, which augments the same interface
//    with module-specific entries.
import type {
  IApiKeyModuleService,
  IAuthModuleService,
  ICacheService,
  ICartModuleService,
  ICurrencyModuleService,
  ICustomerModuleService,
  IEventBusModuleService,
  IFileModuleService,
  IFulfillmentModuleService,
  IInventoryService,
  ILockingModule,
  INotificationModuleService,
  IOrderModuleService,
  IPaymentModuleService,
  IPricingModuleService,
  IPromotionModuleService,
  IRbacModuleService,
  IRegionModuleService,
  ISalesChannelModuleService,
  ISettingsModuleService,
  IStockLocationService,
  IStoreModuleService,
  ITaxModuleService,
  IUserModuleService,
  IWorkflowEngineService,
} from "@medusajs/types-original"
import type { MercurProductModuleService } from "@mercurjs/core/modules/product"

export interface ModuleImplementations {
  // Upstream module services (verbatim from @medusajs/framework, Medusa
  // 2.13.4). `product` is intentionally omitted from this block and
  // declared below with the Mercur override.
  api_key: IApiKeyModuleService
  auth: IAuthModuleService
  cache: ICacheService
  cart: ICartModuleService
  currency: ICurrencyModuleService
  customer: ICustomerModuleService
  event_bus: IEventBusModuleService
  file: IFileModuleService
  fulfillment: IFulfillmentModuleService
  inventory: IInventoryService
  locking: ILockingModule
  notification: INotificationModuleService
  order: IOrderModuleService
  payment: IPaymentModuleService
  pricing: IPricingModuleService
  promotion: IPromotionModuleService
  rbac: IRbacModuleService
  region: IRegionModuleService
  sales_channel: ISalesChannelModuleService
  settings: ISettingsModuleService
  stock_location: IStockLocationService
  store: IStoreModuleService
  tax: ITaxModuleService
  user: IUserModuleService
  workflows: IWorkflowEngineService

  // Mercur override.
  product: MercurProductModuleService
}
