export const RESET_PASSWORD_TOKEN_CREATED_EVENT = 'RESET_PASSWORD_TOKEN_CREATED_EVENT';
export const RESEND_RESET_PASSWORD_TOKEN_CREATED_EVENT = 'RESEND_RESET_PASSWORD_TOKEN_CREATED_EVENT';

export const ACCOUNT_ACTIVATED_EVENT = 'ACCOUNT_ACTIVATED_EVENT';
export const REQUESTED_RESEND_VERIFY_EMAIL_EVENT = 'REQUESTED_RESEND_VERIFY_EMAIL_EVENT';

export const SELLER_REGISTERED_EVENT = 'SELLER_REGISTERED_EVENT';
export const SELLER_CREATED_EVENT = 'SELLER_CREATED_EVENT';
export const SELLER_EMAIL_VERIFIED = 'SELLER_EMAIL_VERIFIED'

export const PASSWORD_HASH_CONFIG = { logN: 15, r: 8, p: 1 };