import { test as base, type APIRequestContext, request as pwRequest } from "@playwright/test"
import { readFileSync } from "node:fs"
import path from "node:path"

const API_URL = process.env.API_URL ?? "http://localhost:9000"
const STORAGE_STATE = path.resolve(process.cwd(), ".auth/vendor.json")
const CONTEXT_PATH = path.resolve(process.cwd(), ".auth/vendor-context.json")

type VendorContext = { sellerId: string }

/**
 * Adds an `apiRequest` fixture that points at the API origin (NOT the vendor
 * SPA), pre-authenticated with the session cookies generated by
 * `auth.setup.ts` and stamped with the `x-seller-id` header that every
 * `/vendor/*` route requires.
 *
 * The browser `page` is already authenticated via `storageState` in
 * playwright.config.ts — this fixture exists because the storage state lives
 * under the vendor origin, while seed calls go straight to the API origin.
 */
type AuthFixtures = {
  apiRequest: APIRequestContext
  sellerId: string
}

export const test = base.extend<AuthFixtures>({
  // oxlint-disable-next-line no-empty-pattern
  sellerId: async ({}, use) => {
    const ctx = JSON.parse(readFileSync(CONTEXT_PATH, "utf-8")) as VendorContext
    await use(ctx.sellerId)
  },

  apiRequest: async ({ sellerId }, use) => {
    const ctx = await pwRequest.newContext({
      baseURL: API_URL,
      storageState: STORAGE_STATE,
      extraHTTPHeaders: {
        "x-seller-id": sellerId,
      },
    })

    await use(ctx)
    await ctx.dispose()
  },
})

export { expect } from "@playwright/test"
