export const OFFERS_PAGE_SIZE = 10
export const STORE_OFFERS_SECTION_PAGE_SIZE = 10
export const OFFER_IDS_KEY = "offer_ids"

export const OFFER_DETAIL_FIELDS = [
  "id",
  "sku",
  "ean",
  "upc",
  "variant_id",
  "seller_id",
  "shipping_profile_id",
  "price_set_id",
  "metadata",
  "created_at",
  "updated_at",
  "deleted_at",
  "product_variant.id",
  "product_variant.title",
  "product_variant.sku",
  "product_variant.product_id",
  "product_variant.product.id",
  "product_variant.product.title",
  "product_variant.product.thumbnail",
  "shipping_profile.id",
  "shipping_profile.name",
  "shipping_profile.type",
  "price_set.id",
  "price_set.prices.id",
  "price_set.prices.amount",
  "price_set.prices.currency_code",
  "price_set.prices.min_quantity",
  "price_set.prices.max_quantity",
  "price_set.prices.rules_count",
  "price_set.prices.price_rules.attribute",
  "price_set.prices.price_rules.value",
  "inventory_item_link.id",
  "inventory_item_link.required_quantity",
  "inventory_item_link.inventory_item_id",
  "inventory_item_link.inventory_item.id",
  "inventory_item_link.inventory_item.sku",
  "inventory_item_link.inventory_item.title",
  "inventory_item_link.inventory_item.location_levels.id",
  "inventory_item_link.inventory_item.location_levels.location_id",
  "inventory_item_link.inventory_item.location_levels.stocked_quantity",
  "inventory_item_link.inventory_item.location_levels.reserved_quantity",
  "inventory_item_link.inventory_item.location_levels.incoming_quantity",
  "inventory_item_link.inventory_item.location_levels.available_quantity",
  "seller.id",
  "seller.name",
  "seller.handle",
  "seller.email",
].join(",")

export const OFFER_LIST_FIELDS = [
  "id",
  "sku",
  "variant_id",
  "seller_id",
  "created_at",
  "updated_at",
  "deleted_at",
  "product_variant.id",
  "product_variant.title",
  "product_variant.product_id",
  "product_variant.product.id",
  "product_variant.product.title",
  "product_variant.product.status",
  "product_variant.product.thumbnail",
  "product_variant.product.categories.id",
  "product_variant.product.categories.name",
  "shipping_profile.id",
  "shipping_profile.name",
  "seller.id",
  "seller.name",
  "seller.handle",
].join(",")
