export const adminProductVariantFields = [
  "id",
  "title",
  "sku",
  "barcode",
  "ean",
  "upc",
  "allow_backorder",
  "manage_inventory",
  "hs_code",
  "origin_country",
  "mid_code",
  "material",
  "weight",
  "length",
  "height",
  "width",
  "metadata",
  "variant_rank",
  "product_id",
  "created_at",
  "updated_at",
  "*prices",
  "prices.currency_code",
  "prices.amount",
  "prices.min_quantity",
  "prices.max_quantity",
  "*inventory_items",
  "inventory_items.required_quantity",
  "inventory_items.inventory_item_id",
  "*options",
  "options.value",
  "options.option_id",
  "*product",
  "product.title",
  "product.handle",
  "product.status",
];

export const adminProductVariantQueryConfig = {
  list: {
    defaults: adminProductVariantFields,
    isList: true,
  },
};
