export enum MercurModules {
    SELLER = "seller",
    COMMISSION = "commission",
    PAYOUT = "payout",
    OFFER = "offer",
    MEDIA = "media",
    PRODUCT_ATTRIBUTE = "product_attribute",
    PRODUCT_EDIT = "product_edit",
    CUSTOM_FIELDS = "custom_fields",
    VENDOR_UI = "vendor_ui",
    ADMIN_UI = "admin_ui",
    CODEGEN = "codegen",
    PROMOTION_COST = "promotion_cost",
    REVIEW = "review",
}
