export enum ResendNotificationTemplates {
  BUYER_ACCOUNT_CREATED = 'buyerAccountCreatedEmailTemplate',
  BUYER_NEW_ORDER = 'buyerNewOrderEmailTemplate',
  BUYER_CANCELED_ORDER = 'buyerCancelOrderEmailTemplate',
  BUYER_ORDER_SHIPPED = 'buyerOrderShippedEmailTemplate',
  SELLER_ACCOUNT_UPDATES_SUBMISSION = 'sellerAccountSubmissionEmailTemplate',
  SELLER_ACCOUNT_UPDATES_APPROVAL = 'sellerAccountApprovedEmailTemplate',
  SELLER_ACCOUNT_UPDATES_REJECTION = 'sellerAccountRejectedEmailTemplate',
  SELLER_NEW_ORDER = 'sellerNewOrderEmailTemplate',
  SELLER_CANCELED_ORDER = 'sellerCanceledOrderEmailTemplate',
  SELLER_ORDER_SHIPPED = 'sellerOrderShippingEmailTemplate',
  SELLER_TEAM_MEMBER_INVITATION = 'sellerTeamInviteEmailTemplate',
  SELLER_VERIFY_EMAIL_TEMPLATE = 'sellerVerifyEmailTemplate',
  FORGOT_PASSWORD = 'forgotPasswordEmailTemplate',
  NEW_SELLER_INVITATION = 'newSellerInvitation',
  SELLER_PRODUCT_APPROVED = 'sellerProductApprovedEmailTemplate',
  SELLER_PRODUCT_REJECTED = 'sellerProductRejectedEmailTemplate',
  ADMIN_REQUEST_CREATED = 'adminRequestCreatedEmailTemplate',
  ADMIN_SELLER_REQUEST_CREATED = 'adminSellerRequestCreatedEmailTemplate'
}
