/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUpdateProductVariant } from './adminUpdateProductVariant';
import type { AdminPostProductsIdVariantsVariantIdBodyAllOf } from './adminPostProductsIdVariantsVariantIdBodyAllOf';

/**
 * The properties to update in the variant.
 */
export type AdminPostProductsIdVariantsVariantIdBody = AdminUpdateProductVariant & AdminPostProductsIdVariantsVariantIdBodyAllOf;
