/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminWorkflowExecution } from './adminWorkflowExecution';

/**
 * The paginated list of workflow executions.
 */
export type AdminGetWorkflowsExecutions200AllOfTwo = {
  /** The workflows execution's workflow executions. */
  workflow_executions: AdminWorkflowExecution[];
};
