/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostPriceListsIdPricesBatchBodyCreateItemRules } from './adminPostPriceListsIdPricesBatchBodyCreateItemRules';

/**
 * A price's details.
 */
export type AdminPostPriceListsIdPricesBatchBodyCreateItem = {
  /** The price's amount. */
  amount: number;
  /** The price's currency code. */
  currency_code: string;
  /** The maximum quantity that must be available of the associated variant in the cart for this price list to apply. */
  max_quantity?: number;
  /** The minimum quantity that must be available of the associated variant in the cart for this price to apply. */
  min_quantity?: number;
  /** Key-value pair rules to apply on the price. */
  rules?: AdminPostPriceListsIdPricesBatchBodyCreateItemRules;
  /** The ID of the variant this price is for. */
  variant_id: string;
};
