/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminProductVariantInventoryLink } from './adminProductVariantInventoryLink';
import type { AdminProductVariant } from './adminProductVariant';

/**
 * The details of the deleted associated between a product variant and an inventory item.
 */
export interface AdminProductVariantInventoryLinkDeleteResponse {
  /** Whether the association was deleted. */
  deleted: boolean;
  id: AdminProductVariantInventoryLink;
  /** The name of the deleted object. */
  object: string;
  parent: AdminProductVariant;
}
