/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The order's metadata. Can hold custom key-value pairs.
 */
export type AdminPostOrdersIdFulfillmentsBodyAllOfMetadata = { [key: string]: unknown };
