/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The price list's type.
 */
export type AdminUpdatePriceListType = typeof AdminUpdatePriceListType[keyof typeof AdminUpdatePriceListType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUpdatePriceListType = {
  sale: 'sale',
  override: 'override',
} as const;
