/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the deleted buy rules.
 */
export type AdminPostPromotionsIdRulesBatch200Deleted = {
  /** Whether the rules were deleted. */
  deleted: boolean;
  /** The IDs of the deleted rules. */
  ids: string[];
  /** The name of the object that was deleted. */
  object: string;
};
