/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetReturnReasonsDeletedAtNotOneOf } from './adminGetReturnReasonsDeletedAtNotOneOf';

export type AdminGetReturnReasonsDeletedAtNot = string | AdminGetReturnReasonsDeletedAtNotOneOf | string[];
