/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The label's labels.
 */
export type AdminPostOrdersIdFulfillmentsFulfillmentIdShipmentsBodyAllOfLabelsItem = {
  /** The label's url. */
  label_url: string;
  /** The label's tracking number. */
  tracking_number: string;
  /** The label's tracking url. */
  tracking_url: string;
};
