/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The promotion's type.
 */
export type AdminPostPromotionsIdBodyAllOfType = typeof AdminPostPromotionsIdBodyAllOfType[keyof typeof AdminPostPromotionsIdBodyAllOfType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminPostPromotionsIdBodyAllOfType = {
  standard: 'standard',
  buyget: 'buyget',
} as const;
