/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStore } from './adminStore';

/**
 * The paginated list of stores.
 */
export interface AdminStoreListResponse {
  /** The total number of items. */
  count: number;
  /** The maximum number of items returned. */
  limit: number;
  /** The number of items skipped before retrieving the returned items. */
  offset: number;
  /** The list of stores. */
  stores: AdminStore[];
}
