/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminInventoryItem } from './adminInventoryItem';
import type { AdminReservationMetadata } from './adminReservationMetadata';

/**
 * The reservation's details.
 */
export interface AdminReservation {
  /** The date this reservation was created. */
  created_at?: string;
  /** The ID of the user that created this reservation. */
  created_by?: string;
  /** The date this reservation was deleted. */
  deleted_at?: string;
  /** The reservation's description. */
  description: string;
  /** An ID in an external system */
  external_id: string;
  /** The reservation's ID. */
  id: string;
  inventory_item?: AdminInventoryItem;
  /** The ID of the inventory item this reservation is associated with. */
  inventory_item_id: string;
  /** The ID of the line item this reservation is for. */
  line_item_id: string;
  /** The ID of the location the quantity is reserved from. */
  location_id: string;
  /** The reservation's metadata, can hold custom key-value pairs. */
  metadata?: AdminReservationMetadata;
  /** The reservation's quantity. */
  quantity: number;
  /** The date this reservation was updated. */
  updated_at?: string;
}
