/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseRuleOperatorOptions } from './baseRuleOperatorOptions';

/**
 * The details of a potential rule attribute.
 */
export interface AdminRuleAttributeOption {
  /** The rule attribute's ID, which is a rule's `attribute` it refers to. */
  id: string;
  /** The rule attribute option's label. */
  label: string;
  /** The attribute's operators. */
  operators: BaseRuleOperatorOptions[];
  /** The rule attribute's value. */
  value: string;
}
