/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostProductTagsIdBodyMetadata } from './adminPostProductTagsIdBodyMetadata';

/**
 * The properties to update in the product tag.
 */
export type AdminPostProductTagsIdBody = {
  /** The product tag's metadata. Can hold custom key-value pairs. */
  metadata?: AdminPostProductTagsIdBodyMetadata;
  /** The product tag's value. */
  value?: string;
};
