/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The price list's status.
 */
export type AdminUpdatePriceListStatus = typeof AdminUpdatePriceListStatus[keyof typeof AdminUpdatePriceListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUpdatePriceListStatus = {
  active: 'active',
  draft: 'draft',
} as const;
