/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPromotion } from './adminPromotion';

/**
 * The promotion's details.
 */
export interface AdminPromotionResponse {
  promotion: AdminPromotion;
}
