/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A price list's status.
 */
export type AdminGetPriceListsStatusItem = typeof AdminGetPriceListsStatusItem[keyof typeof AdminGetPriceListsStatusItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminGetPriceListsStatusItem = {
  active: 'active',
  draft: 'draft',
} as const;
