/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminProductOptionValueMetadata } from './adminProductOptionValueMetadata';
import type { AdminProductOption } from './adminProductOption';

/**
 * The product option value's details.
 */
export interface AdminProductOptionValue {
  /** The date the value was created. */
  created_at?: string;
  /** The date the value was deleted. */
  deleted_at?: string;
  /** The value's ID. */
  id: string;
  /** The value's metadata, can hold custom key-value pairs. */
  metadata?: AdminProductOptionValueMetadata;
  option?: AdminProductOption;
  /** The ID of the option this value belongs to. */
  option_id?: string;
  /** The date the value was updated. */
  updated_at?: string;
  /** The value. */
  value: string;
}
