/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPriceList } from './adminPriceList';

/**
 * The price list's details.
 */
export interface AdminPriceListResponse {
  price_list: AdminPriceList;
}
