/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostOrderEditsAddItemsReqSchemaItemsItem } from './adminPostOrderEditsAddItemsReqSchemaItemsItem';

/**
 * The details of items to be edited.
 */
export interface AdminPostOrderEditsAddItemsReqSchema {
  /** The details of items to be edited. */
  items?: AdminPostOrderEditsAddItemsReqSchemaItemsItem[];
}
