/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of a fulfillmet's shipment label.
 */
export interface AdminFulfillmentLabel {
  /** The date the label was created. */
  created_at: string;
  /** The date the label was deleted. */
  deleted_at: string;
  /** The ID of the fulfillment the label is associated with. */
  fulfillment_id: string;
  /** The label's ID. */
  id: string;
  /** The label's URL. */
  label_url: string;
  /** The label's tracking number. */
  tracking_number: string;
  /** The label's tracking URL. */
  tracking_url: string;
  /** The date the label was updated. */
  updated_at: string;
}
