/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetPromotions200AllOf } from './adminGetPromotions200AllOf';
import type { AdminGetPromotions200AllOfTwo } from './adminGetPromotions200AllOfTwo';

export type AdminGetPromotions200 = AdminGetPromotions200AllOf & AdminGetPromotions200AllOfTwo;
