/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostOrderExchangesReqSchemaMetadata } from './adminPostOrderExchangesReqSchemaMetadata';

/**
 * The exchange's details.
 */
export interface AdminPostOrderExchangesReqSchema {
  /** The exchange's description. */
  description?: string;
  /** A note viewed only by admin users. */
  internal_note?: string;
  /** The exchange's metadata, can hold custom key-value pairs. */
  metadata?: AdminPostOrderExchangesReqSchemaMetadata;
  /** The ID of the order this exchange is created for. */
  order_id: string;
}
