/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeleteTaxRatesIdRulesRuleId200AllOf } from './adminDeleteTaxRatesIdRulesRuleId200AllOf';
import type { AdminDeleteTaxRatesIdRulesRuleId200AllOfTwo } from './adminDeleteTaxRatesIdRulesRuleId200AllOfTwo';

/**
 * The deletion's details.
 */
export type AdminDeleteTaxRatesIdRulesRuleId200 = AdminDeleteTaxRatesIdRulesRuleId200AllOf & AdminDeleteTaxRatesIdRulesRuleId200AllOfTwo;
