/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The deletion's details.
 */
export type AdminDeleteCampaignsId200 = {
  /** Whether the campaign was deleted. */
  deleted: boolean;
  /** The campaign's ID. */
  id: string;
  /** The name of the object that was deleted. */
  object: string;
};
