/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the tax region deletion.
 */
export interface AdminTaxRegionDeleteResponse {
  /** Whether the tax region was deleted. */
  deleted: boolean;
  /** The tax region's ID. */
  id: string;
  /** The name of the deleted object. */
  object: string;
}
