/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetDraftOrdersStatusOneOfNotOneOf } from './adminGetDraftOrdersStatusOneOfNotOneOf';
import type { AdminGetDraftOrdersStatusOneOfNotOneOfSevenItem } from './adminGetDraftOrdersStatusOneOfNotOneOfSevenItem';

export type AdminGetDraftOrdersStatusOneOfNot = string | AdminGetDraftOrdersStatusOneOfNotOneOf | string[] | AdminGetDraftOrdersStatusOneOfNotOneOfSevenItem[];
