/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The api key's type. `secret` is used for a user's API key, whereas `publishable` is used for Publishable API keys.
 */
export type AdminApiKeyType = typeof AdminApiKeyType[keyof typeof AdminApiKeyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminApiKeyType = {
  secret: 'secret',
  publishable: 'publishable',
} as const;
