/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The price list's status.
 */
export type AdminCreatePriceListStatus = typeof AdminCreatePriceListStatus[keyof typeof AdminCreatePriceListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminCreatePriceListStatus = {
  active: 'active',
  draft: 'draft',
} as const;
