/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetShippingOptions200AllOfTwoShippingOptionsItem } from './adminGetShippingOptions200AllOfTwoShippingOptionsItem';

/**
 * The paginated list of shipping options.
 */
export type AdminGetShippingOptions200AllOfTwo = {
  /** The list of shipping options. */
  shipping_options: AdminGetShippingOptions200AllOfTwoShippingOptionsItem[];
};
