/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The country's details.
 */
export interface AdminRegionCountry {
  /** The country's display name. */
  display_name?: string;
  /** The country's ID. */
  id: string;
  /** The country's iso 2. */
  iso_2?: string;
  /** The country's iso 3. */
  iso_3?: string;
  /** The country's name. */
  name?: string;
  /** The country's num code. */
  num_code?: string;
}
