/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUpdateReturnReasonMetadata } from './adminUpdateReturnReasonMetadata';

/**
 * The details to update in a return reason.
 */
export interface AdminUpdateReturnReason {
  /** The return reason's description. */
  description?: string;
  /** The return reason's label. */
  label: string;
  /** The return reason's metadata, can hold custom key-value pairs. */
  metadata?: AdminUpdateReturnReasonMetadata;
  /** The return reason's value. */
  value: string;
}
