/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostOrdersIdFulfillmentsBodyAllOfItemsItem } from './adminPostOrdersIdFulfillmentsBodyAllOfItemsItem';
import type { AdminPostOrdersIdFulfillmentsBodyAllOfMetadata } from './adminPostOrdersIdFulfillmentsBodyAllOfMetadata';

/**
 * The fulfillment's details.
 */
export type AdminPostOrdersIdFulfillmentsBodyAllOf = {
  /** The items to fulfill. */
  items: AdminPostOrdersIdFulfillmentsBodyAllOfItemsItem[];
  /** The ID of the location to fulfill the items from. If not provided, the location associated with the shipping option of the order's shipping method is used. */
  location_id: string;
  /** The order's metadata. Can hold custom key-value pairs. */
  metadata: AdminPostOrdersIdFulfillmentsBodyAllOfMetadata;
  /** Whether to send the customer a notification about the created fulfillment. */
  no_notification?: boolean;
};
