/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminShippingOptionPriceRuleOperator } from './adminShippingOptionPriceRuleOperator';
import type { AdminShippingOptionPriceRuleValue } from './adminShippingOptionPriceRuleValue';

/**
 * The details of a shipping option price's rule.
 */
export interface AdminShippingOptionPriceRule {
  /** The price rule's attribute. */
  attribute: string;
  /** The date the price rule was created. */
  created_at: string;
  /** The date the price rule was deleted. */
  deleted_at: string;
  /** The price rule's ID. */
  id: string;
  /** The price rule's operator. */
  operator: AdminShippingOptionPriceRuleOperator;
  /** The ID of the price this rule applies to. */
  price_id: string;
  /** The price rule's priority. */
  priority: number;
  /** The date the price rule was updated. */
  updated_at: string;
  /** The price rule's value. */
  value: AdminShippingOptionPriceRuleValue;
}
