/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostPromotionsBodyAllOfApplicationMethodAllocation } from './adminPostPromotionsBodyAllOfApplicationMethodAllocation';
import type { AdminPostPromotionsBodyAllOfApplicationMethodBuyRulesItem } from './adminPostPromotionsBodyAllOfApplicationMethodBuyRulesItem';
import type { AdminPostPromotionsBodyAllOfApplicationMethodTargetRulesItem } from './adminPostPromotionsBodyAllOfApplicationMethodTargetRulesItem';
import type { AdminPostPromotionsBodyAllOfApplicationMethodTargetType } from './adminPostPromotionsBodyAllOfApplicationMethodTargetType';
import type { AdminPostPromotionsBodyAllOfApplicationMethodType } from './adminPostPromotionsBodyAllOfApplicationMethodType';

/**
 * The promotion's application method.
 */
export type AdminPostPromotionsBodyAllOfApplicationMethod = {
  /** The allocation value that indicates whether the associated promotion is applied on each item in a cart or split between the items in the cart. */
  allocation?: AdminPostPromotionsBodyAllOfApplicationMethodAllocation;
  /** The quantity that results from matching the `buyget` promotion's condition. For example, if the promotion is a "Buy 2 shirts get 1 free", the value f this attribute is `1`. */
  apply_to_quantity: number;
  /** The application method's buy rules. */
  buy_rules?: AdminPostPromotionsBodyAllOfApplicationMethodBuyRulesItem[];
  /** The minimum quantity required for a `buyget` promotion to be applied. For example, if the promotion is a "Buy 2 shirts get 1 free", the value of this attribute is `2`. */
  buy_rules_min_quantity: number;
  /** The application method's currency code. */
  currency_code: string;
  /** The application method's description. */
  description: string;
  /** The max quantity allowed in the cart for the associated promotion to be applied. */
  max_quantity: number;
  /** The application method's target rules. */
  target_rules?: AdminPostPromotionsBodyAllOfApplicationMethodTargetRulesItem[];
  /** The target type of the application method indicating whether the associated promotion is applied to the cart's items, shipping methods, or the whole order. */
  target_type: AdminPostPromotionsBodyAllOfApplicationMethodTargetType;
  /** The type of the application method indicating how the associated promotion is applied. */
  type: AdminPostPromotionsBodyAllOfApplicationMethodType;
  /** The discounted amount applied by the associated promotion based on the `type`. */
  value: number;
};
