/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminWorkflowExecutionExecutionStepsCompensate } from './adminWorkflowExecutionExecutionStepsCompensate';
import type { AdminWorkflowExecutionExecutionStepsDefinition } from './adminWorkflowExecutionExecutionStepsDefinition';
import type { AdminWorkflowExecutionExecutionStepsInvoke } from './adminWorkflowExecutionExecutionStepsInvoke';

/**
 * The execution's steps. Each object key is a step ID, and the value is the object whose properties are shown below.
 */
export type AdminWorkflowExecutionExecutionSteps = {[key: string]: {
  /** The state of the step's compensation function. */
  compensate?: AdminWorkflowExecutionExecutionStepsCompensate;
  /** The step's definition details. */
  definition?: AdminWorkflowExecutionExecutionStepsDefinition;
  /** The step's depth in the workflow's execution. */
  depth?: number;
  /** The step's ID. */
  id?: string;
  /** The state of the step's invokation function. */
  invoke?: AdminWorkflowExecutionExecutionStepsInvoke;
  /** The timestamp the step started executing. */
  startedAt?: number;
}};
