/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminWorkflowExecutionExecutionStepsInvokeState } from './adminWorkflowExecutionExecutionStepsInvokeState';
import type { AdminWorkflowExecutionExecutionStepsInvokeStatus } from './adminWorkflowExecutionExecutionStepsInvokeStatus';

/**
 * The state of the step's invokation function.
 */
export type AdminWorkflowExecutionExecutionStepsInvoke = {
  /** The invokation step's state. */
  state: AdminWorkflowExecutionExecutionStepsInvokeState;
  /** The invokation step's state. */
  status: AdminWorkflowExecutionExecutionStepsInvokeStatus;
};
