/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminExchange } from './adminExchange';
import type { Order } from './order';

/**
 * The exchange's details.
 */
export interface AdminExchangeOrderResponse {
  exchange: AdminExchange;
  order: Order;
}
