/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The price's details.
 */
export type AdminCreateShippingOptionPricesItemOneOfTwo = {
  /** The price's amount. */
  amount: number;
  /** The ID of the region this price is used in. */
  region_id: string;
};
