/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderPreview } from './adminOrderPreview';

/**
 * The preview of an order.
 */
export interface AdminOrderPreviewResponse {
  order: AdminOrderPreview;
}
