/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The name of the table this action applies on.
 */
export type AdminOrderChangeActionReference = typeof AdminOrderChangeActionReference[keyof typeof AdminOrderChangeActionReference];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminOrderChangeActionReference = {
  claim: 'claim',
  exchange: 'exchange',
  return: 'return',
  order_shipping_method: 'order_shipping_method',
} as const;
