/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The paginated list of payments.
 */
export type AdminGetPayments200AllOf = {
  /** The total number of payments. */
  count: number;
  /** The maximum number of returned items. */
  limit: number;
  /** The number of items skipped before the returned items. */
  offset: number;
};
