/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminInventoryLevelInventoryItem } from './adminInventoryLevelInventoryItem';
import type { AdminInventoryLevelMetadata } from './adminInventoryLevelMetadata';

/**
 * The location level's location levels.
 */
export interface AdminInventoryLevel {
  /** The location level's available quantity. */
  available_quantity: number;
  /** The location level's created at. */
  created_at: string;
  /** The location level's deleted at. */
  deleted_at: string;
  /** The location level's ID. */
  id: string;
  /** The location level's incoming quantity. */
  incoming_quantity: number;
  inventory_item?: AdminInventoryLevelInventoryItem;
  /** The location level's inventory item id. */
  inventory_item_id: string;
  /** The location level's location id. */
  location_id: string;
  /** The location level's metadata. */
  metadata: AdminInventoryLevelMetadata;
  /** The location level's reserved quantity. */
  reserved_quantity: number;
  /** The location level's stocked quantity. */
  stocked_quantity: number;
  /** The location level's updated at. */
  updated_at: string;
}
