/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminFile } from './adminFile';

/**
 * The list of uploaded files.
 */
export interface AdminFileListResponse {
  /** The list of uploaded files. */
  files: AdminFile[];
}
