/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the deleted prices.
 */
export type AdminPriceListBatchResponseDeleted = {
  /** Whether the prices were deleted. */
  deleted: boolean;
  /** The IDs of the deleted prices. */
  ids: string[];
  /** The name of the deleted object. */
  object: string;
};
