/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderPreviewItemsItemAllOfFourActionsItem } from './adminOrderPreviewItemsItemAllOfFourActionsItem';

/**
 * An order's item.
 */
export type AdminOrderPreviewItemsItemAllOfFour = {
  /** The actions applied on an item. */
  actions?: AdminOrderPreviewItemsItemAllOfFourActionsItem[];
};
