/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCollection } from './adminCollection';

/**
 * The collection's details.
 */
export interface AdminCollectionResponse {
  collection: AdminCollection;
}
