/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUpdateProduct } from './adminUpdateProduct';
import type { AdminPostProductsIdBodyAllOf } from './adminPostProductsIdBodyAllOf';

/**
 * The properties to update in a product.
 */
export type AdminPostProductsIdBody = AdminUpdateProduct & AdminPostProductsIdBodyAllOf;
