/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUpsertStockLocationAddress } from './adminUpsertStockLocationAddress';
import type { AdminCreateStockLocationMetadata } from './adminCreateStockLocationMetadata';

/**
 * The stock location's details.
 */
export interface AdminCreateStockLocation {
  address?: AdminUpsertStockLocationAddress;
  /** The ID of the stock location's address. */
  address_id?: string;
  /** The stock location's metadata, used to store custom key-value pairs. */
  metadata?: AdminCreateStockLocationMetadata;
  /** The stock location's name. */
  name: string;
}
