/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostInventoryItemsIdLocationLevelsBatch200InventoryItem } from './adminPostInventoryItemsIdLocationLevelsBatch200InventoryItem';

/**
 * The inventory item's details.
 */
export type AdminPostInventoryItemsIdLocationLevelsBatch200 = {
  /** The inventory item's details. */
  inventory_item: AdminPostInventoryItemsIdLocationLevelsBatch200InventoryItem;
};
