/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { CampaignResponse } from './campaignResponse';

/**
 * The list of campaigns
 */
export type AdminGetCampaigns200AllOfTwo = {
  /** The list of campaigns. */
  campaigns: CampaignResponse[];
};
