/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The price list's rules.
 */
export type AdminUpdatePriceListRules = { [key: string]: unknown };
