/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStockLocation } from './adminStockLocation';
import type { AdminServiceZone } from './adminServiceZone';

/**
 * The service zone's fulfillment set.
 */
export interface AdminFulfillmentSet {
  /** The fulfillment set's created at. */
  created_at: string;
  /** The fulfillment set's deleted at. */
  deleted_at: string;
  /** The fulfillment set's ID. */
  id: string;
  location: AdminStockLocation;
  /** The fulfillment set's name. */
  name: string;
  /** The fulfillment set's service zones. */
  service_zones: AdminServiceZone[];
  /** The fulfillment set's type. */
  type: string;
  /** The fulfillment set's updated at. */
  updated_at: string;
}
