/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The products removal details.
 */
export interface AdminLinkPriceListProducts {
  /** The products to remove from the price list. */
  remove?: string[];
}
