/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetReservations200AllOf } from './adminGetReservations200AllOf';
import type { AdminGetReservations200AllOfTwo } from './adminGetReservations200AllOfTwo';

export type AdminGetReservations200 = AdminGetReservations200AllOf & AdminGetReservations200AllOfTwo;
