/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminShippingProfile } from './adminShippingProfile';

/**
 * The paginated list of shipping profiles.
 */
export type AdminGetShippingProfiles200AllOfTwo = {
  /** The list of shipping profiles. */
  shipping_profiles: AdminShippingProfile[];
};
