/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminProductType } from './adminProductType';

/**
 * The product type's details.
 */
export interface AdminProductTypeResponse {
  product_type: AdminProductType;
}
