/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetCustomersDeletedAtNotOneOfNotOneOf } from './adminGetCustomersDeletedAtNotOneOfNotOneOf';

export type AdminGetCustomersDeletedAtNotOneOfNot = string | AdminGetCustomersDeletedAtNotOneOfNotOneOf | string[];
