/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The price rule's operator.
 */
export type AdminShippingOptionPriceRuleOperator = typeof AdminShippingOptionPriceRuleOperator[keyof typeof AdminShippingOptionPriceRuleOperator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminShippingOptionPriceRuleOperator = {
  gt: 'gt',
  lt: 'lt',
  eq: 'eq',
  ne: 'ne',
  in: 'in',
  lte: 'lte',
  gte: 'gte',
  nin: 'nin',
} as const;
