/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The shipping method's data, useful for fulfillment provider handling its fulfillment.
 */
export type AdminOrderShippingMethodData = { [key: string]: unknown };
