/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetDraftOrdersStatusOneOfNotOneOfSevenItemOneOf } from './adminGetDraftOrdersStatusOneOfNotOneOfSevenItemOneOf';

export type AdminGetDraftOrdersStatusOneOfNotOneOfSevenItem = string | AdminGetDraftOrdersStatusOneOfNotOneOfSevenItemOneOf;
