/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the user to be created.
 */
export type AdminPostInvitesAcceptBody = {
  /** The user's email. */
  email?: string;
  /** The user's first name. */
  first_name?: string;
  /** The user's last name. */
  last_name?: string;
};
