/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostShippingOptionsIdBodyRulesItemOneOfOperator } from './adminPostShippingOptionsIdBodyRulesItemOneOfOperator';
import type { AdminPostShippingOptionsIdBodyRulesItemOneOfValue } from './adminPostShippingOptionsIdBodyRulesItemOneOfValue';

/**
 * The details of a new shipping option rule.
 */
export type AdminPostShippingOptionsIdBodyRulesItemOneOf = {
  /** The name of a property or table that the rule applies to. */
  attribute: string;
  /** The operator used to check whether a rule applies. */
  operator: AdminPostShippingOptionsIdBodyRulesItemOneOfOperator;
  value: AdminPostShippingOptionsIdBodyRulesItemOneOfValue;
};
