/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Filter by values not matching the conditions in this parameter.
 */
export type AdminGetReturnsCreatedAtNotOneOfNotOneOf = { [key: string]: unknown };
