/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkflowExecutionContext } from './workflowExecutionContext';
import type { AdminWorkflowExecutionExecution } from './adminWorkflowExecutionExecution';
import type { AdminWorkflowExecutionState } from './adminWorkflowExecutionState';

/**
 * The workflows execution's details.
 */
export interface AdminWorkflowExecution {
  context: WorkflowExecutionContext;
  /** The date the workflow execution was created. */
  created_at: string;
  /** The date the workflow execution was deleted. */
  deleted_at?: string;
  execution: AdminWorkflowExecutionExecution;
  /** The workflow execution's ID. */
  id: string;
  /** The workflow execution's state. */
  state: AdminWorkflowExecutionState;
  /** The workflow execution's transaction ID. */
  transaction_id: string;
  /** The date the workflow execution was updated. */
  updated_at: string;
  /** The ID of the workflow. */
  workflow_id: string;
}
