/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminTaxRate } from './adminTaxRate';

/**
 * The tax rate's details.
 */
export interface AdminTaxRateResponse {
  tax_rate: AdminTaxRate;
}
