/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The operator used to check whether a rule applies.
 */
export type AdminPostShippingOptionsIdBodyRulesItemOneOfOperator = typeof AdminPostShippingOptionsIdBodyRulesItemOneOfOperator[keyof typeof AdminPostShippingOptionsIdBodyRulesItemOneOfOperator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminPostShippingOptionsIdBodyRulesItemOneOfOperator = {
  in: 'in',
  eq: 'eq',
  ne: 'ne',
  gt: 'gt',
  gte: 'gte',
  lt: 'lt',
  lte: 'lte',
  nin: 'nin',
} as const;
