/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the stock location address to create.
 */
export interface AdminUpsertStockLocationAddress {
  /** The address's first line. */
  address_1: string;
  /** The address's second line. */
  address_2?: string;
  /** The address's city. */
  city?: string;
  /** The address's company. */
  company?: string;
  /** The address's country code. */
  country_code: string;
  /** The address's phone. */
  phone?: string;
  /** The address's postal code. */
  postal_code?: string;
  /** The address's province. */
  province?: string;
}
