/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The data relevant for the fulfillment provider to process this shipment.
 */
export type AdminOrderPreviewShippingMethodsItemAllOfData = { [key: string]: unknown };
