/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of canceling an exchange.
 */
export interface AdminPostCancelExchangeReqSchema {
  /** Whether to send a notification to the customer about the exchange's cancelation. */
  no_notification?: boolean;
}
