/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostClaimsAddItemsReqSchemaItemsItem } from './adminPostClaimsAddItemsReqSchemaItemsItem';

/**
 * The details of the outbound items to add to the claim.
 */
export interface AdminPostClaimsAddItemsReqSchema {
  /** The outbound item's details. */
  items?: AdminPostClaimsAddItemsReqSchemaItemsItem[];
}
