/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The compensation function's state.
 */
export type AdminWorkflowExecutionExecutionStepsCompensateState = typeof AdminWorkflowExecutionExecutionStepsCompensateState[keyof typeof AdminWorkflowExecutionExecutionStepsCompensateState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminWorkflowExecutionExecutionStepsCompensateState = {
  not_started: 'not_started',
  invoking: 'invoking',
  compensating: 'compensating',
  done: 'done',
  reverted: 'reverted',
  failed: 'failed',
  dormant: 'dormant',
  skipped: 'skipped',
  skipped_failure: 'skipped_failure',
  timeout: 'timeout',
} as const;
