/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of revoking the API key.
 */
export interface AdminRevokeApiKey {
  /** The time in seconds to revoke the API key after. If not set, the API key is revoked immediately. */
  revoke_in?: number;
}
