/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetOrders200AllOf } from './adminGetOrders200AllOf';
import type { AdminGetOrders200AllOfTwo } from './adminGetOrders200AllOfTwo';

export type AdminGetOrders200 = AdminGetOrders200AllOf & AdminGetOrders200AllOfTwo;
