/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStockLocation } from './adminStockLocation';

/**
 * The stock location's details.
 */
export interface AdminStockLocationResponse {
  stock_location: AdminStockLocation;
}
