/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCustomer } from './adminCustomer';

/**
 * The deletion's details.
 */
export type AdminDeleteCustomersIdAddressesAddressId200AllOfTwo = {
  parent?: AdminCustomer;
};
