/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetCustomerGroups200AllOf } from './adminGetCustomerGroups200AllOf';
import type { AdminGetCustomerGroups200AllOfTwo } from './adminGetCustomerGroups200AllOfTwo';

export type AdminGetCustomerGroups200 = AdminGetCustomerGroups200AllOf & AdminGetCustomerGroups200AllOfTwo;
