/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetPromotionsRuleValueOptionsRuleTypeRuleAttributeIdPromotionType } from './adminGetPromotionsRuleValueOptionsRuleTypeRuleAttributeIdPromotionType';
import type { AdminGetPromotionsRuleValueOptionsRuleTypeRuleAttributeIdApplicationMethodType } from './adminGetPromotionsRuleValueOptionsRuleTypeRuleAttributeIdApplicationMethodType';

export type AdminGetPromotionsRuleValueOptionsRuleTypeRuleAttributeIdParams = {
/**
 * The number of items to skip when retrieving a list.
 */
offset?: number;
/**
 * Limit the number of items returned in the list.
 */
limit?: number;
/**
 * The field to sort the data by. By default, the sort order is ascending. To change the order to descending, prefix the field name with `-`.
 */
order?: string;
/**
 * The promotion type to retrieve rules for.
 */
promotion_type?: AdminGetPromotionsRuleValueOptionsRuleTypeRuleAttributeIdPromotionType;
/**
 * The application method type to retrieve rules for.
 */
application_method_type?: AdminGetPromotionsRuleValueOptionsRuleTypeRuleAttributeIdApplicationMethodType;
};
