/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCampaignBudgetType } from './adminCampaignBudgetType';

/**
 * The campaign's budget.
 */
export type AdminCampaignBudget = {
  /** The budget's currency code. */
  currency_code: string;
  /** The budget's ID. */
  id: string;
  /** The budget's limit. */
  limit: number;
  /** The budget's type. `spend` means the limit is set on the total amount discounted by the campaign's promotions; `usage` means the limit is set on the total number of times the campaign's promotions can be used.
 */
  type: AdminCampaignBudgetType;
  /** How much of the budget has been used. If the limit is `spend`, this property holds the total amount discounted so far. If the limit is `usage`, it holds the number of times the campaign's promotions have been used so far.
 */
  used: number;
};
