/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostCustomersIdAddressesBodyAllOf } from './adminPostCustomersIdAddressesBodyAllOf';
import type { AdminPostCustomersIdAddressesBodyAllOfThree } from './adminPostCustomersIdAddressesBodyAllOfThree';

/**
 * The address's details.
 */
export type AdminPostCustomersIdAddressesBody = AdminPostCustomersIdAddressesBodyAllOf & AdminPostCustomersIdAddressesBodyAllOfThree;
