/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

export type AdminGetProductsStatusOneOfItem = typeof AdminGetProductsStatusOneOfItem[keyof typeof AdminGetProductsStatusOneOfItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminGetProductsStatusOneOfItem = {
  draft: 'draft',
  proposed: 'proposed',
  published: 'published',
  rejected: 'rejected',
} as const;
