/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The deletion's details.
 */
export type AdminDeleteCustomersId200 = {
  /** The customer's deleted. */
  deleted: boolean;
  /** The customer's ID. */
  id: string;
  /** The customer's object. */
  object: string;
};
