/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCreateShipmentLabelsItem } from './adminCreateShipmentLabelsItem';

/**
 * The shipment's details.
 */
export interface AdminCreateShipment {
  /** The shipment's labels. */
  labels: AdminCreateShipmentLabelsItem[];
}
