/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderPreviewShippingMethodsItemAllOfOnetwoActionsItem } from './adminOrderPreviewShippingMethodsItemAllOfOnetwoActionsItem';

/**
 * The shipping method's details.
 */
export type AdminOrderPreviewShippingMethodsItemAllOfOnetwo = {
  /** The actions applied on the shipping method. */
  actions?: AdminOrderPreviewShippingMethodsItemAllOfOnetwoActionsItem[];
};
