/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetCustomersIdAddresses200AllOf } from './adminGetCustomersIdAddresses200AllOf';
import type { AdminGetCustomersIdAddresses200AllOfTwo } from './adminGetCustomersIdAddresses200AllOfTwo';

export type AdminGetCustomersIdAddresses200 = AdminGetCustomersIdAddresses200AllOf & AdminGetCustomersIdAddresses200AllOfTwo;
