/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUpdateTaxRateMetadata } from './adminUpdateTaxRateMetadata';
import type { AdminUpdateTaxRateRulesItem } from './adminUpdateTaxRateRulesItem';

/**
 * The properties to update in the tax rate.
 */
export interface AdminUpdateTaxRate {
  /** The code that the tax rate is identified by. */
  code?: string;
  /** Whether the tax rate should be combined with parent rates. */
  is_combinable?: boolean;
  /** Whether the tax rate is the default in the store. */
  is_default?: boolean;
  /** The tax rate's metadata, can hold custom key-value pairs. */
  metadata?: AdminUpdateTaxRateMetadata;
  /** The tax rate's name. */
  name?: string;
  /** The rate to charge. */
  rate?: number;
  /** The tax rate's rules. */
  rules?: AdminUpdateTaxRateRulesItem[];
}
