/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCreateCollectionMetadata } from './adminCreateCollectionMetadata';

/**
 * the product collection's details.
 */
export interface AdminCreateCollection {
  /** The collection's handle. */
  handle?: string;
  /** The collection's metadata, used to store custom key-value pairs. */
  metadata?: AdminCreateCollectionMetadata;
  /** The collection's title. */
  title: string;
}
