/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOf } from './adminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOf';
import type { AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfThree } from './adminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfThree';
import type { AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfFive } from './adminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfFive';
import type { AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSeven } from './adminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSeven';

export type AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItem = AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOf | AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfThree | AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfFive | AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSeven;
