/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details to update in a product option.
 */
export interface AdminUpdateProductOption {
  /** The option's title. */
  title?: string;
  /** The option's values. */
  values?: string[];
}
