/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the shipping profile's deletion.
 */
export interface AdminShippingProfileDeleteResponse {
  /** Whether the shipping profile was deleted. */
  deleted: boolean;
  /** The shipping profile's ID. */
  id: string;
  /** The name of the deleted object. */
  object: string;
}
