/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetCustomersCreatedByOneOfAndItem } from './adminGetCustomersCreatedByOneOfAndItem';
import type { AdminGetCustomersCreatedByOneOfEq } from './adminGetCustomersCreatedByOneOfEq';
import type { AdminGetCustomersCreatedByOneOfGt } from './adminGetCustomersCreatedByOneOfGt';
import type { AdminGetCustomersCreatedByOneOfGte } from './adminGetCustomersCreatedByOneOfGte';
import type { AdminGetCustomersCreatedByOneOfInItem } from './adminGetCustomersCreatedByOneOfInItem';
import type { AdminGetCustomersCreatedByOneOfLt } from './adminGetCustomersCreatedByOneOfLt';
import type { AdminGetCustomersCreatedByOneOfLte } from './adminGetCustomersCreatedByOneOfLte';
import type { AdminGetCustomersCreatedByOneOfNe } from './adminGetCustomersCreatedByOneOfNe';
import type { AdminGetCustomersCreatedByOneOfNinItem } from './adminGetCustomersCreatedByOneOfNinItem';
import type { AdminGetCustomersCreatedByOneOfNot } from './adminGetCustomersCreatedByOneOfNot';
import type { AdminGetCustomersCreatedByOneOfOrItem } from './adminGetCustomersCreatedByOneOfOrItem';

/**
 * Filter by conditions on the user ID that created the customer.
 */
export type AdminGetCustomersCreatedByOneOf = {
  /** Join query parameters with an AND condition. Each object's content is the same type as the expected query parameters. */
  $and?: AdminGetCustomersCreatedByOneOfAndItem[];
  /** Filter arrays that contain all values of this parameter. */
  $contained?: string[];
  /** Filter arrays that contain some of the values of this parameter. */
  $contains?: string[];
  $eq?: AdminGetCustomersCreatedByOneOfEq;
  /** Filter by whether a value for this parameter exists (not `null`). */
  $exists?: boolean;
  /** Filter to apply on full-text properties. */
  $fulltext?: string;
  $gt?: AdminGetCustomersCreatedByOneOfGt;
  $gte?: AdminGetCustomersCreatedByOneOfGte;
  /** Apply a case-insensitive `like` filter. Useful for strings only. */
  $ilike?: string;
  /** Filter by values in this array. */
  $in?: AdminGetCustomersCreatedByOneOfInItem[];
  /** Apply a `like` filter. Useful for strings only. */
  $like?: string;
  $lt?: AdminGetCustomersCreatedByOneOfLt;
  $lte?: AdminGetCustomersCreatedByOneOfLte;
  $ne?: AdminGetCustomersCreatedByOneOfNe;
  /** Filter by values not in this array. */
  $nin?: AdminGetCustomersCreatedByOneOfNinItem[];
  $not?: AdminGetCustomersCreatedByOneOfNot;
  /** Join query parameters with an OR condition. Each object's content is the same type as the expected query parameters. */
  $or?: AdminGetCustomersCreatedByOneOfOrItem[];
  /** Filter arrays that have overlapping values with this parameter. */
  $overlap?: string[];
  /** Apply a regex filter. Useful for strings only. */
  $re?: string;
};
