/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The deletion's details.
 */
export type AdminDeleteCustomersIdAddressesAddressId200AllOf = {
  /** Whether the Customer was deleted. */
  deleted: boolean;
  /** The customer's ID. */
  id: string;
  /** The name of the deleted object. */
  object: string;
};
