/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostRegionsIdBodyMetadata } from './adminPostRegionsIdBodyMetadata';

/**
 * The propeties to update in the region.
 */
export type AdminPostRegionsIdBody = {
  /** Whether taxes are calculated automatically for carts in the region. */
  automatic_taxes?: boolean;
  /** The region's countries. */
  countries?: string[];
  /** The region's currency code. */
  currency_code?: string;
  /** Whether the prices in the region are tax inclusive. */
  is_tax_inclusive?: boolean;
  /** The region's metadata. Can hold custom key-value pairs. */
  metadata?: AdminPostRegionsIdBodyMetadata;
  /** The region's name. */
  name?: string;
  /** The payment providers enabled in the region. */
  payment_providers?: string[];
};
