/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderItem } from './adminOrderItem';

/**
 * SUMMARY
 */
export type AdminGetOrdersIdLineItems200 = {
  /** The order's order items. */
  order_items: AdminOrderItem[];
};
