/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminInventoryItem } from './adminInventoryItem';

/**
 * The paginated list of inventory items.
 */
export type AdminGetInventoryItems200AllOfTwo = {
  /** The inventory item's inventory items. */
  inventory_items: AdminInventoryItem[];
};
