/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the item to create shipment for.
 */
export type AdminPostOrdersIdFulfillmentsFulfillmentIdShipmentsBodyAllOfItemsItem = {
  /** The item's ID. */
  id: string;
  /** The item's quantity to ship. */
  quantity: number;
};
