/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The payment session's data, useful for the payment provider processing the payment.
 */
export type AdminPaymentSessionData = { [key: string]: unknown };
