/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSalesChannel } from './adminSalesChannel';

/**
 * The paginated list of sales channels.
 */
export type AdminGetSalesChannels200AllOfTwo = {
  /** The list of sales channels. */
  sales_channels: AdminSalesChannel[];
};
