/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostCustomersIdAddressesBodyAllOfMetadata } from './adminPostCustomersIdAddressesBodyAllOfMetadata';

/**
 * The address's details.
 */
export type AdminPostCustomersIdAddressesBodyAllOf = {
  /** The address's first line. */
  address_1: string;
  /** The address's second line. */
  address_2: string;
  /** The name of the address. */
  address_name: string;
  /** The address's city. */
  city: string;
  /** The address's company. */
  company: string;
  /** The address's country code. */
  country_code: string;
  /** The address's first name. */
  first_name: string;
  /** Whether this address is used by default for billing when placing an order. */
  is_default_billing?: boolean;
  /** Whether this address is used by default for shipping when placing an order. */
  is_default_shipping?: boolean;
  /** The address's last name. */
  last_name: string;
  /** The address's metadata. */
  metadata: AdminPostCustomersIdAddressesBodyAllOfMetadata;
  /** The address's phone. */
  phone: string;
  /** The address's postal code. */
  postal_code: string;
  /** The address's province. */
  province: string;
};
