/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostShippingOptionsIdBodyRulesItemOneOfFourOperator } from './adminPostShippingOptionsIdBodyRulesItemOneOfFourOperator';
import type { AdminPostShippingOptionsIdBodyRulesItemOneOfFourValue } from './adminPostShippingOptionsIdBodyRulesItemOneOfFourValue';

/**
 * Update the properties of an existing rule.
 */
export type AdminPostShippingOptionsIdBodyRulesItemOneOfFour = {
  /** The name of a property or table that the rule applies to. */
  attribute: string;
  /** The rule's ID. */
  id: string;
  /** The operator used to check whether a rule applies. */
  operator: AdminPostShippingOptionsIdBodyRulesItemOneOfFourOperator;
  value: AdminPostShippingOptionsIdBodyRulesItemOneOfFourValue;
};
