/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The shipping method's data, useful for fulfillment providers.
 */
export type AdminPostDraftOrdersBodyAllOfShippingMethodsItemData = { [key: string]: unknown };
