/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostDraftOrdersBodyAllOfBillingAddress } from './adminPostDraftOrdersBodyAllOfBillingAddress';
import type { AdminPostDraftOrdersBodyAllOfItemsItem } from './adminPostDraftOrdersBodyAllOfItemsItem';
import type { AdminPostDraftOrdersBodyAllOfMetadata } from './adminPostDraftOrdersBodyAllOfMetadata';
import type { AdminPostDraftOrdersBodyAllOfShippingAddress } from './adminPostDraftOrdersBodyAllOfShippingAddress';
import type { AdminPostDraftOrdersBodyAllOfShippingMethodsItem } from './adminPostDraftOrdersBodyAllOfShippingMethodsItem';
import type { AdminPostDraftOrdersBodyAllOfStatus } from './adminPostDraftOrdersBodyAllOfStatus';

/**
 * The draft order's details.
 */
export type AdminPostDraftOrdersBodyAllOf = {
  /** The billing address's details. */
  billing_address?: AdminPostDraftOrdersBodyAllOfBillingAddress;
  /** The draft order's currency code. */
  currency_code: string;
  /** The ID of the draft order's customer. */
  customer_id: string;
  /** The email of the draft order's customer. */
  email: string;
  /** The draft order's items. */
  items?: AdminPostDraftOrdersBodyAllOfItemsItem[];
  /** The draft order's metadata. */
  metadata: AdminPostDraftOrdersBodyAllOfMetadata;
  /** Whether to send the customer notifications on order changes. */
  no_notification_order?: boolean;
  /** The promotion codes applied on the draft order. */
  promo_codes?: string[];
  /** The ID of the associated region. */
  region_id: string;
  /** The ID of the associated sales channel. */
  sales_channel_id: string;
  /** The draft order's shipping address. */
  shipping_address?: AdminPostDraftOrdersBodyAllOfShippingAddress;
  /** The draft order's shipping methods. */
  shipping_methods: AdminPostDraftOrdersBodyAllOfShippingMethodsItem[];
  /** The draft order's status. */
  status?: AdminPostDraftOrdersBodyAllOfStatus;
};
