/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderChangeActionAction } from './adminOrderChangeActionAction';
import type { AdminOrderChangeActionDetails } from './adminOrderChangeActionDetails';
import type { AdminOrder } from './adminOrder';
import type { AdminOrderChangeActionOrderChange } from './adminOrderChangeActionOrderChange';
import type { AdminOrderChangeActionReference } from './adminOrderChangeActionReference';

/**
 * The order change action's details.
 */
export interface AdminOrderChangeAction {
  /** The applied action. */
  action: AdminOrderChangeActionAction;
  /** The ID of the associated claim. */
  claim_id: string;
  /** The date the action was created. */
  created_at: string;
  /** The action's details. */
  details: AdminOrderChangeActionDetails;
  /** The ID of the associated exchange. */
  exchange_id: string;
  /** The action's ID. */
  id: string;
  /** A note that's viewed only by admin users. */
  internal_note: string;
  order: AdminOrder;
  order_change: AdminOrderChangeActionOrderChange;
  /** The ID of the order change that the action belongs to. */
  order_change_id: string;
  /** The ID of the order the associated change is for. */
  order_id: string;
  /** The name of the table this action applies on. */
  reference: AdminOrderChangeActionReference;
  /** The ID of the record in the referenced table. */
  reference_id: string;
  /** The ID of the associated return. */
  return_id: string;
  /** The date the action was updated. */
  updated_at: string;
}
