/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The shipping profile's metadata, holds custom key-value pairs.
 */
export type AdminShippingProfileMetadata = { [key: string]: unknown };
