/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The image's details.
 */
export type AdminBatchUpdateProductImagesItem = {
  /** The image's URL. */
  url: string;
};
