/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { InventoryLevel } from './inventoryLevel';

/**
 * The paginated list of inventory levels.
 */
export type AdminGetInventoryItemsIdLocationLevels200AllOfTwo = {
  /** The inventory item's inventory levels. */
  inventory_levels: InventoryLevel[];
};
