/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostOrdersIdFulfillmentsFulfillmentIdCancelBodyAllOf } from './adminPostOrdersIdFulfillmentsFulfillmentIdCancelBodyAllOf';
import type { AdminPostOrdersIdFulfillmentsFulfillmentIdCancelBodyAllOfTwo } from './adminPostOrdersIdFulfillmentsFulfillmentIdCancelBodyAllOfTwo';

/**
 * The cancelation details.
 */
export type AdminPostOrdersIdFulfillmentsFulfillmentIdCancelBody = AdminPostOrdersIdFulfillmentsFulfillmentIdCancelBodyAllOf & AdminPostOrdersIdFulfillmentsFulfillmentIdCancelBodyAllOfTwo;
