/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCreateReservationMetadata } from './adminCreateReservationMetadata';

/**
 * The reservation's details.
 */
export interface AdminCreateReservation {
  /** The reservation's description. */
  description?: string;
  /** The ID of the inventory item associated with the line item's variant. */
  inventory_item_id: string;
  /** The ID of the line item this reservation is created for. */
  line_item_id?: string;
  /** The ID of the location the quantity is reserved from. */
  location_id: string;
  /** The reservation's metadata, used to store custom key-value pairs. */
  metadata?: AdminCreateReservationMetadata;
  /** The reserved quantity. */
  quantity: number;
}
