/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The rule's operator.
 */
export type AdminPromotionRuleOperator = typeof AdminPromotionRuleOperator[keyof typeof AdminPromotionRuleOperator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminPromotionRuleOperator = {
  gt: 'gt',
  lt: 'lt',
  eq: 'eq',
  ne: 'ne',
  in: 'in',
  lte: 'lte',
  gte: 'gte',
} as const;
