/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminProductTypeMetadata } from './adminProductTypeMetadata';

/**
 * The product type's details.
 */
export interface AdminProductType {
  /** The date the type was created. */
  created_at: string;
  /** The date the type was deleted. */
  deleted_at?: string;
  /** The type's ID. */
  id: string;
  /** The type's metadata, can hold custom key-value pairs. */
  metadata?: AdminProductTypeMetadata;
  /** The date the type was updated. */
  updated_at: string;
  /** The type's value. */
  value: string;
}
