/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostInvitesAccept200OneOf } from './adminPostInvitesAccept200OneOf';
import type { AdminPostInvitesAccept200OneOfTwo } from './adminPostInvitesAccept200OneOfTwo';

export type AdminPostInvitesAccept200 = AdminPostInvitesAccept200OneOf | AdminPostInvitesAccept200OneOfTwo;
