/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminBatchUpdateProductCategoriesItem } from './adminBatchUpdateProductCategoriesItem';
import type { AdminBatchUpdateProductImagesItem } from './adminBatchUpdateProductImagesItem';
import type { AdminBatchUpdateProductMetadata } from './adminBatchUpdateProductMetadata';
import type { AdminUpdateProductOption } from './adminUpdateProductOption';
import type { AdminBatchUpdateProductSalesChannelsItem } from './adminBatchUpdateProductSalesChannelsItem';
import type { AdminBatchUpdateProductStatus } from './adminBatchUpdateProductStatus';
import type { AdminBatchUpdateProductTagsItem } from './adminBatchUpdateProductTagsItem';
import type { AdminBatchUpdateProductVariantsItem } from './adminBatchUpdateProductVariantsItem';

/**
 * The product's details.
 */
export interface AdminBatchUpdateProduct {
  /** The product's categories. */
  categories?: AdminBatchUpdateProductCategoriesItem[];
  /** The ID of the product's collection. */
  collection_id?: string;
  /** The product's description. */
  description?: string;
  /** Whether discounts can be applied on the product. */
  discountable?: boolean;
  /** The ID of the product in an external or third-party system. */
  external_id?: string;
  /** The product's unique handle. */
  handle?: string;
  /** The product's height. */
  height?: number;
  /** The product's HS code. */
  hs_code?: string;
  /** The product's ID. */
  id: string;
  /** The product's images. */
  images?: AdminBatchUpdateProductImagesItem[];
  /** Whether the product is a gift card. */
  is_giftcard?: boolean;
  /** The product's length. */
  length?: number;
  /** The product's material. */
  material?: string;
  /** The product's metadata, can hold custom key-value pairs. */
  metadata?: AdminBatchUpdateProductMetadata;
  /** The product's MID code. */
  mid_code?: string;
  /** The product's options. */
  options?: AdminUpdateProductOption[];
  /** The product's origin country. */
  origin_country?: string;
  /** The sales channels that the product is available in. */
  sales_channels?: AdminBatchUpdateProductSalesChannelsItem[];
  /** The product's status. */
  status?: AdminBatchUpdateProductStatus;
  /** The product's subtitle. */
  subtitle?: string;
  /** The product's tags. */
  tags?: AdminBatchUpdateProductTagsItem[];
  /** The product's thumbnail URL. */
  thumbnail?: string;
  /** The product's title. */
  title?: string;
  /** The ID of the product's type. */
  type_id?: string;
  /** The product's variants. You can add new variants or update existing ones, passing their IDs in the object. */
  variants?: AdminBatchUpdateProductVariantsItem[];
  /** The product's weight. */
  weight?: number;
  /** The product's width. */
  width?: number;
}
