/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSalesChannel } from './adminSalesChannel';

/**
 * The sales channel's details.
 */
export interface AdminSalesChannelResponse {
  sales_channel: AdminSalesChannel;
}
