/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCreateRegionMetadata } from './adminCreateRegionMetadata';

/**
 * The region's details.
 */
export interface AdminCreateRegion {
  /** Whether taxes are calculated automatically during checkout in this region. */
  automatic_taxes?: boolean;
  /** The region's countries. */
  countries?: string[];
  /** The region's currency code. */
  currency_code: string;
  /** Whether prices in this region are tax inclusive. */
  is_tax_inclusive?: boolean;
  /** The region's metadata, used to store custom key-value pairs. */
  metadata?: AdminCreateRegionMetadata;
  /** The region's name. */
  name: string;
  /** The payment providers enabled in this region. */
  payment_providers?: string[];
}
