/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetCustomersIdOneOfNotOneOf } from './adminGetCustomersIdOneOfNotOneOf';
import type { AdminGetCustomersIdOneOfNotOneOfSevenItem } from './adminGetCustomersIdOneOfNotOneOfSevenItem';

export type AdminGetCustomersIdOneOfNot = string | AdminGetCustomersIdOneOfNotOneOf | string[] | AdminGetCustomersIdOneOfNotOneOfSevenItem[];
