/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The payment collection's details.
 */
export type AdminPostPaymentCollectionsBody = {
  /** The amount to be paid. */
  amount: number;
  /** The ID of the associated order. */
  order_id: string;
};
