/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminImportProductRequestFile } from './adminImportProductRequestFile';

/**
 * The import's details.
 */
export interface AdminImportProductRequest {
  /** A File to upload. */
  file: AdminImportProductRequestFile;
}
