/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminProductTagMetadata } from './adminProductTagMetadata';

/**
 * The product tag's details.
 */
export interface AdminProductTag {
  /** The date the tag was created. */
  created_at: string;
  /** The date the tag was deleted. */
  deleted_at?: string;
  /** The tag's ID. */
  id: string;
  /** The tag's metadata, can hold custom key-value pairs. */
  metadata?: AdminProductTagMetadata;
  /** The date the tag was updated. */
  updated_at: string;
  /** The tag's value. */
  value: string;
}
