/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderChange } from './adminOrderChange';

/**
 * An order edit's details.
 */
export interface AdminOrderEditResponse {
  order_change: AdminOrderChange;
}
