/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetProductsIdVariants200AllOf } from './adminGetProductsIdVariants200AllOf';
import type { AdminGetProductsIdVariants200AllOfTwo } from './adminGetProductsIdVariants200AllOfTwo';

export type AdminGetProductsIdVariants200 = AdminGetProductsIdVariants200AllOf & AdminGetProductsIdVariants200AllOfTwo;
