/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCampaign } from './adminCampaign';

/**
 * The campaign's details.
 */
export interface AdminCampaignResponse {
  campaign: AdminCampaign;
}
