/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStoreMetadata } from './adminStoreMetadata';
import type { AdminStoreCurrency } from './adminStoreCurrency';

/**
 * The store's details.
 */
export interface AdminStore {
  /** The date the store was created. */
  created_at: string;
  /** The ID of the stock location used by default in the store. */
  default_location_id: string;
  /** The ID of the region used by default in the store. */
  default_region_id: string;
  /** The ID of the sales channel used by default in the store. */
  default_sales_channel_id: string;
  /** The store's ID. */
  id: string;
  /** The store's metadata, can hold custom key-value pairs. */
  metadata: AdminStoreMetadata;
  /** The store's name. */
  name: string;
  /** The store's supported currencies. */
  supported_currencies: AdminStoreCurrency[];
  /** The date the store was updated. */
  updated_at: string;
}
