/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetTaxRatesTaxRegionIdOneOf } from './adminGetTaxRatesTaxRegionIdOneOf';
import type { AdminGetTaxRatesIsDefault } from './adminGetTaxRatesIsDefault';
import type { AdminGetTaxRatesCreatedAtAndItem } from './adminGetTaxRatesCreatedAtAndItem';
import type { AdminGetTaxRatesCreatedAtEq } from './adminGetTaxRatesCreatedAtEq';
import type { AdminGetTaxRatesCreatedAtNot } from './adminGetTaxRatesCreatedAtNot';
import type { AdminGetTaxRatesCreatedAtOrItem } from './adminGetTaxRatesCreatedAtOrItem';
import type { AdminGetTaxRatesUpdatedAtAndItem } from './adminGetTaxRatesUpdatedAtAndItem';
import type { AdminGetTaxRatesUpdatedAtEq } from './adminGetTaxRatesUpdatedAtEq';
import type { AdminGetTaxRatesUpdatedAtNot } from './adminGetTaxRatesUpdatedAtNot';
import type { AdminGetTaxRatesUpdatedAtOrItem } from './adminGetTaxRatesUpdatedAtOrItem';
import type { AdminGetTaxRatesDeletedAtAndItem } from './adminGetTaxRatesDeletedAtAndItem';
import type { AdminGetTaxRatesDeletedAtEq } from './adminGetTaxRatesDeletedAtEq';
import type { AdminGetTaxRatesDeletedAtNot } from './adminGetTaxRatesDeletedAtNot';
import type { AdminGetTaxRatesDeletedAtOrItem } from './adminGetTaxRatesDeletedAtOrItem';
import type { AdminGetTaxRatesAndItem } from './adminGetTaxRatesAndItem';
import type { AdminGetTaxRatesOrItem } from './adminGetTaxRatesOrItem';

export type AdminGetTaxRatesParams = {
/**
 * Comma-separated fields that should be included in the returned data. if a field is prefixed with `+` it will be added to the default fields, using `-` will remove it from the default fields. without prefix it will replace the entire default fields.
 */
fields?: string;
/**
 * The number of items to skip when retrieving a list.
 */
offset?: number;
/**
 * Limit the number of items returned in the list.
 */
limit?: number;
/**
 * The field to sort the data by. By default, the sort order is ascending. To change the order to descending, prefix the field name with `-`.
 */
order?: string;
/**
 * Search terms to filter the tax rate's searchable properties.
 */
q?: string;
tax_region_id?: string | string[] | AdminGetTaxRatesTaxRegionIdOneOf;
/**
 * Filter by whether the tax rate is a default in its tax region.
 */
is_default?: AdminGetTaxRatesIsDefault;
/**
 * Filter by a tax rate's creation date.
 */
created_at?: {
  /** Join query parameters with an AND condition. Each object's content is the same type as the expected query parameters. */
  $and?: AdminGetTaxRatesCreatedAtAndItem[];
  /** Filter arrays that contain all values of this parameter. */
  $contained?: string[];
  /** Filter arrays that contain some of the values of this parameter. */
  $contains?: string[];
  $eq?: AdminGetTaxRatesCreatedAtEq;
  /** Filter by whether a value for this parameter exists (not `null`). */
  $exists?: boolean;
  /** Filter to apply on full-text properties. */
  $fulltext?: string;
  /** Filter by values greater than this parameter. Useful for numbers and dates only. */
  $gt?: string;
  /** Filter by values greater than or equal to this parameter. Useful for numbers and dates only. */
  $gte?: string;
  /** Apply a case-insensitive `like` filter. Useful for strings only. */
  $ilike?: string;
  /** Filter by values in this array. */
  $in?: string[];
  /** Apply a `like` filter. Useful for strings only. */
  $like?: string;
  /** Filter by values less than this parameter. Useful for numbers and dates only. */
  $lt?: string;
  /** Filter by values less than or equal to this parameter. Useful for numbers and dates only. */
  $lte?: string;
  /** Filter by values not equal to this parameter. */
  $ne?: string;
  /** Filter by values not in this array. */
  $nin?: string[];
  $not?: AdminGetTaxRatesCreatedAtNot;
  /** Join query parameters with an OR condition. Each object's content is the same type as the expected query parameters. */
  $or?: AdminGetTaxRatesCreatedAtOrItem[];
  /** Filter arrays that have overlapping values with this parameter. */
  $overlap?: string[];
  /** Apply a regex filter. Useful for strings only. */
  $re?: string;
};
/**
 * Filter by a tax rate's update date.
 */
updated_at?: {
  /** Join query parameters with an AND condition. Each object's content is the same type as the expected query parameters. */
  $and?: AdminGetTaxRatesUpdatedAtAndItem[];
  /** Filter arrays that contain all values of this parameter. */
  $contained?: string[];
  /** Filter arrays that contain some of the values of this parameter. */
  $contains?: string[];
  $eq?: AdminGetTaxRatesUpdatedAtEq;
  /** Filter by whether a value for this parameter exists (not `null`). */
  $exists?: boolean;
  /** Filter to apply on full-text properties. */
  $fulltext?: string;
  /** Filter by values greater than this parameter. Useful for numbers and dates only. */
  $gt?: string;
  /** Filter by values greater than or equal to this parameter. Useful for numbers and dates only. */
  $gte?: string;
  /** Apply a case-insensitive `like` filter. Useful for strings only. */
  $ilike?: string;
  /** Filter by values in this array. */
  $in?: string[];
  /** Apply a `like` filter. Useful for strings only. */
  $like?: string;
  /** Filter by values less than this parameter. Useful for numbers and dates only. */
  $lt?: string;
  /** Filter by values less than or equal to this parameter. Useful for numbers and dates only. */
  $lte?: string;
  /** Filter by values not equal to this parameter. */
  $ne?: string;
  /** Filter by values not in this array. */
  $nin?: string[];
  $not?: AdminGetTaxRatesUpdatedAtNot;
  /** Join query parameters with an OR condition. Each object's content is the same type as the expected query parameters. */
  $or?: AdminGetTaxRatesUpdatedAtOrItem[];
  /** Filter arrays that have overlapping values with this parameter. */
  $overlap?: string[];
  /** Apply a regex filter. Useful for strings only. */
  $re?: string;
};
/**
 * Filter by a tax rate's deletion date.
 */
deleted_at?: {
  /** Join query parameters with an AND condition. Each object's content is the same type as the expected query parameters. */
  $and?: AdminGetTaxRatesDeletedAtAndItem[];
  /** Filter arrays that contain all values of this parameter. */
  $contained?: string[];
  /** Filter arrays that contain some of the values of this parameter. */
  $contains?: string[];
  $eq?: AdminGetTaxRatesDeletedAtEq;
  /** Filter by whether a value for this parameter exists (not `null`). */
  $exists?: boolean;
  /** Filter to apply on full-text properties. */
  $fulltext?: string;
  /** Filter by values greater than this parameter. Useful for numbers and dates only. */
  $gt?: string;
  /** Filter by values greater than or equal to this parameter. Useful for numbers and dates only. */
  $gte?: string;
  /** Apply a case-insensitive `like` filter. Useful for strings only. */
  $ilike?: string;
  /** Filter by values in this array. */
  $in?: string[];
  /** Apply a `like` filter. Useful for strings only. */
  $like?: string;
  /** Filter by values less than this parameter. Useful for numbers and dates only. */
  $lt?: string;
  /** Filter by values less than or equal to this parameter. Useful for numbers and dates only. */
  $lte?: string;
  /** Filter by values not equal to this parameter. */
  $ne?: string;
  /** Filter by values not in this array. */
  $nin?: string[];
  $not?: AdminGetTaxRatesDeletedAtNot;
  /** Join query parameters with an OR condition. Each object's content is the same type as the expected query parameters. */
  $or?: AdminGetTaxRatesDeletedAtOrItem[];
  /** Filter arrays that have overlapping values with this parameter. */
  $overlap?: string[];
  /** Apply a regex filter. Useful for strings only. */
  $re?: string;
};
$and?: AdminGetTaxRatesAndItem[];
$or?: AdminGetTaxRatesOrItem[];
/**
 * Filter by a service zone's ID to retrieve its associated tax rates.
 */
service_zone_id?: string;
/**
 * Filter by a shipping profile's ID to retrieve its associated tax rates.
 */
shipping_profile_id?: string;
/**
 * Filter by a fulfillment provider's ID to retrieve its associated tax rates.
 */
provider_id?: string;
/**
 * Filter by a shipping option type's ID to retrieve its associated tax rates.
 */
shipping_option_type_id?: string;
};
