/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The deleted products' details.
 */
export type AdminBatchProductResponseDeleted = {
  /** Whether the products were deleted. */
  deleted: boolean;
  /** The IDs of deleted products. */
  ids: string[];
  /** The name of the deleted objects. */
  object: string;
};
