/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPaymentProvider } from './adminPaymentProvider';

/**
 * The paginated list of payment providers.
 */
export type AdminGetPaymentsPaymentProviders200AllOfTwo = {
  /** The list of payment providers. */
  payment_providers: AdminPaymentProvider[];
};
