/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetProductsCreatedAtNotOneOf } from './adminGetProductsCreatedAtNotOneOf';

export type AdminGetProductsCreatedAtNot = string | AdminGetProductsCreatedAtNotOneOf | string[];
