/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminShippingOption } from './adminShippingOption';

/**
 * The shipping option's details.
 */
export interface AdminShippingOptionResponse {
  shipping_option: AdminShippingOption;
}
