/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminProductImageMetadata } from './adminProductImageMetadata';

/**
 * The image's details.
 */
export interface AdminProductImage {
  /** The date the image was created. */
  created_at?: string;
  /** The date the image was deleted. */
  deleted_at?: string;
  /** The image's ID. */
  id: string;
  /** The image's metadata, can hold custom key-value pairs. */
  metadata?: AdminProductImageMetadata;
  /** The image's rank among sibling images. */
  rank: number;
  /** The date the image was updated. */
  updated_at?: string;
  /** The image's URL. */
  url: string;
}
