/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Which item does the promotion apply to. `items` mean the promotion applies to the cart's items; `shipping_methods` means the promotion applies to the cart's shipping methods; `order` means the promotion applies on the entire order.
 */
export type AdminApplicationMethodTargetType = typeof AdminApplicationMethodTargetType[keyof typeof AdminApplicationMethodTargetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminApplicationMethodTargetType = {
  items: 'items',
  shipping_methods: 'shipping_methods',
  order: 'order',
} as const;
