/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the deleted shipping option rules.
 */
export type AdminPostShippingOptionsIdRulesBatch200Deleted = {
  /** The deleted's details. */
  deleted: boolean;
  /** The IDs of the deleted shipping option rules. */
  ids: string[];
  /** The name of the deleted object. */
  object: string;
};
