/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostOrdersIdFulfillmentsBodyAllOf } from './adminPostOrdersIdFulfillmentsBodyAllOf';
import type { AdminPostOrdersIdFulfillmentsBodyAllOfFour } from './adminPostOrdersIdFulfillmentsBodyAllOfFour';

/**
 * The fulfillment's details.
 */
export type AdminPostOrdersIdFulfillmentsBody = AdminPostOrdersIdFulfillmentsBodyAllOf & AdminPostOrdersIdFulfillmentsBodyAllOfFour;
