/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSevenMetadata } from './adminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSevenMetadata';
import type { AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSevenPostalExpression } from './adminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSevenPostalExpression';

/**
 * A ZIP geo zone.
 */
export type AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSeven = {
  /** The geo zone's city. */
  city: string;
  /** The geo zone's country code. */
  country_code: string;
  /** The ID of an existing geo zone. */
  id?: string;
  /** The geo zone's metadata. */
  metadata: AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSevenMetadata;
  /** The geo zone's postal expression or ZIP code. */
  postal_expression: AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItemOneOfSevenPostalExpression;
  /** The geo zone's province code. */
  province_code: string;
  /** The geo zone's type. */
  type: string;
};
