/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostReturnsShippingActionReqSchemaMetadata } from './adminPostReturnsShippingActionReqSchemaMetadata';

/**
 * The shipping method's details.
 */
export interface AdminPostReturnsShippingActionReqSchema {
  /** Set a custom price for the shipping method. */
  custom_amount?: number;
  /** A note viewed only by admin users. */
  internal_note?: string;
  /** The return's metadata, can hold custom key-value pairs. */
  metadata?: AdminPostReturnsShippingActionReqSchemaMetadata;
}
