/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The product's tag.
 */
export type AdminBatchUpdateProductTagsItem = {
  /** The tag's ID. */
  id: string;
};
