/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminClaim } from './adminClaim';
import type { Order } from './order';

/**
 * The created claim's details.
 */
export interface AdminClaimOrderResponse {
  claim: AdminClaim;
  order: Order;
}
