/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The tax rate's metadata, used to store custom key-value pairs.
 */
export type AdminCreateTaxRateMetadata = { [key: string]: unknown };
