/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The invite's metadata. Can be custom data in key-value pairs.
 */
export type AdminPostInvitesBodyMetadata = { [key: string]: unknown };
