/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetPayments200AllOf } from './adminGetPayments200AllOf';
import type { AdminGetPayments200AllOfTwo } from './adminGetPayments200AllOfTwo';

export type AdminGetPayments200 = AdminGetPayments200AllOf & AdminGetPayments200AllOfTwo;
