/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfSevenMetadata } from './adminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfSevenMetadata';
import type { AdminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfSevenPostalExpression } from './adminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfSevenPostalExpression';

/**
 * A ZIP geo zone.
 */
export type AdminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfSeven = {
  /** The geo zone's city. */
  city: string;
  /** The geo zone's country code. */
  country_code: string;
  /** The geo zone's metadata. */
  metadata: AdminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfSevenMetadata;
  /** The geo zone's postal expression or ZIP code. */
  postal_expression: AdminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfSevenPostalExpression;
  /** The geo zone's province code. */
  province_code: string;
  /** The geo zone's type. */
  type: string;
};
