/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostCustomersIdAddressesAddressIdBodyAllOf } from './adminPostCustomersIdAddressesAddressIdBodyAllOf';
import type { AdminPostCustomersIdAddressesAddressIdBodyAllOfThree } from './adminPostCustomersIdAddressesAddressIdBodyAllOfThree';

/**
 * The address's details.
 */
export type AdminPostCustomersIdAddressesAddressIdBody = AdminPostCustomersIdAddressesAddressIdBodyAllOf & AdminPostCustomersIdAddressesAddressIdBodyAllOfThree;
