/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminInvite } from './adminInvite';

/**
 * The paginated list of invites.
 */
export type AdminGetInvites200AllOfTwo = {
  /** The list of invites. */
  invites: AdminInvite[];
};
