/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfFiveMetadata } from './adminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfFiveMetadata';

/**
 * A city geo zone
 */
export type AdminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfFive = {
  /** The geo zone's city. */
  city: string;
  /** The geo zone's country code. */
  country_code: string;
  /** The geo zone's metadata. */
  metadata: AdminPostFulfillmentSetsIdServiceZonesBodyGeoZonesItemOneOfFiveMetadata;
  /** The geo zone's province code. */
  province_code: string;
  /** The geo zone's type. */
  type: string;
};
