/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the deleted claim.
 */
export interface AdminClaimDeleteResponse {
  /** Whether the claim was deleted. */
  deleted: boolean;
  /** The claim's ID. */
  id: string;
  /** The name of the deleted object. */
  object: string;
}
