/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A fulfillment status.
 */
export type AdminGetOrdersFulfillmentStatusItem = typeof AdminGetOrdersFulfillmentStatusItem[keyof typeof AdminGetOrdersFulfillmentStatusItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminGetOrdersFulfillmentStatusItem = {
  canceled: 'canceled',
  not_fulfilled: 'not_fulfilled',
  partially_fulfilled: 'partially_fulfilled',
  fulfilled: 'fulfilled',
  partially_shipped: 'partially_shipped',
  shipped: 'shipped',
  partially_delivered: 'partially_delivered',
  delivered: 'delivered',
} as const;
