/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostPriceListsIdPricesBatchBodyCreateItem } from './adminPostPriceListsIdPricesBatchBodyCreateItem';
import type { AdminPostPriceListsIdPricesBatchBodyUpdateItem } from './adminPostPriceListsIdPricesBatchBodyUpdateItem';

/**
 * The prices to create, update, or delete.
 */
export type AdminPostPriceListsIdPricesBatchBody = {
  /** The prices to create. */
  create?: AdminPostPriceListsIdPricesBatchBodyCreateItem[];
  /** The prices to delete. */
  delete?: string[];
  /** The prices to update. */
  update?: AdminPostPriceListsIdPricesBatchBodyUpdateItem[];
};
