/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItem } from './adminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItem';

/**
 * The service zone's details.
 */
export type AdminPostFulfillmentSetsIdServiceZonesZoneIdBody = {
  /** The service zone's associated geo zones. */
  geo_zones?: AdminPostFulfillmentSetsIdServiceZonesZoneIdBodyGeoZonesItem[];
  /** The service zone's name. */
  name?: string;
};
