/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The allocation value that indicates whether the associated promotion is applied on each item in a cart or split between the items in the cart.
 */
export type AdminPostPromotionsIdBodyAllOfApplicationMethodAllocation = typeof AdminPostPromotionsIdBodyAllOfApplicationMethodAllocation[keyof typeof AdminPostPromotionsIdBodyAllOfApplicationMethodAllocation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminPostPromotionsIdBodyAllOfApplicationMethodAllocation = {
  each: 'each',
  across: 'across',
} as const;
