/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostOrderEditsShippingActionReqSchemaMetadata } from './adminPostOrderEditsShippingActionReqSchemaMetadata';

/**
 * The shipping method's details.
 */
export interface AdminPostOrderEditsShippingActionReqSchema {
  /** Set a custom price for the shipping method. */
  custom_amount?: number;
  /** A note viewed only by admin users. */
  internal_note?: string;
  /** The order edit's metadata, can hold custom key-value pairs. */
  metadata?: AdminPostOrderEditsShippingActionReqSchemaMetadata;
}
