/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCreateProductTagMetadata } from './adminCreateProductTagMetadata';

/**
 * The product tag's details.
 */
export interface AdminCreateProductTag {
  /** The product tag's metadata, used to store custom key-value pairs. */
  metadata?: AdminCreateProductTagMetadata;
  /** The product tag's value. */
  value: string;
}
