/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The promotions to add or remove from the campaign.
 */
export type AdminPostCampaignsIdPromotionsBody = {
  /** The promotions to add to the campaign. */
  add?: string[];
  /** The promotions to remove from the campaign. */
  remove?: string[];
};
