/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCreateProductCategoryMetadata } from './adminCreateProductCategoryMetadata';

/**
 * The product category's details.
 */
export interface AdminCreateProductCategory {
  /** The product category's description. */
  description?: string;
  /** The product category's handle. */
  handle?: string;
  /** Whether the product category is active. */
  is_active?: boolean;
  /** Whether the product category is only used and seen by admin users. */
  is_internal?: boolean;
  /** The product category's metadata, used to store custom key-value pairs. */
  metadata?: AdminCreateProductCategoryMetadata;
  /** The product category's name. */
  name: string;
  /** The ID of a category that's the parent of this one. */
  parent_category_id?: string;
  /** The sorting order of the product category among sibling categories. */
  rank?: number;
}
