/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUpdateStoreMetadata } from './adminUpdateStoreMetadata';
import type { AdminUpdateStoreSupportedCurrenciesItem } from './adminUpdateStoreSupportedCurrenciesItem';

/**
 * The properties to update in a store.
 */
export interface AdminUpdateStore {
  /** The ID of the default stock location in the store. */
  default_location_id?: string;
  /** The ID of the default region in the store. */
  default_region_id?: string;
  /** The ID of the default sales channel in the store. */
  default_sales_channel_id?: string;
  /** The store's metadata, can hold custom key-value pairs. */
  metadata?: AdminUpdateStoreMetadata;
  /** The store's name. */
  name?: string;
  /** The store's supported currencies. */
  supported_currencies?: AdminUpdateStoreSupportedCurrenciesItem[];
}
