/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the deleted user.
 */
export interface AdminUserDeleteResponse {
  /** Whether the user was deleted. */
  deleted: boolean;
  /** The user's ID. */
  id: string;
  /** The name of the deleted object. */
  object: string;
}
