/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCreateProductVariantPriceRules } from './adminCreateProductVariantPriceRules';

/**
 * The details of a variant's price.
 */
export interface AdminCreateProductVariantPrice {
  /** The price's amount. */
  amount: number;
  /** The price's currency code. */
  currency_code: string;
  /** The maximum quantity that must not be surpassed in the cart for this price to apply. */
  max_quantity?: number;
  /** The minimum quantity that must be available in the cart for this price to apply. */
  min_quantity?: number;
  /** The price's rules. */
  rules?: AdminCreateProductVariantPriceRules;
}
