/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The shipping option's price for a currency code.
 */
export type AdminPostShippingOptionsIdBodyPricesItemOneOf = {
  /** The price's amount. */
  amount?: number;
  /** The price's currency code. */
  currency_code?: string;
  /** The ID of an existing price. */
  id?: string;
};
