/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of the product type deletion.
 */
export interface AdminProductTypeDeleteResponse {
  /** Whether the product type was deleted. */
  deleted: boolean;
  /** The product type's ID. */
  id: string;
  /** The name of the deleted object. */
  object: string;
}
