/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderItemHistory } from './adminOrderItemHistory';
import type { AdminOrderLineItem } from './adminOrderLineItem';

/**
 * The order item's details.
 */
export interface AdminOrderItem {
  /** The order item's history. */
  history: AdminOrderItemHistory;
  item: AdminOrderLineItem;
  /** The ID of the associated line item. */
  item_id: string;
  /** The ID of the order this item belongs to. */
  order_id: string;
  /** The order item's version. */
  version: number;
}
