/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The customers to add or remove from the group.
 */
export type AdminPostCustomerGroupsIdCustomersBody = {
  /** The customers to add to the group. */
  add?: string[];
  /** The customers to remove from the group. */
  remove?: string[];
};
