/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetTaxRates200AllOf } from './adminGetTaxRates200AllOf';
import type { AdminGetTaxRates200AllOfTwo } from './adminGetTaxRates200AllOfTwo';

export type AdminGetTaxRates200 = AdminGetTaxRates200AllOf & AdminGetTaxRates200AllOfTwo;
