/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The geo zone's type.
 */
export type AdminGeoZoneType = typeof AdminGeoZoneType[keyof typeof AdminGeoZoneType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminGeoZoneType = {
  country: 'country',
  province: 'province',
  city: 'city',
  zip: 'zip',
} as const;
