/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of the shipping option's price. If `calculated`, its price is retrieved by the  associated fulfillment provider during checkout. If `flat`, its price is set in the `prices` property.

 */
export type AdminPostShippingOptionsIdBodyPriceType = typeof AdminPostShippingOptionsIdBodyPriceType[keyof typeof AdminPostShippingOptionsIdBodyPriceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminPostShippingOptionsIdBodyPriceType = {
  calculated: 'calculated',
  flat: 'flat',
} as const;
