/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostExchangesAddItemsReqSchemaItemsItemMetadata } from './adminPostExchangesAddItemsReqSchemaItemsItemMetadata';

/**
 * An item's details.
 */
export type AdminPostExchangesAddItemsReqSchemaItemsItem = {
  /** Whether the item can be added even if it's not in stock. */
  allow_backorder?: boolean;
  /** A note viewed only by admin users. */
  internal_note?: string;
  /** The item's metadata, can hold custom key-value pairs. */
  metadata?: AdminPostExchangesAddItemsReqSchemaItemsItemMetadata;
  /** The item's quantity. */
  quantity: number;
  /** The item's unit price. */
  unit_price?: number;
  /** The ID of the associated product variant. */
  variant_id: string;
};
