/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostCustomersBodyAllOf } from './adminPostCustomersBodyAllOf';
import type { AdminPostCustomersBodyAllOfThree } from './adminPostCustomersBodyAllOfThree';

/**
 * The customer's details.
 */
export type AdminPostCustomersBody = AdminPostCustomersBodyAllOf & AdminPostCustomersBodyAllOfThree;
