/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostProductTypesIdBodyMetadata } from './adminPostProductTypesIdBodyMetadata';

/**
 * The properties to update in the product type.
 */
export type AdminPostProductTypesIdBody = {
  /** The product type's metadata. Can hold custom key-value pairs. */
  metadata?: AdminPostProductTypesIdBodyMetadata;
  /** The product type's value. */
  value?: string;
};
