/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminProductCategory } from './adminProductCategory';
import type { AdminCollection } from './adminCollection';
import type { AdminProductImage } from './adminProductImage';
import type { AdminProductMetadata } from './adminProductMetadata';
import type { AdminProductOption } from './adminProductOption';
import type { AdminSalesChannel } from './adminSalesChannel';
import type { AdminProductStatus } from './adminProductStatus';
import type { AdminProductTag } from './adminProductTag';
import type { AdminProductType } from './adminProductType';
import type { AdminProductVariant } from './adminProductVariant';

/**
 * The product's details.
 */
export interface AdminProduct {
  /** The product's categories. */
  categories?: AdminProductCategory[];
  collection?: AdminCollection;
  /** The ID of the collection that the product belongs to. */
  collection_id: string;
  /** The date the product was created. */
  created_at: string;
  /** The date the product was deleted. */
  deleted_at: string;
  /** The product's description. */
  description: string;
  /** Whether discounts can be applied on the product. */
  discountable: boolean;
  /** The ID of a product in an external system, such as an ERP or CMS. */
  external_id: string;
  /** The product's unique handle. */
  handle: string;
  /** The product's height. */
  height: number;
  /** The product's HS code. */
  hs_code: string;
  /** The product's ID. */
  id: string;
  /** The product's images. */
  images: AdminProductImage[];
  /** Whether the product is a gift card. */
  is_giftcard: boolean;
  /** The product's length. */
  length: number;
  /** The product's material. */
  material: string;
  /** The product's metadata, can hold custom key-value pairs. */
  metadata?: AdminProductMetadata;
  /** The product's MID code. */
  mid_code: string;
  /** The product's options. */
  options: AdminProductOption[];
  /** The product's origin country. */
  origin_country: string;
  /** The sales channels that the product is available in. */
  sales_channels?: AdminSalesChannel[];
  /** The product's status. */
  status: AdminProductStatus;
  /** The product's subtitle. */
  subtitle: string;
  /** The product's tags. */
  tags?: AdminProductTag[];
  /** The product's thumbnail. */
  thumbnail: string;
  /** The product's title. */
  title: string;
  type: AdminProductType;
  /** The ID of the product's type. */
  type_id: string;
  /** The date the product was updated. */
  updated_at: string;
  /** The product's variants. */
  variants: AdminProductVariant[];
  /** The product's weight. */
  weight: number;
  /** The product's width. */
  width: number;
}
