/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPayment } from './adminPayment';

/**
 * The paginated list of payments.
 */
export type AdminGetPayments200AllOfTwo = {
  /** The list of payments. */
  payments: AdminPayment[];
};
