/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGetReturnReasonsCreatedAtNotOneOf } from './adminGetReturnReasonsCreatedAtNotOneOf';

export type AdminGetReturnReasonsCreatedAtNot = string | AdminGetReturnReasonsCreatedAtNotOneOf | string[];
