/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The products to add or remove from the channel.
 */
export type AdminPostSalesChannelsIdProductsBody = {
  /** The products to add to the sales channel. */
  add?: string[];
  /** The products to remove from the sales channel. */
  remove?: string[];
};
