/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminFulfillmentData } from './adminFulfillmentData';
import type { AdminFulfillmentAddress } from './adminFulfillmentAddress';
import type { AdminFulfillmentItem } from './adminFulfillmentItem';
import type { AdminFulfillmentLabel } from './adminFulfillmentLabel';
import type { AdminFulfillmentMetadata } from './adminFulfillmentMetadata';
import type { AdminFulfillmentProvider } from './adminFulfillmentProvider';

/**
 * The fulfillment's details.
 */
export interface AdminFulfillment {
  /** The date the fulfillment was canceled at. */
  canceled_at: string;
  /** The date the fulfillment was created at. */
  created_at: string;
  /** The fulfillment's data, useful for the third-party provider handling the fulfillment. */
  data: AdminFulfillmentData;
  /** The date the fulfillment was deleted at. */
  deleted_at: string;
  /** The date the fulfillment was delivered at. */
  delivered_at: string;
  delivery_address: AdminFulfillmentAddress;
  /** The fulfillment's ID. */
  id: string;
  /** The fulfillment's items. */
  items: AdminFulfillmentItem[];
  /** The fulfillment's shipment labels. */
  labels: AdminFulfillmentLabel[];
  /** The ID of the location the fulfillment's items are shipped from. */
  location_id: string;
  /** The fulfillment's metadata, can hold custom key-value pairs. */
  metadata: AdminFulfillmentMetadata;
  /** The date the fulfillment was packed at. */
  packed_at: string;
  provider: AdminFulfillmentProvider;
  /** The ID of the fulfillment provider handling this fulfillment. */
  provider_id: string;
  /** The date the fulfillment was shipped at. */
  shipped_at: string;
  /** The ID of the shipping option this fulfillment is created for. */
  shipping_option_id: string;
  /** The date the fulfillment was updated at. */
  updated_at: string;
}
