/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The confirmation's details.
 */
export interface AdminPostReturnsConfirmRequestReqSchema {
  /** Whether to send the customer a notification about the confirmation. */
  no_notification?: boolean;
}
