/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The campaign's budget.
 */
export type AdminPostCampaignsIdBodyAllOfBudget = {
  /** The campaign budget's limit. */
  limit: number;
};
