/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The inventory item's details.
 */
export type AdminProductVariantInventoryBatchResponseUpdatedOneOfItemInventoryService = {
  /** The ID of the inventory item. */
  inventory_item_id: string;
};
