/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostDraftOrdersBodyAllOfItemsItemMetadata } from './adminPostDraftOrdersBodyAllOfItemsItemMetadata';
import type { AdminPostDraftOrdersBodyAllOfItemsItemUnitPrice } from './adminPostDraftOrdersBodyAllOfItemsItemUnitPrice';

/**
 * The item's details.
 */
export type AdminPostDraftOrdersBodyAllOfItemsItem = {
  /** The item's barcode. */
  barcode: string;
  /** The item's metadata. */
  metadata: AdminPostDraftOrdersBodyAllOfItemsItemMetadata;
  /** The item's ordered quantity. */
  quantity: number;
  /** The item's SKU. */
  sku: string;
  /** The item's title. */
  title: string;
  unit_price: AdminPostDraftOrdersBodyAllOfItemsItemUnitPrice;
  /** The ID of the associated product variant. */
  variant_id: string;
};
