/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminTaxRate } from './adminTaxRate';

/**
 * The paginated list of tax rates.
 */
export type AdminGetTaxRates200AllOfTwo = {
  /** The tax rate's tax rates. */
  tax_rates: AdminTaxRate[];
};
