/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostExchangesAddItemsReqSchemaItemsItem } from './adminPostExchangesAddItemsReqSchemaItemsItem';

/**
 * The details of outbound items.
 */
export interface AdminPostExchangesAddItemsReqSchema {
  /** The details of outbound items. */
  items?: AdminPostExchangesAddItemsReqSchemaItemsItem[];
}
