/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A category's details.
 */
export type AdminCreateProductCategoriesItem = {
  /** The category's ID. */
  id: string;
};
