/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPostShippingOptionsIdBodyPricesItemOneOf } from './adminPostShippingOptionsIdBodyPricesItemOneOf';
import type { AdminPostShippingOptionsIdBodyPricesItemOneOfTwo } from './adminPostShippingOptionsIdBodyPricesItemOneOfTwo';

export type AdminPostShippingOptionsIdBodyPricesItem = AdminPostShippingOptionsIdBodyPricesItemOneOf | AdminPostShippingOptionsIdBodyPricesItemOneOfTwo;
