/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The version changes of the item.
 */
export type AdminOrderItemHistoryVersion = {
  /** The original version. */
  from: number;
  /** The new version. */
  to: number;
};
