/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminFulfillmentProviderOption } from './adminFulfillmentProviderOption';

/**
 * The paginated list of fulfillment options.
 */
export interface AdminFulfillmentProviderOptionsListResponse {
  /** The total number of items. */
  count: number;
  /** The list of fulfillment options. */
  fulfillment_options: AdminFulfillmentProviderOption[];
  /** The maximum number of items returned. */
  limit: number;
  /** The number of items skipped before retrieving the returned items. */
  offset: number;
}
