/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUser } from './adminUser';

/**
 * The authenticated user's details.
 */
export interface AuthAdminSessionResponse {
  /** The logged-in user. */
  user: AdminUser;
}
