/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreCustomer } from './storeCustomer';

/**
 * The authenticated customer's details.
 */
export interface AuthStoreSessionResponse {
  /** The logged-in customer. */
  user: StoreCustomer;
}
