/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseOrderShippingDetailShippingMethod } from './baseOrderShippingDetailShippingMethod';

/**
 * Details of changes to a shipping method.
 */
export interface BaseOrderShippingDetail {
  /** The ID of the associated claim. */
  claim_id?: string;
  /** The date the shipping method change was created. */
  created_at: string;
  /** The ID of the associated exchange. */
  exchange_id?: string;
  /** The ID of the new changes to the shipping method. */
  id: string;
  /** The ID of the associated return. */
  return_id?: string;
  shipping_method: BaseOrderShippingDetailShippingMethod;
  /** The ID of the shipping method. */
  shipping_method_id: string;
  /** The date the shipping method change was updated. */
  updated_at: string;
}
