/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BasePaymentSessionContext } from './basePaymentSessionContext';
import type { BasePaymentSessionData } from './basePaymentSessionData';
import type { BasePayment } from './basePayment';
import type { BasePaymentSessionPaymentCollection } from './basePaymentSessionPaymentCollection';
import type { BasePaymentSessionStatus } from './basePaymentSessionStatus';

/**
 * The payment session's details.
 */
export interface BasePaymentSession {
  /** The payment session's amount. */
  amount: number;
  /** The date the payment session was authorized. */
  authorized_at?: string;
  /** The context around the payment, such as the customer's details. */
  context?: BasePaymentSessionContext;
  /** The payment session's currency code. */
  currency_code: string;
  /** The payment session's data, useful for the payment provider processing the payment. */
  data: BasePaymentSessionData;
  /** The payment session's ID. */
  id: string;
  payment?: BasePayment;
  payment_collection?: BasePaymentSessionPaymentCollection;
  /** The ID of the payment provider processing this session. */
  provider_id: string;
  /** The payment session's status. */
  status: BasePaymentSessionStatus;
}
