/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseCollectionMetadata } from './baseCollectionMetadata';
import type { BaseCollectionProductsItem } from './baseCollectionProductsItem';

/**
 * The product collection's details.
 */
export interface BaseCollection {
  /** The collection's creation date. */
  created_at: string;
  /** The collection's deletion date. */
  deleted_at: string;
  /** The collection's handle. */
  handle: string;
  /** The collection's ID. */
  id: string;
  /** The collection's metadata, used to store custom key-value pairs. */
  metadata: BaseCollectionMetadata;
  /** The collection's products. */
  products?: BaseCollectionProductsItem[];
  /** The collection's title. */
  title: string;
  /** The collection's update date. */
  updated_at: string;
}
