/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The fulfillment provider's details.
 */
export interface BaseFulfillmentProvider {
  /** The provider's ID. */
  id: string;
  /** Whether the provider is enabled. */
  is_enabled: boolean;
}
