/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The payment session's status.
 */
export type BasePaymentSessionStatus = typeof BasePaymentSessionStatus[keyof typeof BasePaymentSessionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BasePaymentSessionStatus = {
  authorized: 'authorized',
  captured: 'captured',
  canceled: 'canceled',
  pending: 'pending',
  requires_more: 'requires_more',
  error: 'error',
} as const;
