/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseProductOptionMetadata } from './baseProductOptionMetadata';
import type { BaseProductOptionProduct } from './baseProductOptionProduct';
import type { BaseProductOptionValue } from './baseProductOptionValue';

/**
 * The product option's details.
 */
export interface BaseProductOption {
  /** The date the product option was created. */
  created_at?: string;
  /** The date the product option was deleted. */
  deleted_at?: string;
  /** The product option's ID. */
  id: string;
  /** The product option's metadata, can hold custom key-value pairs. */
  metadata?: BaseProductOptionMetadata;
  product?: BaseProductOptionProduct;
  /** The ID of the product this option belongs to. */
  product_id?: string;
  /** The product option's title. */
  title: string;
  /** The date the product option was updated. */
  updated_at?: string;
  /** The product option's values. */
  values?: BaseProductOptionValue[];
}
