/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The values of the item variant's options.
 */
export type BaseOrderLineItemVariantOptionValues = { [key: string]: unknown };
