/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseCapturePayment } from './baseCapturePayment';

/**
 * The details of a captured payment.
 */
export interface BaseCapture {
  /** The captured amount. */
  amount: number;
  /** The date the capture was created. */
  created_at: string;
  /** The ID of the user that captured the payment. */
  created_by?: string;
  /** The payment capture's ID. */
  id: string;
  payment: BaseCapturePayment;
}
