/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The rule value's details.
 */
export interface BasePromotionRuleValue {
  /** The value's ID. */
  id: string;
  /** The value. */
  value?: string;
}
