/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseShippingMethodAdjustmentShippingMethod } from './baseShippingMethodAdjustmentShippingMethod';

/**
 * The adjustment's details.
 */
export interface BaseShippingMethodAdjustment {
  /** The adjustment's amount. */
  amount: number;
  /** The ID of the associated cart. */
  cart_id: string;
  /** The adjustment's code. */
  code?: string;
  /** The date the adjustment was created. */
  created_at: string;
  /** The adjustment's description. */
  description?: string;
  /** The adjustment's ID. */
  id: string;
  /** The ID of the promotion applied by this adjustment. */
  promotion_id?: string;
  /** The adjustment's provider ID. */
  provider_id?: string;
  shipping_method: BaseShippingMethodAdjustmentShippingMethod;
  /** The ID of the shipping method the adjustment is applied on. */
  shipping_method_id: string;
  /** The date the adjustment was updated. */
  updated_at: string;
}
