/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseOrderTransactionMetadata } from './baseOrderTransactionMetadata';
import type { BaseOrderTransactionReference } from './baseOrderTransactionReference';

/**
 * An order transaction's details.
 */
export interface BaseOrderTransaction {
  /** The transaction's amount. */
  amount: number;
  /** The date that the transaction was created. */
  created_at: string;
  /** The transaction's currency code. */
  currency_code: string;
  /** The transaction's ID. */
  id: string;
  /** The transaction's metadata, can hold custom key-value pairs. */
  metadata: BaseOrderTransactionMetadata;
  /** The ID of the order this transaction belongs to. */
  order_id: string;
  /** The name of a table that this transaction references. If this transaction is for captured payment, its value is `capture`. If this transaction is for refunded payment, its value is `refund`. */
  reference: BaseOrderTransactionReference;
  /** The ID of the referenced record in the referenced table. */
  reference_id: string;
  /** The date that the transaction was updated. */
  updated_at: string;
}
