/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseExchangeItemMetadata } from './baseExchangeItemMetadata';

/**
 * The item's details.
 */
export interface BaseExchangeItem {
  /** The date the item was created. */
  created_at: string;
  /** The ID of the exchange this item belongs to. */
  exchange_id: string;
  /** The item's ID. */
  id: string;
  /** The ID of the item in the order. */
  item_id: string;
  /** The item's metadata, can hold custom key-value pairs. */
  metadata?: BaseExchangeItemMetadata;
  /** The ID of the order this item belongs to. */
  order_id: string;
  /** The item's quantity. */
  quantity: number;
  /** The date the item was updated. */
  updated_at: string;
}
