/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateShippingOptionPriceWithCurrency {
  /** The amount of the price. */
  amount: number;
  /** The currency code for the price. */
  currency_code: string;
}
