/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAddressMetadata } from './createAddressMetadata';

/**
 * The address to create.
 */
export interface CreateAddress {
  /** The address's first line. */
  address_1?: string;
  /** The address's second line. */
  address_2?: string;
  /** The address's city. */
  city?: string;
  /** The address's company. */
  company?: string;
  /** The address's country code. */
  country_code?: string;
  /** The ID of the customer this address belongs to. */
  customer_id?: string;
  /** The address's first name. */
  first_name?: string;
  /** The address's last name. */
  last_name?: string;
  /** The address's metadata, can hold custom key-value pairs. */
  metadata?: CreateAddressMetadata;
  /** The address's phone. */
  phone?: string;
  /** The address's postal code. */
  postal_code?: string;
  /** The address's province. */
  province?: string;
}
