/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorCode } from './errorCode';
import type { ErrorType } from './errorType';

export interface Error {
  /** A slug code to indicate the type of the error. */
  code?: ErrorCode;
  /** Description of the error that occurred. */
  message?: string;
  /** A slug indicating the type of the error. */
  type?: ErrorType;
}
