/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { GeoZoneCountryType } from './geoZoneCountryType';

export interface GeoZoneCountry {
  /** The country code of the geo zone. */
  country_code: string;
  /** The type of the geo zone. */
  type: GeoZoneCountryType;
}
