/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { GeoZoneProvinceType } from './geoZoneProvinceType';

export interface GeoZoneProvince {
  /** The country code of the geo zone. */
  country_code: string;
  /** The province code of the geo zone. */
  province_code: string;
  /** The type of the geo zone. */
  type: GeoZoneProvinceType;
}
