/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of the geo zone.
 */
export type GeoZoneCountryType = typeof GeoZoneCountryType[keyof typeof GeoZoneCountryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GeoZoneCountryType = {
  country: 'country',
} as const;
