/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of the geo zone.
 */
export type GeoZoneZipType = typeof GeoZoneZipType[keyof typeof GeoZoneZipType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GeoZoneZipType = {
  zip: 'zip',
} as const;
