/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * User does not exist or incorrect credentials
 */
export type IncorrectCredentialsResponse = string;
