/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { OrderCreditLineMetadata } from './orderCreditLineMetadata';
import type { OrderCreditLineOrder } from './orderCreditLineOrder';

/**
 * The credit line's details.
 */
export interface OrderCreditLine {
  /** The date the credit line was created. */
  created_at: string;
  /** The credit line's ID. */
  id: string;
  /** The credit line's metadata, can hold custom key-value pairs. */
  metadata: OrderCreditLineMetadata;
  order: OrderCreditLineOrder;
  /** The ID of the associated order. */
  order_id: string;
  /** The table that this credit line references. For example, `payment_collection`. */
  reference: string;
  /** The ID of the record in the referenced table. For example, `paycol_123`. */
  reference_id: string;
  /** The date the credit line was updated. */
  updated_at: string;
}
