/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The claim's type.
 */
export type OrderClaimType = typeof OrderClaimType[keyof typeof OrderClaimType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderClaimType = {
  replace: 'replace',
  refund: 'refund',
} as const;
