/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The name of a table that this transaction references. If this transaction is for captured payment, its value is `capture`. If this transaction is for refunded payment, its value is `refund`.
 */
export type OrderTransactionReference = typeof OrderTransactionReference[keyof typeof OrderTransactionReference];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderTransactionReference = {
  capture: 'capture',
  refund: 'refund',
} as const;
