/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { OrderLineItemAdjustmentItem } from './orderLineItemAdjustmentItem';

/**
 * The line item adjustment's details.
 */
export interface OrderLineItemAdjustment {
  /** The adjustment's amount. */
  amount: number;
  /** The adjustment's code. */
  code?: string;
  /** The date the adjustment was created. */
  created_at: string;
  /** The adjustment's description. */
  description?: string;
  /** The adjustment's ID. */
  id: string;
  item: OrderLineItemAdjustmentItem;
  /** The ID of the item this adjustment is for. */
  item_id: string;
  /** The ID of the associated order. */
  order_id: string;
  /** The ID of the promotion applied by this adjustment. */
  promotion_id?: string;
  /** The adjustment's provider ID. */
  provider_id?: string;
  /** The date the adjustment was updated. */
  updated_at: string;
}
