/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminRefundReason } from './adminRefundReason';

/**
 * The refund reason's details.
 */
export interface RefundReasonResponse {
  refund_reason: AdminRefundReason;
}
