/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreReturnItem } from './storeReturnItem';

/**
 * The return's details.
 */
export interface StoreReturn {
  /** The date the return was updated. */
  canceled_at: string;
  /** The ID of the associated claim. */
  claim_id?: string;
  /** The date the return was created. */
  created_at: string;
  /** The return's display ID. */
  display_id: number;
  /** The ID of the associated exchange. */
  exchange_id?: string;
  /** The return's ID. */
  id: string;
  /** The return's items. */
  items: StoreReturnItem[];
  /** The ID of the location the items are returned to. */
  location_id?: string;
  /** The ID of the order this return is created for. */
  order_id: string;
  /** The date the return was received. */
  received_at: string;
  /** The return's refunded amount. */
  refund_amount?: number;
  /** The return's status. */
  status?: string;
}
