/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The shipping option type's details.
 */
export type StoreCartShippingOptionType = {
  /** The type's code. */
  code: string;
  /** The type's description. */
  description: string;
  /** The type's ID. */
  id: string;
  /** The type's label. */
  label: string;
};
