/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderLineItemAdjustmentsItemAllOfTwosevenItem } from './storeOrderLineItemAdjustmentsItemAllOfTwosevenItem';

/**
 * The adjustment's adjustments.
 */
export type StoreOrderLineItemAdjustmentsItemAllOfTwoseven = {
  /** The adjustment's item. */
  item: StoreOrderLineItemAdjustmentsItemAllOfTwosevenItem;
};
