/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodTaxLinesItemAllOfThreeShippingMethod } from './storeOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodTaxLinesItemAllOfThreeShippingMethod';

/**
 * The tax line's tax lines.
 */
export type StoreOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodTaxLinesItemAllOfThree = {
  /** The tax line's shipping method. */
  shipping_method: StoreOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodTaxLinesItemAllOfThreeShippingMethod;
};
