/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreCartShippingMethodAdjustmentsItemAllOfThreeShippingMethod } from './storeCartShippingMethodAdjustmentsItemAllOfThreeShippingMethod';

/**
 * The adjustment's details.
 */
export type StoreCartShippingMethodAdjustmentsItemAllOfThree = {
  /** The details of the method that the adjustment belongs to. */
  shipping_method: StoreCartShippingMethodAdjustmentsItemAllOfThreeShippingMethod;
};
