/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreCartLineItemAdjustmentsItemAllOf } from './storeCartLineItemAdjustmentsItemAllOf';
import type { StoreCartLineItemAdjustmentsItemAllOfThree } from './storeCartLineItemAdjustmentsItemAllOfThree';

/**
 * The adjustment's details.
 */
export type StoreCartLineItemAdjustmentsItem = StoreCartLineItemAdjustmentsItemAllOf & StoreCartLineItemAdjustmentsItemAllOfThree;
