/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Filter by the variants' options.
 */
export type StoreGetProductsVariantsOptions = {
  /** The ID of the option to filter by. */
  option_id: string;
  /** Filter by a value of the option. */
  value: string;
};
