/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfShippingMethod } from './storeOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfShippingMethod';

/**
 * The shipping method's detail.
 */
export type StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOf = {
  /** The detail's claim id. */
  claim_id?: string;
  /** The detail's created at. */
  created_at: string;
  /** The detail's exchange id. */
  exchange_id?: string;
  /** The detail's ID. */
  id: string;
  /** The detail's return id. */
  return_id?: string;
  /** The detail's shipping method. */
  shipping_method: StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfShippingMethod;
  /** The detail's shipping method id. */
  shipping_method_id: string;
  /** The detail's updated at. */
  updated_at: string;
};
