/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreAddCartLineItemMetadata } from './storeAddCartLineItemMetadata';

/**
 * The details of the line item to add.
 */
export interface StoreAddCartLineItem {
  /** The item's metadata, can hold custom key-value pairs. */
  metadata?: StoreAddCartLineItemMetadata;
  /** The item's quantity. */
  quantity: number;
  /** The ID of the product variant to add to the cart. */
  variant_id: string;
}
