/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreCart } from './storeCart';
import type { StorePostCartsIdComplete200OneOfTwoError } from './storePostCartsIdComplete200OneOfTwoError';

/**
 * The details of why the cart completion failed.
 */
export type StorePostCartsIdComplete200OneOfTwo = {
  cart: StoreCart;
  /** The error's details. */
  error: StorePostCartsIdComplete200OneOfTwoError;
  /** The type of the returned object. In this case, the cart is returned because an error has occurred. */
  type: string;
};
