/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StorePriceRuleOperator } from './storePriceRuleOperator';

/**
 * The price rule's details.
 */
export interface StorePriceRule {
  /** The price rule's attribute. */
  attribute: string;
  /** The price rule's ID. */
  id: string;
  /** The price rule's operator. */
  operator: StorePriceRuleOperator;
  /** The price rule's value. */
  value: string;
}
