/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderShippingMethodDetailAllOfShippingMethod } from './storeOrderShippingMethodDetailAllOfShippingMethod';

/**
 * The shipping method's detail.
 */
export type StoreOrderShippingMethodDetailAllOf = {
  /** The detail's shipping method. */
  shipping_method: StoreOrderShippingMethodDetailAllOfShippingMethod;
};
