/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreReturnReason } from './storeReturnReason';

/**
 * The paginated list of return reasons.
 */
export type StoreGetReturnReasons200AllOfTwo = {
  /** The list of return reasons. */
  return_reasons: StoreReturnReason[];
};
