/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseOrderShippingDetail } from './baseOrderShippingDetail';
import type { StoreOrderShippingMethodDetailAllOf } from './storeOrderShippingMethodDetailAllOf';

/**
 * Details of changes to a shipping method.
 */
export type StoreOrderShippingMethodDetail = BaseOrderShippingDetail & StoreOrderShippingMethodDetailAllOf;
