/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreProductCategoriesItem } from './storeProductCategoriesItem';
import type { StoreCollection } from './storeCollection';
import type { StoreProductImage } from './storeProductImage';
import type { StoreProductMetadata } from './storeProductMetadata';
import type { StoreProductOption } from './storeProductOption';
import type { StoreProductStatus } from './storeProductStatus';
import type { StoreProductTag } from './storeProductTag';
import type { StoreProductType } from './storeProductType';
import type { StoreProductVariant } from './storeProductVariant';

/**
 * The product's details.
 */
export interface StoreProduct {
  /** The product's categories. */
  categories?: StoreProductCategoriesItem[];
  collection?: StoreCollection;
  /** The ID of the collection that the product belongs to. */
  collection_id: string;
  /** The date the product was created. */
  created_at: string;
  /** The date the product was deleted. */
  deleted_at: string;
  /** The product's description. */
  description: string;
  /** Whether the product can be discounted. */
  discountable: boolean;
  /** The ID of the product in an external service or system. */
  external_id: string;
  /** The product's handle. */
  handle: string;
  /** The product's height. */
  height: number;
  /** The product's HS code. */
  hs_code: string;
  /** The product's ID. */
  id: string;
  /** The product's images. */
  images: StoreProductImage[];
  /** Whether the product is a gift card. */
  is_giftcard: boolean;
  /** The product's length. */
  length: number;
  /** The product's material. */
  material: string;
  /** The product's metadata, can hold custom key-value pairs. */
  metadata?: StoreProductMetadata;
  /** The product's MID code. */
  mid_code: string;
  /** The product's options. */
  options: StoreProductOption[];
  /** The product's origin country. */
  origin_country: string;
  /** The product's status. */
  status: StoreProductStatus;
  /** The product's subtitle. */
  subtitle: string;
  /** The product's tags. */
  tags?: StoreProductTag[];
  /** The product's thumbnail URL. */
  thumbnail: string;
  /** The product's title. */
  title: string;
  type?: StoreProductType;
  /** The ID of the product's type. */
  type_id: string;
  /** The date the product was updated. */
  updated_at: string;
  /** The product's variants. */
  variants: StoreProductVariant[];
  /** The product's weight. */
  weight: number;
  /** The product's width. */
  width: number;
}
