/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfThreeShippingMethod } from './storeOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfThreeShippingMethod';

/**
 * The shipping method's detail.
 */
export type StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfThree = {
  /** The detail's shipping method. */
  shipping_method: StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfThreeShippingMethod;
};
