/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Holds custom key-value pairs.
 */
export type StorePostCustomersMeAddressesBodyMetadata = { [key: string]: unknown };
