/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodAdjustmentsItemAllOf } from './storeOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodAdjustmentsItemAllOf';
import type { StoreOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodAdjustmentsItemAllOfThree } from './storeOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodAdjustmentsItemAllOfThree';

export type StoreOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodAdjustmentsItem = StoreOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodAdjustmentsItemAllOf & StoreOrderShippingMethodAdjustmentsItemAllOfOneoneShippingMethodAdjustmentsItemAllOfThree;
