/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreInitializePaymentSessionContext } from './storeInitializePaymentSessionContext';
import type { StoreInitializePaymentSessionData } from './storeInitializePaymentSessionData';

/**
 * The payment session's details.
 */
export interface StoreInitializePaymentSession {
  /** The payment's context, such as the customer or address details. If the customer is logged-in, the customer `id` is set in the context under a `customer.id` property. */
  context?: StoreInitializePaymentSessionContext;
  /** Any data necessary for the payment provider to process the payment. */
  data?: StoreInitializePaymentSessionData;
  /** The ID of the payment provider the customer chose. */
  provider_id: string;
}
