/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOf } from './storeOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOf';
import type { StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfThree } from './storeOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfThree';

export type StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetail = StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOf & StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethodDetailAllOfThree;
