/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreDeleteCartsIdLineItemsLineId200AllOf } from './storeDeleteCartsIdLineItemsLineId200AllOf';
import type { StoreDeleteCartsIdLineItemsLineId200AllOfTwo } from './storeDeleteCartsIdLineItemsLineId200AllOfTwo';

/**
 * The deletion's details.
 */
export type StoreDeleteCartsIdLineItemsLineId200 = StoreDeleteCartsIdLineItemsLineId200AllOf & StoreDeleteCartsIdLineItemsLineId200AllOfTwo;
