/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreCartShippingOption } from './storeCartShippingOption';

/**
 * The shipping option's details.
 */
export interface StoreShippingOptionResponse {
  shipping_option: StoreCartShippingOption;
}
