/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

export type StoreGetProductsIdParams = {
/**
 * Comma-separated fields that should be included in the returned data. if a field is prefixed with `+` it will be added to the default fields, using `-` will remove it from the default fields. without prefix it will replace the entire default fields.
 */
fields?: string;
/**
 * The ID of the region the product is being viewed from. This is required if you're retrieving product variant prices with taxes.
 */
region_id?: string;
/**
 * The country code the product is being viewed from. This is required if you're retrieving product variant prices with taxes.
 */
country_code?: string;
/**
 * The province the product is being viewed from. This is useful to narrow down the tax context when calculating product variant prices with taxes.
 */
province?: string;
/**
 * The ID of the customer's cart. If set, the cart's region and shipping address's country code and province are used instead of the `region_id`, `country_code`, and `province` properties.
 */
cart_id?: string;
/**
 * Limit the number of items returned in the list.
 */
limit?: number;
/**
 * The number of items to skip when retrieving a list.
 */
offset?: number;
/**
 * The field to sort the data by. By default, the sort order is ascending. To change the order to descending, prefix the field name with `-`.
 */
order?: string;
};
