/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StorePaymentProvider } from './storePaymentProvider';

/**
 * The list of payment providers.
 */
export type StoreGetPaymentProviders200AllOfTwo = {
  /** The list of payment providers. */
  payment_providers: StorePaymentProvider[];
};
