/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StorePaymentCollection } from './storePaymentCollection';

/**
 * The payment collection's details.
 */
export interface StorePaymentCollectionResponse {
  payment_collection: StorePaymentCollection;
}
