/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The adjustment's item.
 */
export type StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemAdjustmentsItemAllOfThreeItem = { [key: string]: unknown };
