/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderLineItemAdjustmentsItemAllOf } from './storeOrderLineItemAdjustmentsItemAllOf';
import type { StoreOrderLineItemAdjustmentsItemAllOfTwoseven } from './storeOrderLineItemAdjustmentsItemAllOfTwoseven';

/**
 * The adjustment's details.
 */
export type StoreOrderLineItemAdjustmentsItem = StoreOrderLineItemAdjustmentsItemAllOf & StoreOrderLineItemAdjustmentsItemAllOfTwoseven;
