/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderLineItemTaxLinesItemAllOfTwosevenItemAdjustmentsItemAllOf } from './storeOrderLineItemTaxLinesItemAllOfTwosevenItemAdjustmentsItemAllOf';
import type { StoreOrderLineItemTaxLinesItemAllOfTwosevenItemAdjustmentsItemAllOfThree } from './storeOrderLineItemTaxLinesItemAllOfTwosevenItemAdjustmentsItemAllOfThree';

export type StoreOrderLineItemTaxLinesItemAllOfTwosevenItemAdjustmentsItem = StoreOrderLineItemTaxLinesItemAllOfTwosevenItemAdjustmentsItemAllOf & StoreOrderLineItemTaxLinesItemAllOfTwosevenItemAdjustmentsItemAllOfThree;
