/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreCartShippingMethodTaxLinesItemAllOfThreeShippingMethod } from './storeCartShippingMethodTaxLinesItemAllOfThreeShippingMethod';

/**
 * The tax line's details.
 */
export type StoreCartShippingMethodTaxLinesItemAllOfThree = {
  /** The details of the method that the tax line belongs to. */
  shipping_method: StoreCartShippingMethodTaxLinesItemAllOfThreeShippingMethod;
};
