/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemTaxLinesItemAllOfThreeItem } from './storeOrderLineItemAdjustmentsItemAllOfTwosevenItemTaxLinesItemAllOfThreeItem';

/**
 * The tax line's tax lines.
 */
export type StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemTaxLinesItemAllOfThree = {
  /** The tax line's item. */
  item: StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemTaxLinesItemAllOfThreeItem;
};
