/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreGetPaymentProviders200AllOf } from './storeGetPaymentProviders200AllOf';
import type { StoreGetPaymentProviders200AllOfTwo } from './storeGetPaymentProviders200AllOfTwo';

export type StoreGetPaymentProviders200 = StoreGetPaymentProviders200AllOf & StoreGetPaymentProviders200AllOfTwo;
