/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemAdjustmentsItemAllOfItem } from './storeOrderLineItemAdjustmentsItemAllOfTwosevenItemAdjustmentsItemAllOfItem';

/**
 * The adjustment's adjustments.
 */
export type StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemAdjustmentsItemAllOf = {
  /** The adjustment's amount. */
  amount: number;
  /** The adjustment's code. */
  code?: string;
  /** The adjustment's created at. */
  created_at: string;
  /** The adjustment's description. */
  description?: string;
  /** The adjustment's ID. */
  id: string;
  /** The adjustment's item. */
  item: StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemAdjustmentsItemAllOfItem;
  /** The adjustment's item id. */
  item_id: string;
  /** The adjustment's order id. */
  order_id: string;
  /** The adjustment's promotion id. */
  promotion_id?: string;
  /** The adjustment's provider id. */
  provider_id?: string;
  /** The adjustment's updated at. */
  updated_at: string;
};
