/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCartData } from './updateCartData';
import type { StorePostCartsIdBodyAllOf } from './storePostCartsIdBodyAllOf';

/**
 * The properties to update in the cart item.
 */
export type StorePostCartsIdBody = UpdateCartData & StorePostCartsIdBodyAllOf;
