/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The product's status.
 */
export type StoreOrderLineItemTaxLinesItemAllOfItemProductStatus = typeof StoreOrderLineItemTaxLinesItemAllOfItemProductStatus[keyof typeof StoreOrderLineItemTaxLinesItemAllOfItemProductStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreOrderLineItemTaxLinesItemAllOfItemProductStatus = {
  draft: 'draft',
  proposed: 'proposed',
  published: 'published',
  rejected: 'rejected',
} as const;
