/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The details of requesting the order transfer.
 */
export interface StoreRequestOrderTransfer {
  /** The transfer's description, which can be shown to the other customer receiving the request. */
  description?: string;
}
