/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreRegion } from './storeRegion';

/**
 * The paginated list of regions.
 */
export type StoreGetRegions200AllOfTwo = {
  /** The list of regions. */
  regions: StoreRegion[];
};
