/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Custom data that's useful for the fulfillment provider to calculate the price.
 */
export type StorePostShippingOptionsIdCalculateBodyData = { [key: string]: unknown };
