/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { BaseRegionCountry } from './baseRegionCountry';
import type { StoreRegionMetadata } from './storeRegionMetadata';
import type { AdminPaymentProvider } from './adminPaymentProvider';

/**
 * The region's details.
 */
export interface StoreRegion {
  /** Whether taxes are calculated automatically during checkout for carts that belong to this region. */
  automatic_taxes?: boolean;
  /** The region's countries. */
  countries?: BaseRegionCountry[];
  /** The date the region was created. */
  created_at?: string;
  /** The region's currency code. */
  currency_code: string;
  /** The region's ID. */
  id: string;
  /** The region's metadata, can hold custom key-value pairs. */
  metadata?: StoreRegionMetadata;
  /** The region's name. */
  name: string;
  /** The region's payment providers. */
  payment_providers?: AdminPaymentProvider[];
  /** The date the region was updated. */
  updated_at?: string;
}
