/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreGetProductCategoriesCreatedAtAndItem } from './storeGetProductCategoriesCreatedAtAndItem';
import type { StoreGetProductCategoriesCreatedAtEq } from './storeGetProductCategoriesCreatedAtEq';
import type { StoreGetProductCategoriesCreatedAtNot } from './storeGetProductCategoriesCreatedAtNot';
import type { StoreGetProductCategoriesCreatedAtOrItem } from './storeGetProductCategoriesCreatedAtOrItem';
import type { StoreGetProductCategoriesUpdatedAtAndItem } from './storeGetProductCategoriesUpdatedAtAndItem';
import type { StoreGetProductCategoriesUpdatedAtEq } from './storeGetProductCategoriesUpdatedAtEq';
import type { StoreGetProductCategoriesUpdatedAtNot } from './storeGetProductCategoriesUpdatedAtNot';
import type { StoreGetProductCategoriesUpdatedAtOrItem } from './storeGetProductCategoriesUpdatedAtOrItem';
import type { StoreGetProductCategoriesAndItem } from './storeGetProductCategoriesAndItem';
import type { StoreGetProductCategoriesOrItem } from './storeGetProductCategoriesOrItem';

export type StoreGetProductCategoriesParams = {
/**
 * Comma-separated fields that should be included in the returned data. if a field is prefixed with `+` it will be added to the default fields, using `-` will remove it from the default fields. without prefix it will replace the entire default fields.
 */
fields?: string;
/**
 * The number of items to skip when retrieving a list.
 */
offset?: number;
/**
 * Limit the number of items returned in the list.
 */
limit?: number;
/**
 * The field to sort the data by. By default, the sort order is ascending. To change the order to descending, prefix the field name with `-`.
 */
order?: string;
/**
 * Search term to filter the product category's properties.
 */
q?: string;
id?: string | string[];
description?: string | string[];
handle?: string | string[];
parent_category_id?: string | string[];
/**
 * Whether to retrieve the category's parent. When enabled, the parent category is set in the `parent_category` property.
 */
include_ancestors_tree?: boolean;
/**
 * Whether to retrieve a list of child categories. When enabled, the parent categories are added to the `category_children` property.
 */
include_descendants_tree?: boolean;
/**
 * Filter by the category's creation date.
 */
created_at?: {
  /** Join query parameters with an AND condition. Each object's content is the same type as the expected query parameters. */
  $and?: StoreGetProductCategoriesCreatedAtAndItem[];
  /** Filter arrays that contain all values of this parameter. */
  $contained?: string[];
  /** Filter arrays that contain some of the values of this parameter. */
  $contains?: string[];
  $eq?: StoreGetProductCategoriesCreatedAtEq;
  /** Filter by whether a value for this parameter exists (not `null`). */
  $exists?: boolean;
  /** Filter to apply on full-text properties. */
  $fulltext?: string;
  /** Filter by values greater than this parameter. Useful for numbers and dates only. */
  $gt?: string;
  /** Filter by values greater than or equal to this parameter. Useful for numbers and dates only. */
  $gte?: string;
  /** Apply a case-insensitive `like` filter. Useful for strings only. */
  $ilike?: string;
  /** Filter by values in this array. */
  $in?: string[];
  /** Apply a `like` filter. Useful for strings only. */
  $like?: string;
  /** Filter by values less than this parameter. Useful for numbers and dates only. */
  $lt?: string;
  /** Filter by values less than or equal to this parameter. Useful for numbers and dates only. */
  $lte?: string;
  /** Filter by values not equal to this parameter. */
  $ne?: string;
  /** Filter by values not in this array. */
  $nin?: string[];
  $not?: StoreGetProductCategoriesCreatedAtNot;
  /** Join query parameters with an OR condition. Each object's content is the same type as the expected query parameters. */
  $or?: StoreGetProductCategoriesCreatedAtOrItem[];
  /** Filter arrays that have overlapping values with this parameter. */
  $overlap?: string[];
  /** Apply a regex filter. Useful for strings only. */
  $re?: string;
};
/**
 * Filter by the category's update date.
 */
updated_at?: {
  /** Join query parameters with an AND condition. Each object's content is the same type as the expected query parameters. */
  $and?: StoreGetProductCategoriesUpdatedAtAndItem[];
  /** Filter arrays that contain all values of this parameter. */
  $contained?: string[];
  /** Filter arrays that contain some of the values of this parameter. */
  $contains?: string[];
  $eq?: StoreGetProductCategoriesUpdatedAtEq;
  /** Filter by whether a value for this parameter exists (not `null`). */
  $exists?: boolean;
  /** Filter to apply on full-text properties. */
  $fulltext?: string;
  /** Filter by values greater than this parameter. Useful for numbers and dates only. */
  $gt?: string;
  /** Filter by values greater than or equal to this parameter. Useful for numbers and dates only. */
  $gte?: string;
  /** Apply a case-insensitive `like` filter. Useful for strings only. */
  $ilike?: string;
  /** Filter by values in this array. */
  $in?: string[];
  /** Apply a `like` filter. Useful for strings only. */
  $like?: string;
  /** Filter by values less than this parameter. Useful for numbers and dates only. */
  $lt?: string;
  /** Filter by values less than or equal to this parameter. Useful for numbers and dates only. */
  $lte?: string;
  /** Filter by values not equal to this parameter. */
  $ne?: string;
  /** Filter by values not in this array. */
  $nin?: string[];
  $not?: StoreGetProductCategoriesUpdatedAtNot;
  /** Join query parameters with an OR condition. Each object's content is the same type as the expected query parameters. */
  $or?: StoreGetProductCategoriesUpdatedAtOrItem[];
  /** Filter arrays that have overlapping values with this parameter. */
  $overlap?: string[];
  /** Apply a regex filter. Useful for strings only. */
  $re?: string;
};
$and?: StoreGetProductCategoriesAndItem[];
$or?: StoreGetProductCategoriesOrItem[];
name?: string | string[];
};
