/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreReturnReasonMetadata } from './storeReturnReasonMetadata';

/**
 * The return reason's details.
 */
export interface StoreReturnReason {
  /** The date the return reason was created. */
  created_at: string;
  /** The return reason's description. */
  description?: string;
  /** The return reason's ID. */
  id: string;
  /** The return reason's label. */
  label: string;
  /** The return reason's metadata, can hold custom key-value pairs. */
  metadata?: StoreReturnReasonMetadata;
  /** The date the return reason was updated. */
  updated_at: string;
  /** The return reason's value. */
  value: string;
}
