/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The input data necessary for authentication with the specified auth provider. For example, for email-pass authentication, pass `email` and `password` properties.
 */
export type StorePostActorTypeAuthProviderUpdateBody = { [key: string]: unknown };
