/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreCalculatedPriceCalculatedPrice } from './storeCalculatedPriceCalculatedPrice';
import type { StoreCalculatedPriceOriginalPrice } from './storeCalculatedPriceOriginalPrice';

/**
 * The shipping option's calculated price.
 */
export interface StoreCalculatedPrice {
  /** The amount of the calculated price, or `null` if there isn't a calculated price. This is the amount shown to the customer. */
  calculated_amount: number;
  /** The `calculated_amount` with taxes applied. */
  calculated_amount_with_tax?: number;
  /** The `calculated_amount` without taxes applied. */
  calculated_amount_without_tax?: number;
  /** The calculated price's details. */
  calculated_price?: StoreCalculatedPriceCalculatedPrice;
  /** The currency code of the calculated price, or `null` if there isn't a calculated price. */
  currency_code: string;
  /** The ID of the price set from which the price was selected. */
  id: string;
  /** Whether the calculated price belongs to a price list. */
  is_calculated_price_price_list?: boolean;
  /** Whether the calculated price is tax inclusive. */
  is_calculated_price_tax_inclusive?: boolean;
  /** Whether the original price belongs to a price list. */
  is_original_price_price_list?: boolean;
  /** Whether the original price is tax inclusive. */
  is_original_price_tax_inclusive?: boolean;
  /** The amount of the original price, or `null` if there isn't an original price. This amount is useful to compare with the `calculated_amount`, such as to check for discounted value. */
  original_amount: number;
  /** The origin price's details. */
  original_price?: StoreCalculatedPriceOriginalPrice;
}
