/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

export type StorePostActorTypeAuthProviderUpdateParams = {
/**
 * The reset password token received using the Get Reset Password API route.
 */
token: string;
};
