/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreCollection } from './storeCollection';

/**
 * The paginated list of collections.
 */
export type StoreGetCollections200AllOfTwo = {
  /** The collection's collections. */
  collections: StoreCollection[];
};
