/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreCollectionMetadata } from './storeCollectionMetadata';
import type { StoreCollectionProductsItem } from './storeCollectionProductsItem';

/**
 * The collection's details.
 */
export interface StoreCollection {
  /** The date the collection was created. */
  created_at: string;
  /** The date the collection was deleted. */
  deleted_at: string;
  /** The collection's handle. */
  handle: string;
  /** The collection's ID. */
  id: string;
  /** The collection's metadata, can hold custom key-value pairs. */
  metadata: StoreCollectionMetadata;
  /** The collection's products. */
  products?: StoreCollectionProductsItem[];
  /** The collection's title. */
  title: string;
  /** The date the collection was updated. */
  updated_at: string;
}
