/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemAdjustmentsItemAllOfThreeItem } from './storeOrderLineItemAdjustmentsItemAllOfTwosevenItemAdjustmentsItemAllOfThreeItem';

/**
 * The adjustment's adjustments.
 */
export type StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemAdjustmentsItemAllOfThree = {
  /** The adjustment's item. */
  item: StoreOrderLineItemAdjustmentsItemAllOfTwosevenItemAdjustmentsItemAllOfThreeItem;
};
