/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The customer's identifier for the selected auth provider. For example, for the `emailpass` auth provider, the value is the customer's email.
 */
export type StorePostActorTypeAuthProviderResetPasswordBody = { [key: string]: unknown };
