/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Data useful for the fulfillment provider handling it. This is taken from the associated shipping option.
 */
export type StoreOrderFulfillmentData = { [key: string]: unknown };
