/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The error's details.
 */
export type StorePostCartsIdComplete200OneOfTwoError = {
  /** The error's message. */
  message: string;
  /** The error's name. */
  name: string;
  /** The error's type. Can be a [MedusaError type](https://docs.medusajs.com/v2/advanced-development/api-routes/errors#medusaerror-types) or `payment_authorization_error` or `payment_requires_more_error` for payment-related errors.
 */
  type: string;
};
