/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderLineItemTaxLinesItemAllOfItemDetailItem } from './storeOrderLineItemTaxLinesItemAllOfItemDetailItem';
import type { StoreOrderLineItemTaxLinesItemAllOfItemDetailMetadata } from './storeOrderLineItemTaxLinesItemAllOfItemDetailMetadata';

/**
 * The item's detail.
 */
export type StoreOrderLineItemTaxLinesItemAllOfItemDetail = {
  /** The detail's created at. */
  created_at: string;
  /** The detail's delivered quantity. */
  delivered_quantity: number;
  /** The detail's fulfilled quantity. */
  fulfilled_quantity: number;
  /** The detail's ID. */
  id: string;
  /** The detail's item. */
  item: StoreOrderLineItemTaxLinesItemAllOfItemDetailItem;
  /** The detail's item id. */
  item_id: string;
  /** The detail's metadata. */
  metadata: StoreOrderLineItemTaxLinesItemAllOfItemDetailMetadata;
  /** The detail's quantity. */
  quantity: number;
  /** The detail's return dismissed quantity. */
  return_dismissed_quantity: number;
  /** The detail's return received quantity. */
  return_received_quantity: number;
  /** The detail's return requested quantity. */
  return_requested_quantity: number;
  /** The detail's shipped quantity. */
  shipped_quantity: number;
  /** The detail's updated at. */
  updated_at: string;
  /** The detail's written off quantity. */
  written_off_quantity: number;
};
