/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethod } from './storeOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethod';

/**
 * The tax line's tax lines.
 */
export type StoreOrderShippingMethodTaxLinesItemAllOfOneone = {
  /** The tax line's shipping method. */
  shipping_method: StoreOrderShippingMethodTaxLinesItemAllOfOneoneShippingMethod;
};
