/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreGetCollections200AllOf } from './storeGetCollections200AllOf';
import type { StoreGetCollections200AllOfTwo } from './storeGetCollections200AllOfTwo';

export type StoreGetCollections200 = StoreGetCollections200AllOf & StoreGetCollections200AllOfTwo;
