/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderLineItemTaxLinesItemAllOfTwosevenItemDetailAllOf } from './storeOrderLineItemTaxLinesItemAllOfTwosevenItemDetailAllOf';
import type { StoreOrderLineItemTaxLinesItemAllOfTwosevenItemDetailAllOfFour } from './storeOrderLineItemTaxLinesItemAllOfTwosevenItemDetailAllOfFour';

export type StoreOrderLineItemTaxLinesItemAllOfTwosevenItemDetail = StoreOrderLineItemTaxLinesItemAllOfTwosevenItemDetailAllOf & StoreOrderLineItemTaxLinesItemAllOfTwosevenItemDetailAllOfFour;
