/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreOrderLineItemDetailAllOfItemTaxLinesItemAllOfThreeItem } from './storeOrderLineItemDetailAllOfItemTaxLinesItemAllOfThreeItem';

/**
 * The tax line's tax lines.
 */
export type StoreOrderLineItemDetailAllOfItemTaxLinesItemAllOfThree = {
  /** The tax line's item. */
  item: StoreOrderLineItemDetailAllOfItemTaxLinesItemAllOfThreeItem;
};
