/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { UpsertStockLocationAddress } from './upsertStockLocationAddress';
import type { VendorUpdateStockLocationMetadata } from './vendorUpdateStockLocationMetadata';

export interface VendorUpdateStockLocation {
  address?: UpsertStockLocationAddress;
  /**
   * ID of an existing address to use
   * @nullable
   */
  address_id?: string | null;
  /**
   * Additional metadata
   * @nullable
   */
  metadata?: VendorUpdateStockLocationMetadata;
  /** Name of the stock location */
  name?: string;
}
