/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

export type VendorListMembersParams = {
/**
 * The number of items to return. Default 50.
 */
limit?: number;
/**
 * The number of items to skip before starting the response. Default 0.
 */
offset?: number;
/**
 * Comma-separated fields that should be included in the returned data.
 */
fields?: string;
/**
 * Comma-separated relations that should be expanded in the returned data.
 */
expand?: string;
/**
 * Field used to order the results.
 */
order?: string;
};
