/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorPayoutAccount } from './vendorPayoutAccount';

export type VendorCreateOnboarding200 = {
  payout_account?: VendorPayoutAccount;
};
