/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorListOrdersStatusOneOf } from './vendorListOrdersStatusOneOf';

export type VendorListOrdersParams = {
/**
 * The number of items to skip before starting to collect the result set.
 */
offset?: number;
/**
 * The number of items to return.
 */
limit?: number;
/**
 * Comma-separated fields to include in the response.
 */
fields?: string;
/**
 * The order of the returned items.
 */
order?: string;
/**
 * Filter by created at date range
 */
created_at?: { [key: string]: unknown };
/**
 * Filter by order status
 */
status?: string | string[] | VendorListOrdersStatusOneOf;
/**
 * Filter by fulfillment status
 */
fulfillment_status?: string;
/**
 * Filter by payment status
 */
payment_status?: string;
/**
 * Search query for filtering orders
 */
q?: string;
};
