/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorMember } from './vendorMember';

export type VendorListMembers200 = {
  /** The total number of items available */
  count?: number;
  /** The number of items per page */
  limit?: number;
  members?: VendorMember[];
  /** The number of items skipped before these items */
  offset?: number;
};
