/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

export interface VendorUpdateMember {
  /**
   * The member's biography.
   * @nullable
   */
  bio?: string | null;
  /** The name of the member. */
  name?: string;
  /**
   * The member's phone number.
   * @nullable
   */
  phone?: string | null;
  /**
   * URL to the member's photo.
   * @nullable
   */
  photo?: string | null;
}
