/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorProductCollectionMetadata } from './vendorProductCollectionMetadata';

/**
 * A product collection object with its properties
 */
export interface VendorProductCollection {
  /** The date with timezone at which the resource was created. */
  created_at: string;
  /**
   * The date with timezone at which the resource was deleted.
   * @nullable
   */
  deleted_at?: string | null;
  /** The handle of the product collection. */
  handle?: string;
  /** The unique identifier of the product collection. */
  id: string;
  /** An optional key-value map with additional details. */
  metadata?: VendorProductCollectionMetadata;
  /** The title of the product collection. */
  title: string;
  /** The date with timezone at which the resource was last updated. */
  updated_at: string;
}
