/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorCreateOnboardingContext } from './vendorCreateOnboardingContext';

export interface VendorCreateOnboarding {
  /**
   * Additional data needed by the payment provider to create onboarding.
   * @nullable
   */
  context?: VendorCreateOnboardingContext;
}
