/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { GeoZoneCountry } from './geoZoneCountry';
import type { GeoZoneProvince } from './geoZoneProvince';
import type { GeoZoneCity } from './geoZoneCity';
import type { GeoZoneZip } from './geoZoneZip';

export type VendorCreateServiceZoneGeoZonesItem = GeoZoneCountry | GeoZoneProvince | GeoZoneCity | GeoZoneZip;
