/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorProductOptionValueMetadata } from './vendorProductOptionValueMetadata';

/**
 * A product option value object with its properties
 */
export interface VendorProductOptionValue {
  /** The date with timezone at which the resource was created. */
  created_at: string;
  /**
   * The date with timezone at which the resource was deleted.
   * @nullable
   */
  deleted_at?: string | null;
  /** The unique identifier of the product option value. */
  id: string;
  /** An optional key-value map with additional details. */
  metadata?: VendorProductOptionValueMetadata;
  /** The date with timezone at which the resource was last updated. */
  updated_at: string;
  /** The value of the product option value. */
  value: string;
}
