/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * An order set object with its properties
 */
export interface VendorOrderSet {
  /** The date with timezone at which the resource was created. */
  created_at: string;
  /** The display ID of the order set. */
  display_id: number;
  /** The unique identifier of the order set. */
  id: string;
  /** The date with timezone at which the resource was last updated. */
  updated_at: string;
}
