/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorCreateFulfillmentItemsItem } from './vendorCreateFulfillmentItemsItem';

export interface VendorCreateFulfillment {
  /** Sales channels to associate the product with. */
  items?: VendorCreateFulfillmentItemsItem[];
  /** The number of items to skip before starting the response. Default 0. */
  location_id?: string;
  /** The number of items to return. Default 50. */
  requires_shipping?: boolean;
}
