/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { GeoZoneZip } from './geoZoneZip';
import type { VendorUpdateServiceZoneGeoZonesItemOneOfSevenAllOf } from './vendorUpdateServiceZoneGeoZonesItemOneOfSevenAllOf';

export type VendorUpdateServiceZoneGeoZonesItemOneOfSeven = GeoZoneZip & VendorUpdateServiceZoneGeoZonesItemOneOfSevenAllOf;
