/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorPayoutData } from './vendorPayoutData';
import type { VendorPayoutAccount } from './vendorPayoutAccount';

/**
 * A payout object with its properties
 */
export interface VendorPayout {
  /** The amount of the payout. */
  amount: number;
  /** The date with timezone at which the resource was created. */
  created_at?: string;
  /** The currency code of the payout. */
  currency_code: string;
  /**
   * Additional data stored with the payout.
   * @nullable
   */
  data?: VendorPayoutData;
  /** The unique identifier of the payout. */
  id: string;
  /** The payout account this payout belongs to. */
  payout_account?: VendorPayoutAccount;
  /** The date with timezone at which the resource was last updated. */
  updated_at?: string;
}
