/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorOrderAddress } from './vendorOrderAddress';
import type { VendorOrderDetailsFulfillmentStatus } from './vendorOrderDetailsFulfillmentStatus';
import type { VendorOrderFulfillment } from './vendorOrderFulfillment';
import type { VendorOrderLineItem } from './vendorOrderLineItem';
import type { VendorOrderDetailsMetadata } from './vendorOrderDetailsMetadata';
import type { VendorOrderPaymentCollection } from './vendorOrderPaymentCollection';
import type { VendorOrderDetailsPaymentStatus } from './vendorOrderDetailsPaymentStatus';
import type { VendorOrderShippingMethod } from './vendorOrderShippingMethod';
import type { VendorOrderSummary } from './vendorOrderSummary';

/**
 * The order's details.
 */
export interface VendorOrderDetails {
  billing_address?: VendorOrderAddress;
  /** The date the order was created. */
  created_at?: string;
  /** The order's currency code. */
  currency_code?: string;
  /** The ID of the customer that placed the order. */
  customer_id?: string;
  /** The tax total of order's discount or promotion. */
  discount_tax_total?: number;
  /** The order's discount or promotions total. */
  discount_total?: number;
  /** The order's display ID. */
  display_id?: number;
  /** The email of the customer that placed the order. */
  email?: string;
  /** The order's fulfillment status. */
  fulfillment_status?: VendorOrderDetailsFulfillmentStatus;
  /** The order's fulfillments. */
  fulfillments?: VendorOrderFulfillment[];
  /** The tax total of the order's gift card. */
  gift_card_tax_total?: number;
  /** The order's gift card total. */
  gift_card_total?: number;
  /** The order's ID. */
  id?: string;
  /** The total of the order's items excluding taxes, including promotions. */
  item_subtotal?: number;
  /** The tax total of the order's items including promotions. */
  item_tax_total?: number;
  /** The total of the order's items including taxes and promotions. */
  item_total?: number;
  /** The order's items. */
  items?: VendorOrderLineItem[];
  /** The order's metadata, can hold custom key-value pairs. */
  metadata?: VendorOrderDetailsMetadata;
  /** The total of the order's items excluding taxes, including promotions. */
  original_item_subtotal?: number;
  /** The tax total of the order's items excluding promotions. */
  original_item_tax_total?: number;
  /** The total of the order's items including taxes, excluding promotions. */
  original_item_total?: number;
  /** The order's shipping total excluding taxes, including promotions. */
  original_shipping_subtotal?: number;
  /** The tax total of the order's shipping excluding promotions. */
  original_shipping_tax_total?: number;
  /** The order's shipping total including taxes, excluding promotions. */
  original_shipping_total?: number;
  /** The order's total excluding taxes, including promotions. */
  original_subtotal?: number;
  /** The order's tax total, excluding promotions. */
  original_tax_total?: number;
  /** The order's total excluding promotions, including taxes. */
  original_total?: number;
  /** The order's payment collections. */
  payment_collections?: VendorOrderPaymentCollection[];
  /** The order's payment status. */
  payment_status?: VendorOrderDetailsPaymentStatus;
  /** The ID of the region associated with the order. */
  region_id?: string;
  /** The ID of the sales channel the order is placed in. */
  sales_channel_id?: string;
  shipping_address?: VendorOrderAddress;
  /** The order's shipping methods. */
  shipping_methods?: VendorOrderShippingMethod[];
  /** The order's shipping total excluding taxes, including promotions. */
  shipping_subtotal?: number;
  /** The tax total of the order's shipping. */
  shipping_tax_total?: number;
  /** The order's shipping total including taxes and promotions. */
  shipping_total?: number;
  /** The order's total excluding taxes, including promotions. */
  subtotal?: number;
  summary?: VendorOrderSummary;
  /** The order's tax total including promotions. */
  tax_total?: number;
  /** The order's total including taxes and promotions. */
  total?: number;
  /** The date the order was updated. */
  updated_at?: string;
  /** The order's version. */
  version?: number;
}
