/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorOnboardingContext } from './vendorOnboardingContext';
import type { VendorOnboardingData } from './vendorOnboardingData';
import type { VendorPayoutAccount } from './vendorPayoutAccount';

/**
 * An onboarding object with its properties
 */
export interface VendorOnboarding {
  /**
   * Additional context stored with the onboarding.
   * @nullable
   */
  context?: VendorOnboardingContext;
  /** The date with timezone at which the resource was created. */
  created_at?: string;
  /**
   * Additional data stored with the onboarding.
   * @nullable
   */
  data?: VendorOnboardingData;
  /** The unique identifier of the onboarding. */
  id: string;
  /** The payout account this onboarding belongs to. */
  payout_account?: VendorPayoutAccount;
  /** The date with timezone at which the resource was last updated. */
  updated_at?: string;
}
