/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorOrderPaymentCollectionMetadata } from './vendorOrderPaymentCollectionMetadata';
import type { VendorOrderPaymentCollectionStatus } from './vendorOrderPaymentCollectionStatus';

/**
 * The payment collection's details.
 */
export interface VendorOrderPaymentCollection {
  /** The total amount to be paid. */
  amount?: number;
  /** The total authorized amount of the collection's payments. */
  authorized_amount?: number;
  /** The total captured amount of the collection's payments. */
  captured_amount?: number;
  /** The date the payment collection was completed. */
  completed_at?: string;
  /** The date the payment collection was created. */
  created_at?: string;
  /** The payment collection's currency code. */
  currency_code?: string;
  /** The payment collection's ID. */
  id?: string;
  /** The payment collection's metadata, can hold custom key-value pairs. */
  metadata?: VendorOrderPaymentCollectionMetadata;
  /** The total refunded amount of the collection's payments. */
  refunded_amount?: number;
  /** The ID of the region this payment collection is associated with. */
  region_id?: string;
  /** The payment collection's status. */
  status?: VendorOrderPaymentCollectionStatus;
  /** The date the payment collection was updated. */
  updated_at?: string;
}
