/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

export type VendorListProductsParams = {
/**
 * The number of items to skip before starting to collect the result set.
 */
offset?: number;
/**
 * The number of items to return.
 */
limit?: number;
/**
 * Comma-separated fields to include in the response.
 */
fields?: string;
/**
 * The order of the returned items.
 */
order?: string;
};
