/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorProductOptionMetadata } from './vendorProductOptionMetadata';
import type { VendorProductOptionValue } from './vendorProductOptionValue';

/**
 * A product option object with its properties
 */
export interface VendorProductOption {
  /** The date with timezone at which the resource was created. */
  created_at: string;
  /**
   * The date with timezone at which the resource was deleted.
   * @nullable
   */
  deleted_at?: string | null;
  /** The unique identifier of the product option. */
  id: string;
  /** An optional key-value map with additional details. */
  metadata?: VendorProductOptionMetadata;
  /** The title of the product option. */
  title: string;
  /** The date with timezone at which the resource was last updated. */
  updated_at: string;
  /** The associated product option values. */
  values?: VendorProductOptionValue[];
}
