/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

export type VendorDeleteFulfillmentSet200 = {
  /** Whether or not the items were deleted. */
  deleted?: boolean;
  /** The ID of the deleted Fulfillment Set. */
  id?: string;
  /** The type of the object that was deleted. */
  object?: string;
};
