/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminServiceZone } from './adminServiceZone';

export type VendorCreateServiceZone201 = {
  service_zone?: AdminServiceZone;
};
