/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorStockLocation } from './vendorStockLocation';
import type { VendorServiceZone } from './vendorServiceZone';

/**
 * The service zone's fulfillment set.
 */
export interface VendorFulfillmentSet {
  /** The fulfillment set's created at. */
  created_at: string;
  /** The fulfillment set's deleted at. */
  deleted_at: string;
  /** The fulfillment set's ID. */
  id: string;
  location: VendorStockLocation;
  /** The fulfillment set's name. */
  name: string;
  /** The fulfillment set's service zones. */
  service_zones: VendorServiceZone[];
  /** The fulfillment set's type. */
  type: string;
  /** The fulfillment set's updated at. */
  updated_at: string;
}
