/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorProduct } from './vendorProduct';

export type VendorCreateProduct201 = {
  product?: VendorProduct;
};
