/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorFulfillmentSet } from './vendorFulfillmentSet';
import type { VendorGeoZone } from './vendorGeoZone';
import type { VendorShippingOption } from './vendorShippingOption';

/**
 * The shipping option's service zone.
 */
export interface VendorServiceZone {
  /** The service zone's created at. */
  created_at: string;
  /** The service zone's deleted at. */
  deleted_at: string;
  fulfillment_set: VendorFulfillmentSet;
  /** The service zone's fulfillment set id. */
  fulfillment_set_id: string;
  /** The service zone's geo zones. */
  geo_zones: VendorGeoZone[];
  /** The service zone's ID. */
  id: string;
  /** The service zone's name. */
  name: string;
  /** The service zone's shipping options. */
  shipping_options: VendorShippingOption[];
  /** The service zone's updated at. */
  updated_at: string;
}
