/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorProductCategoryMetadata } from './vendorProductCategoryMetadata';

/**
 * A product category object with its properties
 */
export interface VendorProductCategory {
  /** The child categories. */
  category_children?: VendorProductCategory[];
  /** The date with timezone at which the resource was created. */
  created_at: string;
  /**
   * The date with timezone at which the resource was deleted.
   * @nullable
   */
  deleted_at?: string | null;
  /** The handle of the product category. */
  handle?: string;
  /** The unique identifier of the product category. */
  id: string;
  /** Whether the product category is active. */
  is_active?: boolean;
  /** Whether the product category is internal. */
  is_internal?: boolean;
  /** An optional key-value map with additional details. */
  metadata?: VendorProductCategoryMetadata;
  /** The name of the product category. */
  name: string;
  /**
   * The parent category.
   * @nullable
   */
  parent_category?: VendorProductCategory;
  /** The rank of the category among sibling categories. */
  rank?: number;
  /** The date with timezone at which the resource was last updated. */
  updated_at: string;
}
