/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorPayoutAccountContext } from './vendorPayoutAccountContext';
import type { VendorPayoutAccountData } from './vendorPayoutAccountData';
import type { VendorOnboarding } from './vendorOnboarding';
import type { VendorPayout } from './vendorPayout';
import type { VendorPayoutAccountStatus } from './vendorPayoutAccountStatus';

/**
 * A payout account object with its properties
 */
export interface VendorPayoutAccount {
  /**
   * Context data stored with the payout account.
   * @nullable
   */
  context?: VendorPayoutAccountContext;
  /** The date with timezone at which the resource was created. */
  created_at?: string;
  /** Additional data stored with the payout account. */
  data: VendorPayoutAccountData;
  /** The unique identifier of the payout account. */
  id: string;
  /**
   * The onboarding associated with the payout account.
   * @nullable
   */
  onboarding?: VendorOnboarding;
  /** The payouts associated with this account. */
  payouts?: VendorPayout[];
  /** Reference ID used by the payment processor. */
  reference_id: string;
  /** The status of the payout account. */
  status: VendorPayoutAccountStatus;
  /** The date with timezone at which the resource was last updated. */
  updated_at?: string;
}
