/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A schema for the update seller request body.
 */
export interface VendorUpdateSeller {
  /**
   * A description of the seller.
   * @nullable
   */
  description?: string | null;
  /**
   * A unique handle for the seller.
   * @minLength 1
   */
  handle?: string;
  /**
   * The name of the seller.
   * @minLength 1
   */
  name?: string;
  /**
   * URL to the seller's photo.
   * @nullable
   */
  photo?: string | null;
}
