/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorMember } from './vendorMember';

/**
 * A seller object with its properties
 */
export interface VendorSeller {
  /** The date with timezone at which the resource was created. */
  created_at: string;
  /**
   * A description of the seller.
   * @nullable
   */
  description?: string | null;
  /** A unique handle for the seller. */
  handle: string;
  /** The unique identifier of the seller. */
  id: string;
  /** The members associated with the seller. */
  members?: VendorMember[];
  /** The name of the seller. */
  name: string;
  /**
   * URL to the seller's photo.
   * @nullable
   */
  photo?: string | null;
  /** The date with timezone at which the resource was last updated. */
  updated_at: string;
}
