/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorStockLocation } from './vendorStockLocation';

export type VendorListStockLocations200 = {
  stock_locations?: VendorStockLocation[];
};
