/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */
import type { VendorMemberRole } from './vendorMemberRole';
import type { VendorSeller } from './vendorSeller';

/**
 * A member object with its properties
 */
export interface VendorMember {
  /**
   * The member's biography.
   * @nullable
   */
  bio?: string | null;
  /** The date with timezone at which the resource was created. */
  created_at: string;
  /** The email of the member. */
  email: string;
  /** The unique identifier of the member. */
  id: string;
  /**
   * The name of the member.
   * @nullable
   */
  name?: string | null;
  /**
   * URL to the member's photo.
   * @nullable
   */
  photo?: string | null;
  /** The role of the member. */
  role: VendorMemberRole;
  /**
   * The seller associated with the member.
   * @nullable
   */
  seller?: VendorSeller;
  /** The date with timezone at which the resource was last updated. */
  updated_at: string;
}
