/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Additional data stored with the payout.
 * @nullable
 */
export type VendorPayoutData = { [key: string]: unknown } | null;
