/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Additional metadata for the product.
 */
export type VendorCreateProductMetadata = { [key: string]: unknown };
