/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Medusa API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The role to assign to the invited member.
 */
export type VendorInviteMemberRole = typeof VendorInviteMemberRole[keyof typeof VendorInviteMemberRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VendorInviteMemberRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;
