export const MISSING_DIR_OR_EMPTY_PROJECT = "MISSING_DIR_OR_EMPTY_PROJECT";
export const MISSING_CONFIG = "MISSING_CONFIG";
export const BUILD_MISSING_REGISTRY_FILE = "BUILD_MISSING_REGISTRY_FILE";
export const CODGEN_MISSING_MEDUSA_CONFIG_FILE = "CODGEN_MISSING_MEDUSA_CONFIG_FILE";