export const defaultStoreOfferFields = [
  "id",
  "seller_id",
  "variant_id",
  "product_id",
  "shipping_profile_id",
  "sku",
  "ean",
  "upc",
  "metadata",
  "created_at",
  "updated_at",
  "seller.id",
  "seller.name",
  "seller.handle",
  "product_variant.id",
  "product_variant.title",
  "product_variant.sku",
  "product_variant.price_set.id",
  "shipping_profile.id",
  "shipping_profile.name",
  "prices.id",
  "prices.amount",
  "prices.currency_code",
  "prices.min_quantity",
  "prices.max_quantity",
  "inventory_item_link.id",
  "inventory_item_link.required_quantity",
  "inventory_item_link.inventory_item_id",
  "inventory_item_link.inventory_item.id",
  "inventory_item_link.inventory_item.sku",
  "inventory_item_link.inventory_item.location_levels.id",
  "inventory_item_link.inventory_item.location_levels.location_id",
  "inventory_item_link.inventory_item.location_levels.stocked_quantity",
]

export const storeOfferQueryConfig = {
  list: {
    defaults: defaultStoreOfferFields,
    defaultLimit: 50,
    isList: true,
  },
  retrieve: {
    defaults: defaultStoreOfferFields,
    isList: false,
  },
}
