import path from "path";
import { DIST_DIR } from "./constants";
import { ensureDir } from "./fs";
import { getRoutes } from "./routes";
import type { RouteInfo } from "../types";

export { getRoutes } from "./routes";
export { recursiveReadDir, pathExists, ensureDir } from "./fs";
export { normalizeApiPath, normalizePathSep } from "./path";
export { DIST_DIR, API_DIR, ROUTE_FILE_PATTERN } from "./constants";

export function generateRouteTypes(routes: RouteInfo[]): string {
    const queries: string[] = [];
    const mutations: string[] = [];
    const deletes: string[] = [];

    for (const route of routes) {
        const routeKey = JSON.stringify(route.route);

        for (const handler of route.handlers) {
            const input = handler.input || "unknown";
            const output = handler.output || "unknown";
            const routeDef = `RouteDef<${input}, ${output}>`;

            switch (handler.method) {
                case "GET":
                    queries.push(`        ${routeKey}: ${routeDef};`);
                    break;
                case "POST":
                    mutations.push(`        ${routeKey}: ${routeDef};`);
                    break;
                case "DELETE":
                    deletes.push(`        ${routeKey}: ${routeDef};`);
                    break;
            }
        }
    }

    const queriesContent = queries.sort().join("\n");
    const mutationsContent = mutations.sort().join("\n");
    const deletesContent = deletes.sort().join("\n");

    return `// This file is generated automatically by Mercur.js
// Do not edit this file manually

// Type definitions for Mercur API routes

export type RouteDef<TInput = unknown, TOutput = unknown> = {
    input: TInput;
    output: TOutput;
};

export type Router = {
    queries: {
${queriesContent}
    };
    mutations: {
${mutationsContent}
    };
    deletes: {
${deletesContent}
    };
};
`;
}

export async function writeRouteTypes() {
    const entryFilePath = path.join(process.cwd(), DIST_DIR, "routes.d.ts");
    const entryDir = path.dirname(entryFilePath);

    await ensureDir(entryDir);

    const routes = await getRoutes();
    const routeTypes = generateRouteTypes(routes);


}
