export const storeOrderGroupFields = [
  "id",
  "display_id",
  "customer_id",
  "seller_count",
  "total",
  "created_at",
  "updated_at",
  "orders",
  "orders.id",
  "orders.display_id",
  "orders.status",
  "orders.fulfillment_status",
  "orders.payment_status",
  "orders.currency_code",
  "orders.total",
  "orders.shipping_total",
  "orders.created_at",
  "orders.seller_id",
  "orders.seller",
  "orders.seller.id",
  "orders.seller.name",
  "orders.items",
  "orders.items.variant",
  "orders.items.variant.product",
  "orders.items.variant.product.seller",
  "orders.items.variant.product.seller.id",
  "orders.items.variant.product.seller.name",
]

export const storeOrderGroupQueryConfig = {
  list: {
    defaults: storeOrderGroupFields,
    allowed: storeOrderGroupFields,
    isList: true,
  },
  retrieve: {
    defaults: storeOrderGroupFields,
    allowed: storeOrderGroupFields,
    isList: false,
  },
}
