export const defaultStoreProductFields = [
  "id",
  "title",
  "subtitle",
  "status",
  "external_id",
  "description",
  "handle",
  "is_giftcard",
  "discountable",
  "thumbnail",
  "collection_id",
  "type_id",
  "weight",
  "length",
  "height",
  "width",
  "hs_code",
  "origin_country",
  "mid_code",
  "material",
  "created_at",
  "updated_at",
  "metadata",
  "*type",
  "*collection",
  "*tags",
  "*images",
  "*categories",
  "*variants",
  "*variants.options",
  "*options",
  "*options.values",
  "product_attribute_values.id",
  "product_attribute_values.name",
  "product_attribute_values.rank",
  "product_attribute_values.attribute_id",
  "product_attribute_values.attribute.id",
  "product_attribute_values.attribute.name",
  "product_attribute_values.attribute.handle",
  "product_attribute_values.attribute.type",
  "product_attribute_values.attribute.is_variant_axis",
  "product_attribute_values.attribute.is_required",
  "product_attribute_values.attribute.rank",
  "product_attribute_values.attribute.values.id",
  "product_attribute_values.attribute.values.name",
  "product_attribute_values.attribute.values.rank",
  "scoped_attributes.id",
  "scoped_attributes.name",
  "scoped_attributes.handle",
  "scoped_attributes.type",
  "scoped_attributes.is_variant_axis",
  "scoped_attributes.values.id",
  "scoped_attributes.values.name",
  "scoped_attributes.values.rank",
]

export const storeProductQueryConfig = {
  list: {
    defaults: defaultStoreProductFields,
    defaultLimit: 50,
    isList: true,
  },
  retrieve: {
    defaults: defaultStoreProductFields,
    isList: false,
  },
}
