import path from "path"
import fs from "fs/promises"
import { writeRouteTypes, DIST_DIR, ensureDir } from "@/src/codegen"

/**
 * Preflight for `mercur build`. Emits everything that lives under the
 * consuming project's `.mercur/` directory:
 *
 *   .mercur/routes.d.ts            — the generated route map (existing)
 *   .mercur/types.d.ts             — TypeScript path-mapping shim that makes
 *                                    `import { ProductDTO } from "@medusajs/types"`
 *                                    return the Mercur shape
 *   .mercur/tsconfig.augment.json  — path map redirecting `@medusajs/types`
 *                                    to the shim above
 *
 * Nothing is written into `node_modules`. The `.medusa/types/modules-bindings.d.ts`
 * post-process (`postprocessModulesBindings`) runs after `medusa build`, not
 * here — see `commands/build.ts`.
 *
 * See SPEC-005 / SPEC-006.
 */
export async function preflightBuild(rootDir: string): Promise<void> {
  // 1. Route map (delegates to the existing codegen path so `mercur codegen`
  //    and the build preflight stay in lockstep).
  await writeRouteTypes(rootDir)

  // 2. Type-shim + tsconfig augment.
  const mercurDir = path.join(rootDir, DIST_DIR)
  await ensureDir(mercurDir)

  const shimPath = path.join(mercurDir, "types.d.ts")
  await fs.writeFile(shimPath, buildTypesShim(), "utf-8")

  const augmentPath = path.join(mercurDir, "tsconfig.augment.json")
  await fs.writeFile(augmentPath, buildTsconfigAugment(), "utf-8")
}

/**
 * The path-mapping shim. Resolved when consumers' tsconfig extends
 * `./.mercur/tsconfig.augment.json` — TypeScript then redirects every
 * `@medusajs/types` import through this file.
 *
 * The file uses `export type *` / `export type {…}` exclusively so it
 * never claims a runtime export upstream doesn't have. Runtime resolution
 * of `@medusajs/types` still goes through the real package (which is
 * itself types-only).
 */
function buildTypesShim(): string {
  // Hand-enumerated list of upstream `ModuleImplementations` keys (Medusa
  // 2.13.4). The shim re-declares the interface explicitly because the
  // framework ships its own `declare module "@medusajs/types"` for
  // `product: IProductModuleService`; a competing augmentation would
  // collide on "subsequent property declarations must have the same type".
  // See SPEC-005 / SPEC-006 for the constraint discussion.
  return `// AUTO-GENERATED by \`mercur build\` preflight — do not edit.
// See SPEC-005 / SPEC-006 for the design notes.
//
// This file is the path-mapping shim resolved when downstream code writes
// \`import { ProductDTO } from "@medusajs/types"\`. \`tsconfig.augment.json\`
// (emitted alongside) maps \`@medusajs/types\` here and
// \`@medusajs/types-original\` to the real upstream package.

// 1. Forward every upstream type except the ones we replace below.
//    \`export type *\` is intentional — the upstream package is types-only,
//    so the shim must never claim a runtime export.
//    \`ModuleImplementations\` is explicitly excluded so the re-declaration
//    further down is the only one visible to consumers.
export type * from "@medusajs/types-original"

// 2. Replace ProductDTO with the Mercur shape. Same name; named re-export
//    wins over \`export type *\` per TS module rules.
export type { MercurProductDTO as ProductDTO } from "@mercurjs/types/product"

// 3. Replace ProductStatus. This is a *type* export only — upstream
//    \`ProductStatus\` in @medusajs/types is a string-literal union with no
//    runtime value, and path mapping is types-only. Code that needs a
//    runtime constant imports \`ProductStatusValues\` from
//    \`@mercurjs/types/product\` directly (that import is not path-mapped).
export type { ProductStatus } from "@mercurjs/types/product"

// 4. Re-declare ModuleImplementations explicitly. \`declare module\`
//    augmentation can't replace \`product: IProductModuleService\` with a
//    different service type — TS rejects interface merges with conflicting
//    property types. Replacement (not augmentation) is the only option.
//
//    Every upstream key is re-listed verbatim. The Mercur-only modules
//    (admin_ui, codegen, commission, custom_fields, offer, payout, seller,
//    subscription, vendor_ui) come in via Medusa's per-project
//    \`generateContainerTypes\` output, which augments the same interface
//    with module-specific entries.
import type {
  IApiKeyModuleService,
  IAuthModuleService,
  ICacheService,
  ICartModuleService,
  ICurrencyModuleService,
  ICustomerModuleService,
  IEventBusModuleService,
  IFileModuleService,
  IFulfillmentModuleService,
  IInventoryService,
  ILockingModule,
  INotificationModuleService,
  IOrderModuleService,
  IPaymentModuleService,
  IPricingModuleService,
  IPromotionModuleService,
  IRbacModuleService,
  IRegionModuleService,
  ISalesChannelModuleService,
  ISettingsModuleService,
  IStockLocationService,
  IStoreModuleService,
  ITaxModuleService,
  IUserModuleService,
  IWorkflowEngineService,
} from "@medusajs/types-original"
import type { MercurProductModuleService } from "@mercurjs/core/modules/product"

export interface ModuleImplementations {
  // Upstream module services (verbatim from @medusajs/framework, Medusa
  // 2.13.4). \`product\` is intentionally omitted from this block and
  // declared below with the Mercur override.
  api_key: IApiKeyModuleService
  auth: IAuthModuleService
  cache: ICacheService
  cart: ICartModuleService
  currency: ICurrencyModuleService
  customer: ICustomerModuleService
  event_bus: IEventBusModuleService
  file: IFileModuleService
  fulfillment: IFulfillmentModuleService
  inventory: IInventoryService
  locking: ILockingModule
  notification: INotificationModuleService
  order: IOrderModuleService
  payment: IPaymentModuleService
  pricing: IPricingModuleService
  promotion: IPromotionModuleService
  rbac: IRbacModuleService
  region: IRegionModuleService
  sales_channel: ISalesChannelModuleService
  settings: ISettingsModuleService
  stock_location: IStockLocationService
  store: IStoreModuleService
  tax: ITaxModuleService
  user: IUserModuleService
  workflows: IWorkflowEngineService

  // Mercur override.
  product: MercurProductModuleService
}
`
}

/**
 * The path-map fragment. Consumers extend this from their root
 * \`tsconfig.json\`; TS then redirects every \`@medusajs/types\` import
 * through the shim above.
 *
 * The augment is JSON with comments-free output so it can be checked in or
 * re-emitted on every build without diff noise.
 */
function buildTsconfigAugment(): string {
  const payload = {
    compilerOptions: {
      paths: {
        "@medusajs/types": ["./.mercur/types.d.ts"],
        "@medusajs/types-original": ["./node_modules/@medusajs/types"],
      },
    },
  }
  return JSON.stringify(payload, null, 2) + "\n"
}

/**
 * Post-process Medusa's own \`generateContainerTypes\` output. Strips the
 * \`'product': ...\` line (and the now-unused \`IProductModuleService\` import
 * if present) from \`.medusa/types/modules-bindings.d.ts\` so the upstream
 * codegen does not re-introduce a competing \`ModuleImplementations.product\`
 * declaration that would collide with the shim's re-declared interface.
 *
 * Writes only inside the user's project (\`.medusa/\`) — never into
 * \`node_modules\`. Idempotent: re-running on a cleaned file is a no-op.
 *
 * Runs from \`commands/build.ts\` *after* \`medusa build\` completes, not
 * here in the preflight.
 */
export async function postprocessModulesBindings(
  rootDir: string,
): Promise<void> {
  const bindingsPath = path.join(
    rootDir,
    ".medusa",
    "types",
    "modules-bindings.d.ts",
  )

  let contents: string
  try {
    contents = await fs.readFile(bindingsPath, "utf-8")
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return
    throw err
  }

  let next = contents

  // 1. Strip the 'product': … line inside the interface body.
  next = next.replace(/^\s*['"]product['"]\s*:\s*[^,\n}]+,?\n/gm, "")

  // 2. If the file imported `IProductModuleService` only for that line,
  //    drop the import too.
  if (!/\bIProductModuleService\b/.test(next.replace(/^import[^;]+;\n?/gm, ""))) {
    next = next.replace(
      /^import\s+type\s*\{\s*IProductModuleService\s*\}\s+from\s+['"]@medusajs\/framework\/types['"]\s*;?\n?/gm,
      "",
    )
  }

  if (next !== contents) {
    await fs.writeFile(bindingsPath, next, "utf-8")
  }
}
