export const adminProductFields = [
  "id",
  "title",
  "subtitle",
  "status",
  "is_active",
  "is_restricted",
  "external_id",
  "description",
  "handle",
  "is_giftcard",
  "discountable",
  "thumbnail",
  "collection_id",
  "type_id",
  "brand_id",
  "created_by",
  "created_by_actor",
  "weight",
  "length",
  "height",
  "width",
  "hs_code",
  "origin_country",
  "mid_code",
  "material",
  "created_at",
  "updated_at",
  "deleted_at",
  "metadata",
  "*type",
  "*brand",
  "*collection",
  "*tags",
  "*images",
  "*categories",
  "*variants",
  "*variants.prices",
  "variants.prices.price_rules.value",
  "variants.prices.price_rules.attribute",
  "*variant_attributes",
  "*variant_attributes.values",
]

export const adminProductRetrieveFields = [
  ...adminProductFields,
  "*changes",
]

export const adminProductQueryConfig = {
  list: {
    defaults: adminProductFields,
    defaultLimit: 50,
    isList: true,
  },
  retrieve: {
    defaults: adminProductRetrieveFields,
    isList: false,
  },
}
