export const adminProductFields = [
  "id",
  "title",
  "subtitle",
  "status",
  "is_active",
  "is_restricted",
  "external_id",
  "description",
  "handle",
  "is_giftcard",
  "discountable",
  "thumbnail",
  "collection_id",
  "type_id",
  "brand_id",
  "created_by",
  "created_by_actor",
  "weight",
  "length",
  "height",
  "width",
  "hs_code",
  "origin_country",
  "mid_code",
  "material",
  "created_at",
  "updated_at",
  "deleted_at",
  "metadata",
  "*type",
  "*brand",
  "*collection",
  "*tags",
  "*images",
  "*categories",
  "*sellers",
  "*variants",
  "*variants.attribute_values",
  "*variants.attribute_values.attribute",
  "*variant_attributes",
  "*variant_attributes.values",
  "*custom_attributes",
  "*custom_attributes.values",
  "*attribute_values",
  "*attribute_values.attribute",
]

export const adminProductRetrieveFields = [
  ...adminProductFields,
  "*changes",
]

export const adminProductQueryConfig = {
  list: {
    defaults: adminProductFields,
    defaultLimit: 50,
    isList: true,
  },
  retrieve: {
    defaults: adminProductRetrieveFields,
    isList: false,
  },
}

export const adminProductVariantFields = [
  "id",
  "title",
  "sku",
  "ean",
  "upc",
  "isbn",
  "asin",
  "gtin",
  "barcode",
  "hs_code",
  "mid_code",
  "variant_rank",
  "weight",
  "length",
  "height",
  "width",
  "origin_country",
  "material",
  "metadata",
  "created_at",
  "updated_at",
  "product_id",
  "*attribute_values",
  "*attribute_values.attribute",
]

export const adminProductVariantQueryConfig = {
  list: {
    defaults: adminProductVariantFields,
    defaultLimit: 50,
    isList: true,
  },
  retrieve: {
    defaults: adminProductVariantFields,
    isList: false,
  },
}
